### ISSUE TITLE
Google Camera and Photos apps are not working anymore after SQ1A.220205.002.2022022818 update

### ISSUE THREAD

**Issue by pkhomyakov-rms** [GrapheneOS/os-issue-tracker#1026] opened 2022-03-02 13:42 UTC
Pixel 5a, autoupdated to latest SQ1A.220205.002.2022022818

- Google Camera stopped working: opens to black screen.
- Google Photos (used by camera for some functions) stoped working: opening briefly then crashes.

Both worked without issues in previous release.

**Comment by w0d4** [comment] 2022-03-02 17:39
Hi, I have exactly the same issue.
Google camera is only black since last update.
Can I contribute any logs for this?
SQ1A.220205.002.2022022818 also worked well for me.

**Comment by thestinger** [comment] 2022-03-02 18:41
It's very unlikely that this is tied to the OS update. It's likely from a recent Google Camera update.

Can reproduce the problem:

03-02 13:41:19.793 11998 11998 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/data/app/~~9ptbveiBAMJpZvNJO5WvtA==/com.google.android.GoogleCamera-jWdvZ6BMdLvfhvA7a2g78w==/base.apk!/lib/arm64-v8a/libpairipcore.so" segment 1: Permission denied

**Comment by thestinger** [comment] 2022-03-02 18:46
We think we know why this is happening and it will be addressed by the next release.

**Comment by pkhomyakov-rms** [comment] 2022-03-02 18:49
In my case Google Camera was last updated on Jan 22nd. I did take a bunch of photos in last few days, no issues with either camera or viewing in photos. This started happening after I finally got around to update the phone to latest this morning.

**Comment by thestinger** [comment] 2022-03-02 18:57
We're aware of the issue now and it's being resolved.

**Comment by pkhomyakov-rms** [comment] 2022-03-02 19:01
Thanks! Does this apply to photos as well or is it something else?

**Comment by flawedworld** [comment] 2022-03-02 19:50
Google Photos was crashing because of Google Camera crashing. If you can't wait, uninstall Google Camera and it should work.

**Comment by thestinger** [comment] 2022-03-02 19:56
This will be fixed in the next release. Further information isn't needed from users about it.

**Closed** 2022-03-03 01:53 UTC
Labels: bug, Pixel 5, Pixel 4a (5G), Pixel 5a
