### ISSUE TITLE
[Feature Request] Long press power button for flashlight

### ISSUE THREAD

**Issue by Kyuunex** [GrapheneOS/os-issue-tracker#2115] opened 2023-04-14 05:25 UTC
I'm coming from LineageOS, recently bought a Pixel specifically for GrapheneOS and this the only feature I can't go without.

It is incredibly inconvenient to light up the screen, swipe down and tap the flashlight icon when I'm outside in dark and need a flashlight immediately. Lighting up the screen also makes my eyes adjust to the light for a couple of seconds, making it even harder to see in the dark, potentially putting me in danger.

When the screen is off, long pressing the power button to turn on/off flashlight is a feature I really need and would like to request.

**Comment by thestinger** [comment] 2023-04-14 07:50
This is a duplicate of previous issues.

**Closed** 2023-04-14 07:50 UTC
