### ISSUE TITLE
Screen flickers an eventually blacks out (Pixel 7 Pro)

### ISSUE THREAD

**Issue by klaus1k** [GrapheneOS/os-issue-tracker#1837] opened 2022-12-19 10:38 UTC
Hello,
I got an issue, that I interestingly also had on GrapheneoOS on Pixel 6 Pro:

On random occasions, the screen on my Pixel 7 Pro starts to flicker and after some time blacks out completely. It still reacts to touch input. After a reboot everything works fine again.
I am on the newest stable release of Graphene OS.

Possible correlations observed:
- happens mostly if phone was not rebooted for more than ~ a day.
- flickering starts most often when viewing the tab switching view in Mull; then screen flickers everywhere in the OS, the black-out-times grow longer. The screen is still responsive, so that I can reboot the phone by long press on the power button and tapping the area where the "reboot" button should be displayed. Everything works fine again after reboot.
- screen black out sometimes also happening without the aforementioned flickering when playing videos in full screen (Newpipe App or YouTube via Mull). Can be reproduced: works fine in the small video view, when clicking on the full screen icon, screen blacks out. Sound is still playing. After screen lock, screen is on again. If I try Fullscreen again, it blacks out again. If I restart the phone everything works fine again afterwards.

If logs or more information is needed, I am happy to provide them. I cannot explicitly trigger this behavior, so I would have to wait for it to happen again.

**Comment by klaus1k** [comment] 2022-12-19 16:46
Thanks, will post it here the next time it occurs!

**Comment by Zi-SH** [comment] 2022-12-21 16:26
I've also had run-ins with this issue while using resource intensive sites in Firefox, including but not limited to Firefox. I'm using a Pixel 7 Pro as well.  

The phone is responsive to touch, but has no display. Holding the power button returns the expected vibration as the power popup appears. Rebooting resolves the issue. 

Attempting to recreate the issue for the sake of logs, but I wanted to speak up so it isn't dismissed as an isolated issue.

**Comment by maade69** [comment] 2022-12-23 17:39
@Zi-SH can you provide an example of resource intensive site?

**Comment by Zi-SH** [comment] 2022-12-23 19:21
> @Zi-SH can you provide an example of resource intensive site?

I had initially believed it was a graphical issue, but after stress testing the devices graphics I was unable to recreate the issue. 

In regards to resource intensive sites, it wasn't one site so much as a few dozen tabs of sites with a lot of ads (in my defense I've yet to install an ad blocker because the device is only a few weeks old).  In the instance mentioned prior, it was those generic wallpaper sites that pop up by the hundreds to farm ad revenue off rehosting images.

I was able to get a log of the issue... but I was foolish and and dumped the adb to /tmp and lost it in a reboot. I can specifically remember the error talking about a frame buffer and OOM. I'll see if I can recreate it and get another copy of the logs.

**Comment by thestinger** [comment] 2023-01-03 04:40
We think it's the same as https://github.com/GrapheneOS/os-issue-tracker/issues/1830. It's an Android 13 QPR1 regression and may be fixed in the January or February release of AOSP.

**Closed by thestinger** 2023-01-03 04:40 UTC
Labels: bug
