### ISSUE TITLE
AOD text increasingly shitfts downwards

### ISSUE THREAD

**Issue by ArchitektApx** [GrapheneOS/os-issue-tracker#2120] opened 2023-04-15 18:51 UTC
I've realized that all text on the Always On Display increasingly shifts downwards its location the more you lock/unlock your phone. After a while it starts to go over the symbol for the fingerprint sensor on my P7P.

![Screenshot_20230415-203835](https://user-images.githubusercontent.com/21159658/232247792-f0c7266a-cba3-4879-a78b-4c94a6c6d6ea.png)

The shift seems to increase gradually with more time passing/more unlocks. The screenshot was taken after about 3 days of use. 
This seems to affect both modes of AOD (Clock in two lines or not) and neither disabling/re-enabling nor rebooting did resolve the issue.

**Comment by r3g-5z** [comment] 2023-04-15 20:37
This is an AOSP upstream bug. No plans to fix it on our end but we may accept a community contribution fixing it.

Duplicate of 

https://github.com/GrapheneOS/os-issue-tracker/issues/1828
https://github.com/GrapheneOS/os-issue-tracker/issues/1225
https://github.com/GrapheneOS/os-issue-tracker/issues/968

**Closed by r3g-5z** 2023-04-15 20:37 UTC
