### ISSUE TITLE
Radio Crash After Battery Died and Reboot/Charge

### ISSUE THREAD

**Issue by adrien666** [GrapheneOS/os-issue-tracker#2956] opened 2023-12-27 20:48 UTC
```
type: crash
osVersion: google/shiba/shiba:14/UQ1A.231205.015/2023121200:user/release-keys
uid: 1001 (u:r:hal_radioext_default:s0)
cmdline: /vendor/bin/hw/vendor.google.radioext@1.0-service
processUptime: 1s

abortMessage: fdsan: attempted to close file descriptor 4, expected to be unowned, actually owned by FILE* 0xdbbb7e3c60b0

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: vendor.google.r
MTE: not enabled

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (fdsan_error(char const*, ...)+552, pc 67b68)
    /apex/com.android.runtime/lib64/bionic/libc.so (android_fdsan_close_with_tag+796, pc 6786c)
    /apex/com.android.runtime/lib64/bionic/libc.so (close+16, pc 67ff0)
    /vendor/bin/hw/vendor.google.radioext@1.0-service (vendor::google::radioext::V1_0::implementation::readFrequencyFile(cam_index_e_type, cam_conf_index_e_type, android::hardware::hidl_vec<int>&)+992, pc 3cb60)
    /vendor/bin/hw/vendor.google.radioext@1.0-service 

> (vendor::google::radioext::V1_0::implementation::RadioExt::RadioExt()+216, pc 3cc78)

    /vendor/bin/hw/vendor.google.radioext@1.0-service (main+76, pc 3b3bc)
    /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+104, pc 5ad28)
```

**Comment by thestinger** [comment] 2023-12-28 04:03
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2935 and is an upstream bug out of scope of our work.

**Closed** 2023-12-28 04:02 UTC
