### ISSUE TITLE
UI differences between PIN configuration input and screen unlock input prompts

### ISSUE THREAD

**Issue by redcrate** [GrapheneOS/os-issue-tracker#1977] opened 2023-02-24 22:47 UTC
Hello,

When choosing to setup the PIN lock for the device the person is presented with what appears to be a "standard" android E.161 style input prompt to type in and confirm the PIN to use on the phone.

[https://en.wikipedia.org/wiki/E.161](https://en.wikipedia.org/wiki/E.161)

However, subsequent unlocking of the phone presents the person with what appears to be a custom PIN unlock input screen, but without the "standard" Latin character mapping onto the individual numbers (1, 2 ABC, 3 DEF, etc...).

![image](https://user-images.githubusercontent.com/85591702/221300894-7358f6bd-ea5c-4136-9e14-aa438022a074.png)

I'm assuming this custom PIN unlock screen is to support features like PIN scrambling and such. I seem to recall that prior versions did not use this custom screen unlock unless PIN scrambling was also enabled, though that may have been a long time ago or I may be mistaken.

In any case, I would like to request that the "standard" E.161 Latin alphabet character mapping also be displayed on this custom PIN unlock input screen.

I consider this "standard" character mapping to be a useful feature, as it allows me to type in my universally used "hunter2" password as PIN number: "4868372" without having to setup a password lock, which is difficult to enter using the on screen keyboard when using just my thumb.

Thank you for your time,

P.S. The password/PIN examples above are a joke and only meant to illustrate the point, my real password is: *******

**Comment by r3g-5z** [comment] 2023-02-24 23:34
Known upstream bug, not going to be tracked here or worked on by GrapheneOS. Patch welcome to fix it if available.

Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/1330

**Comment by r3g-5z** [comment] 2023-02-24 23:35
Misinterpreted the issue.

**Comment by r3g-5z** [comment] 2023-02-24 23:36
Either way, I don't think GrapheneOS modifies or touches the PIN layout at all beyond PIN scrambling.

**Comment by thestinger** [comment] 2023-02-26 04:10
This is the same UI as the stock OS and we don't plan to change it.

**Closed by thestinger** 2023-02-26 04:10 UTC
