### ISSUE TITLE
Vanadium crash?

### ISSUE THREAD

**Issue by Futurekino** [GrapheneOS/os-issue-tracker#2957] opened 2023-12-27 23:12 UTC
System crashed from no where and vanadium tried to get access and allow native code debugging but it was set that could not change on pre instlaled apps

```
type: crash
osVersion: google/bluejay/bluejay:14/UQ1A.231205.015/2023121200:user/release-keys
uid: 10095 (u:r:untrusted_app:s0:c95,c256,c512,c768)
cmdline: app.vanadium.browser
processUptime: 836s

abortMessage: GrContext is abandoned/device lost at start of CanvasContext::draw

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: RenderThread

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 62e64)
    /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1456, pc 64be80)
    /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 38730)
    /system/lib64/liblog.so (__android_log_assert+308, pc 6fd4)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw(bool)+2664, pc 292d48)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::prepareAndDraw(android::uirenderer::RenderNode*)+184, pc 2934d8)
    /system/lib64/libhwui.so (std::__1::__function::__func<android::uirenderer::renderthread::RenderThread::frameCallback(long, long, long, long)::$_0, std::__1::allocator<android::uirenderer::renderthread::RenderThread::frameCallback(long, long, long, long)::$_0>, void ()>::operator()() (.__uniq.90750746851124314286939039409884766998.943faa9544c4af3f5d65b01483b58c5a)+232, pc 2a7408)
    /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+624, pc 2840d0)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+404, pc 2a67f4)
    /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+284, pc 1430c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cf9ec)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64730)
```

**Comment by thestinger** [comment] 2023-12-28 03:58
Duplicate of #2700.

**Closed** 2023-12-28 03:58 UTC
