### ISSUE TITLE
Bug: Image preview is blurry when editing screenshot/screen capture

### ISSUE THREAD

**Issue by erra-ch** [GrapheneOS/os-issue-tracker#2284] opened 2023-06-27 18:40 UTC
Platform: Google Pixel 7a
OS Version: 13 (TQ3A.230605.012.2023062300)
Issue: When taking a screenshot, the preview when using the edit functionality is very blurry. See attached images for reference. The image looks as is should when saved in the Gallery, also if saved after doing some editing (i.e. cropping).
In other words it is still usable but still an annoying bug.

![image](https://github.com/GrapheneOS/os-issue-tracker/assets/73989943/42b1bf0b-ca8a-41f3-8c1d-8747e8bdd413)

![image](https://github.com/GrapheneOS/os-issue-tracker/assets/73989943/2c863095-3ce4-47ab-ba65-4edbc61cc776)

**Comment by thestinger** [comment] 2023-06-27 18:41
Known limitation of AOSP Gallery and not a bug but rather it's written to use a very low resolution. A proper pull request changing this would be accepted. A previous PR did not meet our standards and wasn't merged. 

We aren't going to track legacy AOSP sample app limitations here.

**Closed by thestinger** 2023-06-27 18:41 UTC
