### ISSUE TITLE
Sandboxed Google play crashes constantly 

### ISSUE THREAD

**Issue by MisterLovaLova** [GrapheneOS/os-issue-tracker#1734] opened 2022-11-25 07:47 UTC
```
type: crash
osVersion: google/oriole/oriole:13/TP1A.221105.002/2022111800:user/release-keys
package: com.google.android.gms:224113044
process: com.google.android.gms.persistent
processUptime: 6296515 + 351 ms
GmsCompatConfig version: 17

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.CONFIGURED_NETWORKS_CHANGE flg=0x4000010 (has extras) } in com.google.android.gms.wearable.node.WifiService$SavedNetworkBroadcastReceiver@6ed51f6
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1800)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.SecurityException: WifiService: Neither user 10161 nor current process has android.permission.READ_WIFI_CREDENTIAL.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.net.wifi.IWifiManager$Stub$Proxy.getPrivilegedConfiguredNetworks(IWifiManager.java:2210)
	at android.net.wifi.WifiManager.getPrivilegedConfiguredNetworks(WifiManager.java:1697)
	at cbwo.e(:com.google.android.gms@224113044@22.41.13 (190400-480714934):4)
	at cbwo.i(:com.google.android.gms@224113044@22.41.13 (190400-480714934):3)
	at cbwo.g(:com.google.android.gms@224113044@22.41.13 (190400-480714934):1)
	at com.google.android.gms.wearable.node.WifiService$SavedNetworkBroadcastReceiver.a(:com.google.android.gms@224113044@22.41.13 (190400-480714934):6)
	at com.google.android.gms.libs.punchclock.tracing.TracingBroadcastReceiver.onReceive(:com.google.android.gms@224113044@22.41.13 (190400-480714934):2)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2285)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2313)
	at android.content.ContextWrapper.enforceCallingOrSelfPermission(ContextWrapper.java:948)
	at com.android.server.wifi.WifiServiceImpl.enforceReadCredentialPermission(WifiServiceImpl.java:1070)
	at com.android.server.wifi.WifiServiceImpl.getPrivilegedConfiguredNetworks(WifiServiceImpl.java:3029)


```

**Comment by thestinger** [comment] 2022-11-25 08:01
Duplicate of an issue resolved in the next OS release already.

**Closed** 2022-11-25 08:00 UTC
