### ISSUE TITLE
Sandboxed Google play crashed

### ISSUE THREAD

**Issue by VRT-secure** [GrapheneOS/os-issue-tracker#1669] opened 2022-11-10 18:48 UTC
Today I get this error a few times on my phone pixel 4a

**Comment by VRT-secure** [comment] 2022-11-10 18:50
Sandbox Google play now on my phone in work space it's work via Shelter

**Comment by coltonbh** [comment] 2022-11-10 18:59
More details: 
```
type: crash
osVersion: google/sunfish/sunfish:13/TP1A.221105.002/2022110800:user/release-keys
package: com.google.android.gms:224312044
process: com.google.android.gms

dazd: rethrowing exception from lowpool[2]
	at zxg.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at arre.lx(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at arre.dispatchMessage(:com.google.android.gms@224312044@22.43.12 (190400-483592595):11)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: cuwy: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.security__nonwearable-TelecomTaskService_onRunTaskAsync(Unknown Source:0)
		at tk_trace.security__nonwearable-TelecomTaskService-IMessenger_0(Unknown Source:0)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.content.pm.ParceledListSlice.getList()' on a null object reference
	at android.telecom.TelecomManager.getAllPhoneAccountHandles(TelecomManager.java:1472)
	at bscy.a(:com.google.android.gms@224312044@22.43.12 (190400-483592595):2)
	at com.google.android.gms.security.snet.TelecomTaskService.a(:com.google.android.gms@224312044@22.43.12 (190400-483592595):2)
	at arsq.call(:com.google.android.gms@224312044@22.43.12 (190400-483592595):4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at zxw.c(:com.google.android.gms@224312044@22.43.12 (190400-483592595):6)
	at zxw.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at aadb.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by muhomorr** [comment] 2022-11-10 19:03
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/1664

Update GmsCompatConfig to version 15 to fix this issue.

**Closed by muhomorr** 2022-11-10 19:03 UTC
