### ISSUE TITLE
Surfaceflinger Crash

### ISSUE THREAD

**Issue by Ruben-Fischer** [GrapheneOS/os-issue-tracker#2831] opened 2023-12-12 00:11 UTC
```
type: crash
osVersion: google/husky/husky:14/UQ1A.231205.015/2023120800:user/release-keys
uid: 1000 (u:r:surfaceflinger:s0)
cmdline: /system/bin/surfaceflinger
processUptime: 9s

signal: 11 (SIGSEGV), code 9 (SEGV_MTESERR), faultAddr 700dbe792ca4f49
threadName: surfaceflinger
MTE: enabled

backtrace:
    /system/bin/surfaceflinger (android::SurfaceFlinger::commit(android::PhysicalDisplayId, android::ftl::SmallMap<android::PhysicalDisplayId, android::scheduler::FrameTarget const*, 3ul, std::__1::equal_to<android::PhysicalDisplayId> > const&)+800, pc 20ef60)
    /system/bin/surfaceflinger (android::scheduler::Scheduler::onFrameSignal(android::ICompositor&, android::VsyncId, android::TimePoint)+364, pc 1ee39c)
    /system/lib64/libutils.so (android::Looper::pollInner(int)+376, pc 18b08)
    /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+124, pc 1892c)
    /system/bin/surfaceflinger (android::impl::MessageQueue::waitMessage()+92, pc 1deefc)
    /system/bin/surfaceflinger (android::scheduler::Scheduler::run()+28, pc 1ee21c)
    /system/bin/surfaceflinger (main+1792, pc 25b920)
    /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+104, pc 5ad08)
```

**Comment by thestinger** [comment] 2023-12-12 09:06
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2792.

**Closed by thestinger** 2023-12-12 09:06 UTC
