### ISSUE TITLE
"Sandboxed Google Play Crashed" after latest update

### ISSUE THREAD

**Issue by davidwilliams238** [GrapheneOS/os-issue-tracker#2669] opened 2023-11-08 09:39 UTC
GMSCompat displays multiple "Sandboxed Google Play Crashed" messages after booting from latest update. The error data is as follows:

```
type: crash
osVersion: google/cheetah/cheetah:14/UP1A.231105.003/2023110700:user/release-keys
package: com.google.android.gms:234313038
process: com.google.android.gms.persistent
processUptime: 7428075 + 660 ms
installer: com.android.vending
GmsCompatConfig version: 82

java.lang.RuntimeException: Rethrown by StandaloneSchedulingEngine
	at cmzk.a(:com.google.android.gms@234313038@23.43.13 (190400-577232161):455)
	at cmwk.run(:com.google.android.gms@234313038@23.43.13 (190400-577232161):9)
	at ajlc.c(:com.google.android.gms@234313038@23.43.13 (190400-577232161):50)
	at ajlc.run(:com.google.android.gms@234313038@23.43.13 (190400-577232161):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ajqf.run(:com.google.android.gms@234313038@23.43.13 (190400-577232161):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dviq: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.RuntimeException: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a126; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at bfub.apply(:com.google.android.gms@234313038@23.43.13 (190400-577232161):5)
	at ebua.d(:com.google.android.gms@234313038@23.43.13 (190400-577232161):3)
	at ebub.run(:com.google.android.gms@234313038@23.43.13 (190400-577232161):139)
	... 6 more
Caused by: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a126; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at avwq.sendBroadcastAsUser(:com.google.android.gms@234313038@23.43.13 (190400-577232161):6)
	at cvrq.a(:com.google.android.gms@234313038@23.43.13 (190400-577232161):39)
	at cvrv.g(:com.google.android.gms@234313038@23.43.13 (190400-577232161):723)
	at cvrr.c(:com.google.android.gms@234313038@23.43.13 (190400-577232161):7)
	at com.google.android.gms.time.singleuserapi.service.TrustedTimeMaintenanceTaskService.hb(:com.google.android.gms@234313038@23.43.13 (190400-577232161):186)
	at bfuc.call(:com.google.android.gms@234313038@23.43.13 (190400-577232161):32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 6 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2457)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:14540)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14450)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:15416)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2661)


```

**Comment by shaydin** [comment] 2023-11-08 19:34
Also seeing this issue. First crash was as soon as the phone rebooted, second was a couple of hours later while playing a game.

Second crash log:

```
type: crash
osVersion: google/cheetah/cheetah:14/UP1A.231105.003/2023110700:user/release-keys
package: com.google.android.gms:234313038
process: com.google.android.gms.persistent
processUptime: 3201827 + 385 ms
installer: com.android.vending
GmsCompatConfig version: 82

java.lang.RuntimeException: Rethrown by StandaloneSchedulingEngine
	at cmzk.a(:com.google.android.gms@234313038@23.43.13 (190400-577232161):455)
	at cmwk.run(:com.google.android.gms@234313038@23.43.13 (190400-577232161):9)
	at ajlc.c(:com.google.android.gms@234313038@23.43.13 (190400-577232161):50)
	at ajlc.run(:com.google.android.gms@234313038@23.43.13 (190400-577232161):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ajqf.run(:com.google.android.gms@234313038@23.43.13 (190400-577232161):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dviq: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.RuntimeException: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a126; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at bfub.apply(:com.google.android.gms@234313038@23.43.13 (190400-577232161):5)
	at ebua.d(:com.google.android.gms@234313038@23.43.13 (190400-577232161):3)
	at ebub.run(:com.google.android.gms@234313038@23.43.13 (190400-577232161):139)
	... 6 more
Caused by: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a126; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at cvrq.a(:com.google.android.gms@234313038@23.43.13 (190400-577232161):39)
	at cvrv.g(:com.google.android.gms@234313038@23.43.13 (190400-577232161):723)
	at cvrr.c(:com.google.android.gms@234313038@23.43.13 (190400-577232161):7)
	at com.google.android.gms.time.singleuserapi.service.TrustedTimeMaintenanceTaskService.hb(:com.google.android.gms@234313038@23.43.13 (190400-577232161):186)
	at bfuc.call(:com.google.android.gms@234313038@23.43.13 (190400-577232161):32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 6 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2457)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:14540)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14450)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:15416)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2661)


```

**Comment by muhomorr** [comment] 2023-11-08 20:46
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2649

**Closed by muhomorr** 2023-11-08 20:46 UTC
