### ISSUE TITLE
GrapheneOS-specific settings are not indexed

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#1955] opened 2023-02-11 00:20 UTC
I dont know but guess this is a known bug.

When searching for settings like "Internet connectivity check", they are not shown.

Any way to help implement that?

**Comment by r3g-5z** [comment] 2023-02-23 03:18
GrapheneOS settings are indexed when they're defined in the specific Settings layout's XML file. In the case with the internet connectivity check / captive portal check, it's not defined in [network_and_internet.xml](https://github.com/GrapheneOS/platform_packages_apps_Settings/blob/13/res/xml/network_and_internet.xml)'s layout file which is why some of these settings are not indexed. An example of a valid GrapheneOS-specific setting being indexed just fine is auto reboot. The non-indexed settings only show up because the [preference controller method is called to show it in the fragment that the layout uses](https://github.com/GrapheneOS/platform_packages_apps_Settings/commit/8681fb65fe3e5bc95c1ff2ab6e531b3686e2b16a#diff-9d1d1cef2695ecfeddf596cb056ab1381569197d72e37a818748320a01a3a79cR124-R126), which is a very bad implementation choice for vendor-specific settings like ours and shouldn't have been done like this in the first place.

This is actually a small bug that will be resolved when we start migrating GrapheneOS-specific settings to ExtSettings which requires a definition in the respective layout. GrapheneOS doesn't need to do anything special to get our settings indexed other than migrate old settings to ExtSettings, but search performance of Settings isn't good to begin with.

**Comment by r3g-5z** [comment] 2023-03-06 13:04
@matchboxbananasynergy The title isn't, but if you search for a keyword in the setting summary such as "A-GNSS", it's indexed. Unsure why that's the case but maybe something can be done about that. Settings search is pretty slow/inefficient and not that quite good so only so much we'll be able to do.

**Comment by muhomorr** [comment] 2023-03-06 15:30
When searching for "SUPL" or "Secure", SUPL setting does show up for me.

**Comment by muhomorr** [comment] 2023-03-06 15:43
Strange. "SUPL" and "supl" do work for me.
Also tried "secure", "user pla", "location", all work.

**Comment by r3g-5z** [comment] 2023-03-06 15:53
I think the setting is indexed fine from an implementation standpoint. People's indexes may simply be slightly outdated since this is a new option.

**Comment by muhomorr** [comment] 2023-03-06 16:37
@matchboxbananasynergy Go to Settings -> Apps -> Show system -> "Settings Suggestions" and clear its data. See if it helps.

**Comment by muhomorr** [comment] 2023-03-06 16:58
Do you use English as your device language? I'm able to reproduce this issue after changing device language to non-English.

**Comment by thestinger** [comment] 2023-03-06 17:00
Which variant of English? US?

**Comment by r3g-5z** [comment] 2023-03-06 17:03
@matchboxbananasynergy The connectivity check not showing up is a separate issue that will be resolved when moving it to ExtSettings.

The original issue did not make it clear this is likely a language problem.

**Comment by muhomorr** [comment] 2023-03-06 19:11
@matchboxbananasynergy Do you use a single device language (English (US)), or multiple?

**Closed** 2023-05-25 15:12 UTC
Labels: bug

**Comment by e-t-l** [comment] 2025-02-05 21:26
> This is actually a small bug that will be resolved when we start migrating GrapheneOS-specific settings to ExtSettings which requires a definition in the respective layout. GrapheneOS doesn't need to do anything special to get our settings indexed other than migrate old settings to ExtSettings, but search performance of Settings isn't good to begin with.

Has this "migration to ExtSettings" happened yet? It sounds like devs are aware that Settings search can be really slow (in fact I recently opened a discussion thread about it here: https://discuss.grapheneos.org/d/19736-super-slow-searching-in-settings) and I'm wondering if anything can be done to improve it.

(For reference, my system language is English (United States) and nothing else; I recently tried clearing Search Suggestions app data (as well as gave it Unrestricted background battery use) but search results are still very slow. Worth noting that I do have a work profile enabled - is search speed significantly faster if there are no secondary user profiles created?)
