### ISSUE TITLE
Bug: Pixel 7 Pro "Extra Dim" not turning off

### ISSUE THREAD

**Issue by X2K1ng** [GrapheneOS/os-issue-tracker#2262] opened 2023-06-20 17:40 UTC
Platform: Google Pixel 7 Pro
OS Version: 13 (TQ3A.230605.012.2023061402)
Issue: When "Extra Dim" is disabled, phone stays in "Extra Dim" mode.

To Replicate:

    Open Settings App
    Select Accessibility settings
    Enable "Extra Dim"
    Disable "Extra Dim"

Expectation: Phone "Extra Dim" is enabled, phone brightness decreases. Phone "Extra Dim" is disabled, phone brightness returns to normal.

Actual Result: When "Extra Dim" is enabled, phone brightness decreases. However, when disabled, "Extra Dim" stays on.

Temporary Fix: Make sure "Extra Dim" is disabled, Hold the power button and restart the device. Phone will return to normal brightness.

Please let me know if you require additional info to resolve this issue.

**Comment by matrixneo135** [comment] 2023-10-12 18:23
Duplicate of #1437

**Closed** 2023-10-16 23:33 UTC
