### ISSUE TITLE
Switching back and forth between user accounts, passphrase can't be entered until power menu -> lockdown has been pressed

### ISSUE THREAD

**Issue by barathrm** [GrapheneOS/os-issue-tracker#1264] opened 2022-06-21 06:05 UTC
I have a main account with a work profile and another user account. The main account is protected with a passphrase, no fingerprint. I had enabled and then disabled using a fingerprint for the main account a while ago, but now it's only protected with a passphrase. The second, separate, user account is protected by pin only. I have the following chain of events I can always reproduce:

- Switch to secondary user account, enter pin to log in, do stuff
- End the secondary user account's session. The device says "Switching to <main account name here>"
- Now I'm shown the screen for entering my main account's passphrase, but the virtual keyboard doesn't pop up and I can't enter the passphrase
- Go to the power menu, choose lockdown, now I can enter my passphrase and log in as usual

This happens every time.

Thanks for reading :)

**Comment by flawedworld** [comment] 2022-06-21 12:09
dupe of https://github.com/GrapheneOS/os-issue-tracker/issues/467

**Closed by flawedworld** 2022-06-21 12:09 UTC
