### ISSUE TITLE
inverted colors wont turn off

### ISSUE THREAD

**Issue by JarekLB** [GrapheneOS/os-issue-tracker#1810] opened 2022-12-11 18:46 UTC
confirmed to happen on P7 and P7P on 120700 when you turn on inverted colors by the toggle it won't turn off visually until its set to be off is setting and the phone is restarted.

**Comment by r3g-5z** [comment] 2022-12-11 18:52
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/1437

**Closed by r3g-5z** 2022-12-11 18:52 UTC
