### ISSUE TITLE
Wifi crash while disabling hotspot connection

### ISSUE THREAD

**Issue by algues111** [GrapheneOS/os-issue-tracker#4171] opened 2024-10-21 15:44 UTC
```
type: crash
osVersion: google/shiba/shiba:15/AP3A.241005.015/2024102000:user/release-keys
uid: 1010 (u:r:hal_wifi_ext:s0)
cmdline: /apex/com.google.pixel.wifi.ext/bin/hw/vendor.google.wifi_ext-service-vendor
processUptime: 0s

signal: 11 (SIGSEGV), code 9 (SEGV_MTESERR), faultAddr d00db554d88325c
threadName: binder:1070_2
MTE: enabled

backtrace:
    /apex/com.google.pixel.wifi.ext/lib64/libwifi-hal.so (SetLogHandler::cancel()+340, pc 53a54)
    /apex/com.google.pixel.wifi.ext/lib64/libwifi-hal.so (wifi_get_cancel_cmd(int, wifi_interface_info*) (.cfi)+140, pc 3180c)
    /apex/com.google.pixel.wifi.ext/bin/hw/vendor.google.wifi_ext-service-vendor (aidl::android::hardware::wifi::WifiChip::stopLoggingToDebugRingBuffer()+140, pc 460fc)
    /apex/com.google.pixel.wifi.ext/lib64/android.hardware.wifi-V2-ndk.so (aidl::android::hardware::wifi::_aidl_android_hardware_wifi_IWifiChip_onTransact(AIBinder*, unsigned int, AParcel const*, AParcel*)+4248, pc 445f8)
    /system/lib64/libbinder_ndk.so (ABBinder::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+140, pc 15b9c)
    /system/lib64/libbinder.so (android::IPCThreadState::executeCommand(int)+1220, pc 595a4)
    /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+684, pc 584cc)
    /apex/com.google.pixel.wifi.ext/bin/hw/vendor.google.wifi_ext-service-vendor (main+1556, pc 1cfc4)
    /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+120, pc 602e8)
```

**Comment by muhomorr** [comment] 2024-11-07 18:37
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/4175 , which is resolved.

**Closed by muhomorr** 2024-11-07 18:37 UTC
Labels: bug, duplicate, upstream
