### ISSUE TITLE
com.google.android.gms.ui crashed after toggling off NFC

### ISSUE THREAD

**Issue by mwglen** [GrapheneOS/os-issue-tracker#3394] opened 2024-04-01 04:32 UTC
```
type: crash
osVersion: google/panther/panther:14/AP1A.240305.019.A1/2024032100:user/release-keys
package: com.google.android.gms:240914038
process: com.google.android.gms.ui
processUptime: 17445 + 216 ms
installer: com.android.vending
GmsCompatConfig version: 100

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.nfc.action.ADAPTER_STATE_CHANGED flg=0x4000010 (has extras) } in com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver@d447d11
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1818)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$mcNAAl1SQ4MyJPyDg8TJ2x2h0Rk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at fh.aE(:com.google.android.gms@240914038@24.09.14 (190400-617895654):12)
	at fh.N(:com.google.android.gms@240914038@24.09.14 (190400-617895654):27)
	at bw.c(:com.google.android.gms@240914038@24.09.14 (190400-617895654):66)
	at bw.a(:com.google.android.gms@240914038@24.09.14 (190400-617895654):2)
	at db.jw(:com.google.android.gms@240914038@24.09.14 (190400-617895654):109)
	at db.dismiss(:com.google.android.gms@240914038@24.09.14 (190400-617895654):2)
	at dzyh.dismiss(:com.google.android.gms@240914038@24.09.14 (190400-617895654):8)
	at atpy.r(:com.google.android.gms@240914038@24.09.14 (190400-617895654):52)
	at atpy.k(:com.google.android.gms@240914038@24.09.14 (190400-617895654):86)
	at avae.b(:com.google.android.gms@240914038@24.09.14 (190400-617895654):504)
	at atpy.q(:com.google.android.gms@240914038@24.09.14 (190400-617895654):10)
	at auik.f(:com.google.android.gms@240914038@24.09.14 (190400-617895654):5)
	at atxk.b(:com.google.android.gms@240914038@24.09.14 (190400-617895654):9)
	at auyl.c(:com.google.android.gms@240914038@24.09.14 (190400-617895654):64)
	at auyl.b(:com.google.android.gms@240914038@24.09.14 (190400-617895654):105)
	at com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver.a(:com.google.android.gms@240914038@24.09.14 (190400-617895654):113)
	at com.google.android.gms.libs.punchclock.tracing.TracingBroadcastReceiver.onReceive(:com.google.android.gms@240914038@24.09.14 (190400-617895654):18)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1810)
	... 12 more
```

**Comment by muhomorr** [comment] 2024-04-01 08:25
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/3114

**Closed by muhomorr** 2024-04-01 08:25 UTC
