### ISSUE TITLE
NFC payments succeed then fail

### ISSUE THREAD

**Issue by h2dden** [GrapheneOS/os-issue-tracker#846] opened 2021-12-07 09:19 UTC
I am running the latest Graphene OS on Pixel 6
I am using a banking app that allows me making NFC payments. I go ahead and within the app I add a debit card, I am asked to make the app the default payment app and I get a push notification that the card is set up for payments. All goes as expected, payments succeed.
Until I put the profile to sleep: end the session. Once I bring up the profile again, play services still working just fine, I get push notifications through the banking app of various transactions/purchases. However, NFC payments fail. The POS displays a message like: Swipe or insert card, while the phone makes an error like sound and vibrates short.
If I remove the card from the banking app and re add it (takes about 2-3 minutes) NFC payments start working again. Until I end the session... Then upon bringing up the profile, NFC payments fail again.

I have a bug report generated by the OS, but I have check the verbose option and not sure how much private info is in there... How to share it, privately?
What other diagnostics should I perform?

**Comment by Zanthed** [comment] 2021-12-07 17:17
> I have a bug report generated by the OS, but I have check the verbose option and not sure how much private info is in there... How to share it, privately?

Send it privately to contact@grapheneos.org

**Comment by h2dden** [comment] 2021-12-17 10:02
the latest OS update on my Pixel 6 must have broken some functionality, as of now I cannot even log in the app.
The app has not been updated since I posted this ticket
If a new bug report is something of interest I can semd another one, just like the previous one
let me know

**Comment by h2dden** [comment] 2021-12-17 10:08
just to be clear on how the app misbehabes:
once I enter my username and password and deemed correct the app pop up a screen where I have to push a button to generate a 2FA code (sms)
this freezes for a few seconds and the app resets returning to the login screen, to input username and passwors again
and then loops again
again: the app has not been updated, only OS

**Comment by thestinger** [comment] 2021-12-17 13:43
OS update has nothing to do with it.

**Comment by h2dden** [comment] 2021-12-17 13:44
you should know better, but there was no other change apart from an OS update...
any thoughts?

**Comment by h2dden** [comment] 2021-12-17 13:46
I logout of the app, to try figuring out what was happening since the trick described above with removing and re adding the card was not working anymore after the OS update. Only to discover that I cannot log into the app itself...

**Comment by h2dden** [comment] 2021-12-18 00:51
I can admit when I am wrong, and I was wrong
A full device reboot solved the problem and now it  behaves as described in the begining of this ticket...
lesson learnt

**Comment by h2dden** [comment] 2021-12-19 06:53
I know that above I said I was wrong, but there is more to this issue... a reboot kind of solves the problem, until ending the secondary profile and bringing it back up causes some strange behaviour. It happened again..
 I kind of found a way around the issue: reboot, app uninstall and reinstall, etc. but it is annoying
anyway, if another bug report is deemed interesting, I am willing to provide a detailed one: just let me know

**Comment by Zanthed** [comment] 2022-02-09 12:59
Please confirm if this is still an issue.

**Comment by h2dden** [comment] 2022-02-10 08:56
what is with the rush to close this? do you have some targets to report to someone?
please open it again. it is still very much an issue
I have just tried and the issue is as described above

**Comment by h2dden** [comment] 2022-02-10 08:57
I can provide another bug report.
let me know if anyone wants it

**Comment by thestinger** [comment] 2022-02-10 09:19
@h2dden: It was closed due to lack of response to whether it was still an issue so it was assumed that it wasn't.

**Comment by thestinger** [comment] 2022-02-10 09:20
When we think issues may have been fixed, we ask if they're still an issue, and close it if it isn't.

**Comment by h2dden** [comment] 2022-02-10 09:34
@thestinger I am not a sticler and you dont owe me explanations... but the issue was closed a few seconds after the question
moving on: is anyone interested in a new bug report? are there any specific requirements on how to generate this report: this weekend I could reinstall the OS so that the bug report is very specific, etc.

**Comment by thestinger** [comment] 2022-02-19 14:18
Please check again on the latest release.

**Comment by h2dden** [comment] 2022-02-19 14:19
will do. tomorrow. now is midnight here

**Comment by h2dden** [comment] 2022-02-20 03:45
no success
I am running SQ1D.220205.004.2022021721
Added the card, performed a successful transaction.
Ended the session while card still attached to the banking app. Started again the secondary profile, opened the banking app and tried another transaction: POS says contactless error
I tried turnining off and on NFC: same result.
Once I detach the card and re-attach it, it works again...

**Comment by thestinger** [comment] 2022-03-17 05:50
We're unable to keep this open because it's not reproducible and very likely an upstream issue. It can't be worked on so this isn't actionable.

**Closed by thestinger** 2022-03-17 05:50 UTC
Labels: bug

**Comment by dadus33** [comment] 2025-03-22 11:34
@thestinger 
I have the same or very similar issue. I have my banking app installed in a secondary profile with google play services. Installing the app and adding the card all worked perfectly, and the first NFC payment was also successful. However, after changing profile to owner then at a later time switching back and trying to pay, it doesn't work anymore. I get an error message on the payment terminal saying that I should present one card or try again with a different card. The phone also doesn't vibrate, as it usually does during successful payments. Switching profiles, enabling / disabling NFC doesn't help. The only fix seems to be a full device reboot, after which I can make a payment again, but as soon as I switch profiles the problem resurfaces. What I haven't yet tested is trying to do multiple payments in a row without switching profiles after device restart. That way I'd know for sure if the issue is caused only by profile switching or just by making a payment. I will update this as soon as I get to try it.

**Comment by dadus33** [comment] 2025-03-24 12:15
Hey, as I stated in my last comment, I tried making several subsequent payments without switching away from the profile that has the banking app installed. This worked without any issues! Surprisingly, even after switching between profiles and going back to the bank app at a later time, payment was still working! However, after another device reboot the issue started happening again. I could make the first payment just fine, but when switching between profiles, subsequent payments would not work anymore (until I reboot, that is). So, honestly, I'm not sure how to reproduce it 100%, as sometimes it seems to just work without issues...

**Comment by dadus33** [comment] 2025-03-26 14:57
I managed to test this some more, and I think I fount the trigger for this issue. Switching between the owner profile (with no google play services) and the profile that I have the banking app installed on (with google play services installed) doesn't cause issues. I can do that however many times, and I will still be able to make the payment. But switching between to any other profile except the owner profile will trigger the issue. In my case, I have 2 other profiles (except the owner and the one for the banking app), both of which have play services installed. I am not sure if this is caused by the other profiles also having play services installed, or by the special status of the Owner profile, however, but I think this is a step in the right direction to being able to reproduce this issue.

**Comment by dadus33** [comment] 2025-03-28 08:56
It looks like this may have been fixed (at least for my issue) in the last stable release. I can now switch between any profiles, go back to the profile with the banking app, and make the payment without issues.
