### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by bannert1337** [GrapheneOS/os-issue-tracker#2841] opened 2023-12-13 00:51 UTC
```
type: crash
osVersion: google/lynx/lynx:14/UQ1A.231205.015/2023120800:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 61943s

abortMessage: Split motion event has mismatching downTime and eventTime for ACTION_DOWN, motionEntry=MotionEvent, splitDownTime=61946027185000

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: InputDispatcher

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 62e64)
    /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1456, pc 64be80)
    /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 38730)
    /system/lib64/liblog.so (__android_log_assert+308, pc 6fd4)
    /system/lib64/libinputflinger.so (android::inputdispatcher::InputDispatcher::splitMotionEvent(android::inputdispatcher::MotionEntry const&, std::__1::bitset<32ul>, long)+1284, pc b50d4)
    /system/lib64/libinputflinger.so (android::inputdispatcher::InputDispatcher::prepareDispatchCycleLocked(long, std::__1::shared_ptr<android::inputdispatcher::Connection> const&, std::__1::shared_ptr<android::inputdispatcher::EventEntry>, android::inputdispatcher::InputTarget const&)+1384, pc b06f8)
    /system/lib64/libinputflinger.so (android::inputdispatcher::InputDispatcher::dispatchEventLocked(long, std::__1::shared_ptr<android::inputdispatcher::EventEntry>, std::__1::vector<android::inputdispatcher::InputTarget, std::__1::allocator<android::inputdispatcher::InputTarget> > const&)+348, pc ab5bc)
    /system/lib64/libinputflinger.so (android::inputdispatcher::InputDispatcher::dispatchMotionLocked(long, std::__1::shared_ptr<android::inputdispatcher::MotionEntry>, android::inputdispatcher::InputDispatcher::DropReason*, long*)+1028, pc a87b4)
    /system/lib64/libinputflinger.so (android::inputdispatcher::InputDispatcher::dispatchOnceInnerLocked(long*)+1620, pc a55e4)
    /system/lib64/libinputflinger.so (android::inputdispatcher::InputDispatcher::dispatchOnce()+84, pc a4ee4)
    /system/lib64/libinputflinger_base.so (android::(anonymous namespace)::InputThreadImpl::threadLoop()+24, pc aff8)
    /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+284, pc 1430c)
    /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+140, pc e719c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cf9ec)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64730)
```

>

**Comment by OscarArmend** [comment] 2023-12-13 12:55
I too had a random crash, but it has been happening very frequently since the last update. I've seen this random crash and auto reboot at least once per day.
I've also seen the authentication keeps failing.

```
type: crash
osVersion: google/oriole/oriole:14/UQ1A.231205.015/2023120800:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 28428s

abortMessage: Could not create epoll instance: Too many open files

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: Filter

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 62e64)
    /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1456, pc 64be80)
    /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 38730)
    /system/lib64/liblog.so (__android_log_assert+308, pc 6fd4)
    /system/lib64/libutils.so (android::Looper::rebuildEpollLocked()+408, pc 18228)
    /system/lib64/libutils.so (android::Looper::Looper(bool)+256, pc 18040)
    /system/lib64/libandroid_runtime.so (android::NativeMessageQueue::NativeMessageQueue()+160, pc 180530)
    /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativeInit(_JNIEnv*, _jclass*)+28, pc 18193c)
    /system/framework/arm64/boot-framework.oat (art_jni_trampoline+112, pc 1e9420)
    /system/framework/arm64/boot-framework.oat (android.os.HandlerThread.run+280, pc 55c678)
    /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612, pc 2109a4)
    /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+172, pc 253b3c)
    /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1416, pc 69abc8)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cf9ec)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64730)
```

**Comment by thestinger** [comment] 2023-12-13 12:56
@OscarArmend That's a different issue likely caused by the apps you have installed and should be resolved by the latest release, currently in the Beta channel. See https://github.com/GrapheneOS/os-issue-tracker/issues/2787.

**Comment by thestinger** [comment] 2023-12-14 12:35
Please update to the latest release and see if it happens again.

**Closed by thestinger** 2023-12-14 12:35 UTC
Labels: bug, upstream
