### ISSUE TITLE
system_server crash

### ISSUE THREAD

**Issue by cjvanzwol** [GrapheneOS/os-issue-tracker#2827] opened 2023-12-11 21:44 UTC
```
type: crash
Process: system_server
Build: google/bluejay/bluejay:14/UQ1A.231205.015/2023120800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Failed to initialize display event receiver.  status=-2147483646
	at android.view.DisplayEventReceiver.nativeInit(Native Method)
	at android.view.DisplayEventReceiver.<init>(DisplayEventReceiver.java:130)
	at android.view.Choreographer$FrameDisplayEventReceiver.<init>(Choreographer.java:1277)
	at android.view.Choreographer.<init>(Choreographer.java:281)
	at android.view.Choreographer.<init>(Choreographer.java:274)
	at android.view.Choreographer.<init>(Unknown Source:0)
	at android.view.Choreographer$1.initialValue(Choreographer.java:116)
	at android.view.Choreographer$1.initialValue(Choreographer.java:109)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at android.view.Choreographer.getInstance(Choreographer.java:309)
	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1171)
	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1132)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:397)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:150)
	at android.app.Dialog.show(Dialog.java:352)
	at com.android.server.am.ErrorDialogController$$ExternalSyntheticLambda3.accept(R8$$SyntheticClass:0)
	at com.android.server.am.ErrorDialogController.forAllDialogs(ErrorDialogController.java:164)
	at com.android.server.am.ErrorDialogController.lambda$showCrashDialogs$1(ErrorDialogController.java:182)
	at com.android.server.am.ErrorDialogController.$r8$lambda$RbiusjkAePXWGrMazzX5fIVcwYY(ErrorDialogController.java:0)
	at com.android.server.am.ErrorDialogController$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
	at com.android.server.UiThread.run(UiThread.java:45)

```

**Comment by cjvanzwol** [comment] 2023-12-11 21:44
I was just using Trakt.tv app and phone rebooted.

**Comment by cjvanzwol** [comment] 2023-12-12 14:24
And again today. I was editting email through the notifications. 

I also noticed significant battery drain. 

```
type: crash
osVersion: google/bluejay/bluejay:14/UQ1A.231205.015/2023120800:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 16964s

abortMessage: Too many open files, could not duplicate input channel ClientState{50f9e09 mUid=10104 mPid=29277 mSelfReportedDisplayId=0} (server)

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: binder:28583_C

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 62e64)
    /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1456, pc 64be80)
    /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 38730)
    /system/lib64/liblog.so (__android_log_assert+308, pc 6fd4)
    /system/lib64/libinput.so (android::InputChannel::dupFd() const+532, pc b5314)
    /system/lib64/libinput.so (android::InputChannel::dup() const+52, pc b4f44)
    /system/lib64/libandroid_runtime.so (android::android_view_InputChannel_nativeDup(_JNIEnv*, _jobject*, long)+80, pc 149530)
    /system/framework/arm64/boot-framework.oat (art_jni_trampoline+116, pc 1e9094)
    /system/framework/oat/arm64/services.odex (com.android.server.inputmethod.InputMethodManagerService.attachNewInputLocked+2624, pc 2eabd0)
    /system/framework/oat/arm64/services.odex (com.android.server.inputmethod.InputMethodManagerService.startInputUncheckedLocked+2716, pc 2eefec)
    /system/framework/oat/arm64/services.odex (com.android.server.inputmethod.InputMethodManagerService.startInputOrWindowGainedFocusInternalLocked+2364, pc 2ee2cc)
    /system/framework/oat/arm64/services.odex (com.android.server.inputmethod.InputMethodManagerService.startInputOrWindowGainedFocus+1268, pc 2ed564)
    /apex/com.android.art/lib64/libart.so (nterp_helper+5848, pc 20aa58)
    /system/framework/framework.jar (com.android.internal.view.IInputMethodManager$Stub.onTransact+1336, pc 4e7ec)
    /apex/com.android.art/lib64/libart.so (nterp_helper+3924, pc 20a2d4)
    /system/framework/services.jar (com.android.server.inputmethod.InputMethodManagerService.onTransact+0, pc 5c9c14)
    /system/framework/arm64/boot-framework.oat (android.os.Binder.execTransactInternal+752, pc 6247a0)
    /system/framework/arm64/boot-framework.oat (android.os.Binder.execTransact+564, pc 624304)
    /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612, pc 2109a4)
    /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+172, pc 253b3c)
    /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+460, pc 64417c)
    /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92, pc 64440c)
    /apex/com.android.art/lib64/libart.so (art::JNI<false>::CallBooleanMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+660, pc 47aa84)
    /system/lib64/libandroid_runtime.so (_JNIEnv::CallBooleanMethod(_jobject*, _jmethodID*, ...)+120, pc deae8)
    /system/lib64/libandroid_runtime.so (JavaBBinder::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+164, pc 195d24)
    /system/lib64/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+304, pc 74b00)
    /system/lib64/libbinder.so (android::IPCThreadState::executeCommand(int)+1016, pc 5ed78)
    /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+160, pc 5e8c0)
    /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+112, pc 5f210)
    /system/lib64/libbinder.so (android::PoolThread::threadLoop()+24, pc 69078)
    /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+284, pc 1430c)
    /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+140, pc e719c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cf9ec)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64730)
```

**Comment by thestinger** [comment] 2023-12-12 15:38
@krple That's a much different upstream Android bug than the other upstream bugs.

**Comment by GrapheneEnjoyer** [comment] 2023-12-12 16:48
Heres Mine, Anything i should be concerned about?


type: crash
Process: system_server
Build: google/cheetah/cheetah:14/UQ1A.231205.015/2023120800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

android.view.Surface$OutOfResourcesException: DEAD_OBJECT
	at android.view.SurfaceControl.nativeCreate(Native Method)
	at android.view.SurfaceControl.<init>(SurfaceControl.java:1237)
	at android.view.SurfaceControl.<init>(Unknown Source:0)
	at android.view.SurfaceControl$Builder.build(SurfaceControl.java:910)
	at com.android.server.wm.WindowContainer.setInitialSurfaceControlProperties(WindowContainer.java:682)
	at com.android.server.wm.WindowContainer.createSurfaceControl(WindowContainer.java:678)
	at com.android.server.wm.WindowToken.createSurfaceControl(WindowToken.java:337)
	at com.android.server.wm.WindowContainer.onParentChanged(WindowContainer.java:664)
	at com.android.server.wm.WindowContainer.setParent(WindowContainer.java:646)
	at com.android.server.wm.WindowContainer.addChild(WindowContainer.java:777)
	at com.android.server.wm.DisplayArea$Tokens.addChild(DisplayArea.java:729)
	at com.android.server.wm.DisplayContent.addWindowToken(DisplayContent.java:1434)
	at com.android.server.wm.WindowToken.<init>(WindowToken.java:240)
	at com.android.server.wm.WallpaperWindowToken.<init>(WallpaperWindowToken.java:53)
	at com.android.server.wm.WindowManagerService.addWindowToken(WindowManagerService.java:2722)
	at com.android.server.wm.WindowManagerService$LocalService.addWindowToken(WindowManagerService.java:7856)
	at com.android.server.wallpaper.WallpaperManagerService$DisplayConnector.connectLocked(WallpaperManagerService.java:937)
	at com.android.server.wallpaper.WallpaperManagerService.lambda$attachServiceLocked$21(WallpaperManagerService.java:3735)
	at com.android.server.wallpaper.WallpaperManagerService.$r8$lambda$uZi5_bwd07bsmBx9bUAW0RE40MU(WallpaperManagerService.java:0)
	at com.android.server.wallpaper.WallpaperManagerService$$ExternalSyntheticLambda23.accept(R8$$SyntheticClass:0)
	at com.android.server.wallpaper.WallpaperManagerService$WallpaperConnection.forEachDisplayConnector(WallpaperManagerService.java:1052)
	at com.android.server.wallpaper.WallpaperManagerService.attachServiceLocked(WallpaperManagerService.java:3735)
	at com.android.server.wallpaper.WallpaperManagerService.-$$Nest$mattachServiceLocked(WallpaperManagerService.java:0)
	at com.android.server.wallpaper.WallpaperManagerService$WallpaperConnection.onServiceConnected(WallpaperManagerService.java:1094)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2198)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2231)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at com.android.server.SystemServer.run(SystemServer.java:972)
	at com.android.server.SystemServer.main(SystemServer.java:666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by NaiveInvestigator** [comment] 2023-12-12 17:03
i was using the browser and it randomly crashed too.
```
type: crash
osVersion: google/panther/panther:14/UQ1A.231205.015/2023120800:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 22614s

abortMessage: Too many open files, could not duplicate input channel ClientState{ccbe1b8 mUid=10154 mPid=9050 mSelfReportedDisplayId=0} (server)

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: binder:20444_4

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 62e64)
    /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1456, pc 64be80)
    /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 38730)
    /system/lib64/liblog.so (__android_log_assert+308, pc 6fd4)
    /system/lib64/libinput.so (android::InputChannel::dupFd() const+532, pc b5314)
    /system/lib64/libinput.so (android::InputChannel::dup() const+52, pc b4f44)
    /system/lib64/libandroid_runtime.so (android::android_view_InputChannel_nativeDup(_JNIEnv*, _jobject*, long)+80, pc 149530)
    /system/framework/arm64/boot-framework.oat (art_jni_trampoline+116, pc 1e9094)
    /system/framework/oat/arm64/services.odex (com.android.server.inputmethod.InputMethodManagerService.attachNewInputLocked+2624, pc 2eabd0)
    /system/framework/oat/arm64/services.odex (com.android.server.inputmethod.InputMethodManagerService.startInputUncheckedLocked+2716, pc 2eefec)
    /system/framework/oat/arm64/services.odex (com.android.server.inputmethod.InputMethodManagerService.startInputOrWindowGainedFocusInternalLocked+2364, pc 2ee2cc)
    /system/framework/oat/arm64/services.odex (com.android.server.inputmethod.InputMethodManagerService.startInputOrWindowGainedFocus+1268, pc 2ed564)
    /apex/com.android.art/lib64/libart.so (nterp_helper+5848, pc 20aa58)
    /system/framework/framework.jar (com.android.internal.view.IInputMethodManager$Stub.onTransact+1336, pc 4e7ec)
    /apex/com.android.art/lib64/libart.so (nterp_helper+3924, pc 20a2d4)
    /system/framework/services.jar (com.android.server.inputmethod.InputMethodManagerService.onTransact+0, pc 5c9c14)
    /system/framework/arm64/boot-framework.oat (android.os.Binder.execTransactInternal+752, pc 6247a0)
    /system/framework/arm64/boot-framework.oat (android.os.Binder.execTransact+564, pc 624304)
    /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612, pc 2109a4)
    /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+172, pc 253b3c)
    /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+460, pc 64417c)
    /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92, pc 64440c)
    /apex/com.android.art/lib64/libart.so (art::JNI<false>::CallBooleanMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+660, pc 47aa84)
    /system/lib64/libandroid_runtime.so (_JNIEnv::CallBooleanMethod(_jobject*, _jmethodID*, ...)+120, pc deae8)
    /system/lib64/libandroid_runtime.so (JavaBBinder::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+164, pc 195d24)
    /system/lib64/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+304, pc 74b00)
    /system/lib64/libbinder.so (android::IPCThreadState::executeCommand(int)+1016, pc 5ed78)
    /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+160, pc 5e8c0)
    /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+112, pc 5f210)
    /system/lib64/libbinder.so (android::PoolThread::threadLoop()+24, pc 69078)
    /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+284, pc 1430c)
    /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+140, pc e719c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cf9ec)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64730)
```

**Comment by krple** [comment] 2023-12-12 17:05
One interesting thing I did notice is before this crash I didn't get notifications until very late in the day or after a restart. After the crash I'm now getting notifications normally.

**Comment by thestinger** [comment] 2023-12-12 17:05
Closing as duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2787.

**Closed by thestinger** 2023-12-12 17:05 UTC

**Comment by thestinger** [comment] 2023-12-13 01:36
https://grapheneos.org/releases#2023121200 raises the file descriptor limit and should resolve this Android 14 QPR1 issue unless it's caused by a file descriptor leak rather than higher file descriptor usage.
