### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by David-Prock** [GrapheneOS/os-issue-tracker#3323] opened 2024-03-12 06:49 UTC
```
type: crash
osVersion: google/husky/husky:14/AP1A.240305.019.A1/2024030900:user/release-keys
package: com.google.android.gms:240513038
process: com.google.android.gms.ui
processUptime: 79744 + 451 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 98

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.nfc.action.ADAPTER_STATE_CHANGED flg=0x4000010 (has extras) } in com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver@dc40beb
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1818)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$mcNAAl1SQ4MyJPyDg8TJ2x2h0Rk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at fd.aE(:com.google.android.gms@240513038@24.05.13 (190400-602827846):12)
	at fd.N(:com.google.android.gms@240513038@24.05.13 (190400-602827846):27)
	at bs.c(:com.google.android.gms@240513038@24.05.13 (190400-602827846):66)
	at bs.a(:com.google.android.gms@240513038@24.05.13 (190400-602827846):2)
	at cx.hH(:com.google.android.gms@240513038@24.05.13 (190400-602827846):109)
	at cx.dismiss(:com.google.android.gms@240513038@24.05.13 (190400-602827846):2)
	at dxst.dismiss(:com.google.android.gms@240513038@24.05.13 (190400-602827846):8)
	at asnb.s(:com.google.android.gms@240513038@24.05.13 (190400-602827846):52)
	at asnb.k(:com.google.android.gms@240513038@24.05.13 (190400-602827846):88)
	at atxr.b(:com.google.android.gms@240513038@24.05.13 (190400-602827846):504)
	at asnb.q(:com.google.android.gms@240513038@24.05.13 (190400-602827846):10)
	at atfn.f(:com.google.android.gms@240513038@24.05.13 (190400-602827846):5)
	at asun.b(:com.google.android.gms@240513038@24.05.13 (190400-602827846):9)
	at atvy.c(:com.google.android.gms@240513038@24.05.13 (190400-602827846):64)
	at atvy.b(:com.google.android.gms@240513038@24.05.13 (190400-602827846):116)
	at com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver.a(:com.google.android.gms@240513038@24.05.13 (190400-602827846):113)
	at com.google.android.gms.libs.punchclock.tracing.TracingBroadcastReceiver.onReceive(:com.google.android.gms@240513038@24.05.13 (190400-602827846):18)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1810)
	... 12 more
```

**Comment by muhomorr** [comment] 2024-03-15 07:15
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/3114

**Closed** 2024-03-15 07:16 UTC
