### ISSUE TITLE
fingerprint service crash

### ISSUE THREAD

**Issue by MichaelDevon** [GrapheneOS/os-issue-tracker#2968] opened 2023-12-29 16:23 UTC
SYSTEM SERVER

```
type: crash
Process: system_server
Build: google/shiba/shiba:14/UQ1A.231205.015/2023121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.biometrics.BiometricService$EnabledOnKeyguardCallback.notify(boolean, int)' on a null object reference
	at com.android.server.biometrics.BiometricService$SettingObserver.notifyEnabledOnKeyguardCallbacks(BiometricService.java:390)
	at com.android.server.biometrics.BiometricService$3.onUserSwitchComplete(BiometricService.java:1060)
	at com.android.server.am.UserController.dispatchUserSwitchComplete(UserController.java:2009)
	at com.android.server.am.UserController.handleMessage(UserController.java:3172)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)

```

android.hardware.biometrics.fingerprint-service.goodix

```
type: crash
osVersion: google/shiba/shiba:14/UQ1A.231205.015/2023121200:user/release-keys
uid: 1000 (u:r:hal_fingerprint_default:s0)
cmdline: /vendor/bin/hw/android.hardware.biometrics.fingerprint-service.goodix
processUptime: 13248s

signal: 11 (SIGSEGV), code 1 (SEGV_MAPERR), faultAddr 0
cause: null pointer dereference
threadName: android.hardwar
MTE: not enabled

backtrace:
    /vendor/lib64/libgf_hal.so (goodix::GoodixFingerprintEngine::enumerateEnrollments()+380, pc 39a5c)
    /vendor/bin/hw/android.hardware.biometrics.fingerprint-service.goodix (aidl::android::hardware::biometrics::fingerprint::WorkerThread::threadFunc()+356, pc ce04)
    /vendor/bin/hw/android.hardware.biometrics.fingerprint-service.goodix (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (aidl::android::hardware::biometrics::fingerprint::WorkerThread::*)(), aidl::android::hardware::biometrics::fingerprint::WorkerThread*> >(void*)+60, pc d18c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cffec)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64d30)
```

**Comment by MichaelDevon** [comment] 2023-12-29 16:24
This caused my phone to soft reboot after a profile switch.

**Comment by muhomorr** [comment] 2023-12-31 08:16
This system_server crash should be fixed in 2023123000 release. 

Under what circumstances did the `android.hardware.biometrics.fingerprint-service.goodix` crash happen?

**Comment by MichaelDevon** [comment] 2023-12-31 11:07
i ended another profile session, so it switched back to owners but nothing else special

**Comment by thestinger** [comment] 2023-12-31 16:55
It might be caused by the system_server crash. I think it's best to close it and see if it ever happens again.

**Closed by thestinger** 2023-12-31 16:55 UTC
