### ISSUE TITLE
Spell checker shows empty suggestions

### ISSUE THREAD

**Issue by shibattor** [GrapheneOS/os-issue-tracker#865] opened 2021-12-13 20:11 UTC
Spell checker shows empty suggestions, tested with the default keyboard and Florisboard in English and Czech languages on the latest (2021121012) GrapheneOS.
 
**StR**
1. write something in English with a typo
2. press space
3. click on the highlighted word

Actual result:
![2021-12-13-202851](https://user-images.githubusercontent.com/87258997/145881337-f1bb2888-b628-4861-9463-5ceba45684a4.jpeg)

**Comment by jorgeluiscarrillo** [comment] 2021-12-13 20:50
It's working fine for me using FlorisBoard (English/US). Under Settings > System > Languages & input > Spell checker, Languages is set to Use system languages and Default spell checker is set to GrapheneOS Spell Checker.

**Comment by shibattor** [comment] 2021-12-14 05:59
You are right, it is working when the GrapheneOS Spell Checker is used. I switched it to FlorisBoard one so in hopes that I could have functional spell checker for Czech language and forgot about it, sorry.
I do not know whether this is a GrapheneOS or a Florisboard one, I have tried multiple keyboards, but I haven't found another one with an option in the Spell Checker option in the Android settings.

**Comment by jorgeluiscarrillo** [comment] 2021-12-14 07:03
I don't think there is a Czech dictionary in AOSP so the GrapheneOS spell checker won't work. Recent versions of FlorisBoard (v0.3.13-beta05 or newer) support adding spell checking dictionaries as described [here](https://github.com/florisboard/florisboard/wiki/System-spell-checker-service). Here is a [Czech dictionary](https://addons.mozilla.org/en-US/firefox/addon/czech-spell-checking-dictionar/) from Mozilla. Open that link in Vanadium and download the file which can be imported into FlorisBoard.

Anyways, this issue should probably be closed as the GrapheneOS spell checker works with the supported languages.

**Comment by shibattor** [comment] 2021-12-14 10:03
I am using the latest Florisboard version with the dictionary downloaded and set-up. The mistyped word is highlighted, therefore it is clearly working, but the correction/suggestion window shows no entries, therefore I am not sure whether this is a GrapheneOS issue or a Florisboard issue.

**Comment by shibattor** [comment] 2021-12-14 19:39
Here are findings of the Florisboard's maintainer (patrickgold)

> Just to make sure I tested out the Czech subtype / Czech Mozilla Firefox spell checker dictionary and it works on an Android 11 device (with GMS) without issues, so a general issue in the internal dictionary matcher of FlorisBoard is not present.

https://matrix.to/#/!LcLoPwndyZCssfevip:matrix.org/$NNdvUvVRmathp9hRXoF7qCifrLkdqOc0OpPCrSZd-LI?via=matrix.org&via=tchncs.de&via=kde.org

> Hmm yeah I heavily suspect that there's an issue with AOSP (not GrapheneOS) which many proprietary ROMs seem to patch out though. I may have to dig into the source code of other FOSS spell checkers if I miss something or if there's some workaround to a bug I am not aware of, but at the moment I can't promise any fix sadly.

https://matrix.to/#/!LcLoPwndyZCssfevip:matrix.org/$e0qx8nzL3cfbnH4jnozrCif-kaJwmmRjRllhcKihoHk?via=matrix.org&via=tchncs.de&via=kde.org

**Comment by patrickgold** [comment] 2021-12-14 19:58
Adding additional info as FlorisBoard's maintainer: The spell checker implementation of Android is buggy across many different ROMs, so I suspect that this particular issue is upstream in AOSP and not within GrapheneOS directly.

As I want to ensure though that my keyboard's spell checker service is not the issue here, I will add a specific debug overlay which draws the current processed words in the free space above the app, so we can check if the empty box is because I pass empty strings (what I don't think because I literally filter blank strings before passing the suggested corrections) or because the system incorrectly displays them as empty. If it is the former I have something to fix, if it is the latter we might consider filing a bug report on the AOSP bug tracker and closing this issue.

**Comment by thestinger** [comment] 2021-12-14 20:13
We're very interested in fixing the issue if the problem is identified. If there's a patch available somewhere it would be good to know.

**Comment by patrickgold** [comment] 2021-12-15 23:43
I have just implemented a spell checker overlay for FlorisBoard, to check if it is actually the issue. I do not have any results from any of my original reporters of the empty box problem yet, but have done extensive testing on my phone (_OnePlus 7T with Oxygen OS (Android 11), GMS installed_ and _Emulated Google Pixel 3a with Android 10, GMS installed_), where I found a really interesting bug.

Whenever starting a new spell checker session, it seems like that for this session the first incorrect word the user taps on is taken as a baseline for all subsequent taps in terms of window measurement and the correction UI window's height will not adapt anymore after that (until the session is destroyed and reinstated).

For example we type the following words and FlorisBoard suggests these words:

Typed word | No. of suggested corrections | Suggested Corrections
-|-|-
glorius | 3 | glorious, glories, gregorius
handschake | 2 | handshake, handbrake
sreeem | 1 | redeem

If the user first clicks on "glorius", a UI will be shown with a height exactly matching 3 words and the add/delete buttons. Then the user clicks on "handschake". Expected outcome: the window reduces its height so only 2 rows + buttons have space. Actual outcome: The window is still 3 rows + buttons high, thus for the user it seems like I provided one empty string (which I did not confirmed by the debug overlay I just added).
Then click on "sreeem". Same thing again, only that this time there are 2 empty rows.

Now we play the same thing but reversed (after closing and reopening the screen the edit text was on to reset the spell check session):  
First we click on "sreeem". A window with 1 row + button's height is shown, everything is fine. Next we click on "handschake". Expected: we have a window with 2 rows and buttons. Actual outcome: The window is only 1 row + buttons high, and I have to scroll (!) the suggestions now, even though there's plenty of room on the screen. Same thing for the "glorius" word.

To further test out this I wanted to see how both OpenBoard's and Gboard's spell checker service handle this. I can't reproduce this bug with either of them, because they always provide the same number of suggestions (3 for me), no matter how stupid the input word is, just to make sure there are no empty rows. Afaik OpenBoard's spell checker is based on the AOSP spell checker service, in which case I would immediately see the reason why this bug no one noticed: As the suggestion count is static in AOSP, it is more than enough to set the window height once for the firts window appearance and forget about it. FlorisBoard however only provides suggestions if it can actually provide one, so the returned number of corrections is somewhere between 0 and the set suggestion limit by the spell checker requester. This means that the height of the input window should also be updated for each word (based on the number of provided suggestions).

At this moment I do not know how exactly my discovered bug correlates with OP's issue (considering the fact that not even a single Czech word gets suggested) and if this bug is also reproducible in GrapheneOS or other ROMs. I already contacted OP in the Matrix group of FlorisBoard to ask if he/she could try out the current debug build with the spell checker debug overlay, to hopefully clarify the situation with the Czech spell checker.

I hope I described this bug so it is understandable what I mean, else I can try screen recording the issue and posting it here too. It would be great if others could also test my theory (with any spell checker service that does NOT suggest a static number of words), because I only have 2 other devices where I can test this out, which is a pretty low sample size.

**Comment by patrickgold** [comment] 2021-12-16 17:46
Status update:

The original issue reported by @shibattor is indeed caused by FlorisBoard, as seen on below screenshot (taken by the reporter and shared in the FlorisBoard Matrix channel):

![image](https://user-images.githubusercontent.com/19412843/146419864-a416aafe-e41d-4e67-87e6-f54218ea4587.png)

As Kotlin does not filter out the string as blank (even though it is blank when you print it), it appears to me that this is an encoding issue within FlorisBoard, where at some point the character codes get mutated and are just garbage (but not known blank characters, so not filtered).

Still there's the bug with the input window height which I described above, which is not connected to the encoding issue at all. This has nothing to do with GrapheneOS though and is an upstream bug, so I suggest closing this issue. I will probably file a bug report after testing out if I can reproduce this bug in Android 12, if so I will share the link to the issue created here.

**Closed** 2021-12-16 17:48 UTC
Labels: bug, upstream

**Comment by shibattor** [comment] 2021-12-16 17:50
Here is the related issue on the FlorisBoard side https://github.com/florisboard/florisboard/issues/1452.
