### ISSUE TITLE
Sandboxed Google Play crashes in secondary users when granted Location permission due to upstream Android 14 regression breaking some APIs in secondary users

### ISSUE THREAD

**Issue by somehuman60** [GrapheneOS/os-issue-tracker#2517] opened 2023-10-12 13:39 UTC
And almost all apps from Google Play crash too.

```
type: crash
osVersion: google/cheetah/cheetah:14/UP1A.231005.007/2023101100:user/release-keys
package: com.google.android.gms:233514044
process: com.google.android.gms.persistent
processUptime: 26229 + 373 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 77

java.lang.NullPointerException: packageName can't be null
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3072)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.requestCellInfoUpdate(ITelephony.java:9641)
	at android.telephony.TelephonyManager.requestCellInfoUpdate(TelephonyManager.java:6807)
	at android.telephony.TelephonyManager.requestCellInfoUpdate(TelephonyManager.java:6869)
	at dkjq.handleMessage(:com.google.android.gms@233514044@23.35.14 (190400-561707045):596)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at bbxa.lJ(:com.google.android.gms@233514044@23.35.14 (190400-561707045):1)
	at bbxa.dispatchMessage(:com.google.android.gms@233514044@23.35.14 (190400-561707045):143)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	Suppressed: dpws: 
		at tk_trace.location_base-GoogleLocationChimeraService_onCreate(Unknown Source:0)

```

**Comment by thestinger** [comment] 2023-10-12 14:02
@somehuman60 Revoking Location permission from Play services should work around it. Turn location re-routing back on if you disabled it. We'll look into working around this issue to avoid issues with their network location service for users who want to use it.

**Comment by somehuman60** [comment] 2023-10-12 14:24
> @somehuman60 Revoking Location permission from Play services should work around it. Turn location re-routing back on if you disabled it. We'll look into working around this issue to avoid issues with their network location service for users who want to use it.

Thank you. This works now.

**Comment by thestinger** [comment] 2023-10-12 14:49
This appears to be an Android bug with user profiles and GrapheneOS users are just more heavily using user profiles.

**Comment by qoijjj** [comment] 2023-10-12 16:20
> @somehuman60 Revoking Location permission from Play services should work around it. Turn location re-routing back on if you disabled it. We'll look into working around this issue to avoid issues with their network location service for users who want to use it.

You mean to tell me I didn't need to give Google Play Services my location this entire time? 😄

This fixed it for me as well and I don't think I'll be disabling it even after the issue is fixed. Not sure why I ever disabled it. GrapheneOS just keeps getting better.

**Comment by thestinger** [comment] 2023-10-12 16:28
No need to give Location permission to Play services for most users. Many apps request location from Play services via the Play geolocation API but on GrapheneOS they get rerouted to the OS location service by the sandboxed Google Play compatibility layer. We do this so that location works in apps by default via GNSS (satellite location). We emulate the presence of network-based location so that apps only querying network-based receive it from GNSS if possible.

It's possible to use the Google Play network location service on GrapheneOS for apps which use Play geolocation, but it's entirely optional and requires multiple steps to enable it (https://grapheneos.org/usage#sandboxed-google-play-configuration): granting Location permission, disabling location re-routing and enabling their network location opt-in toggle since they don't use it by default without user consent. This is currently broken **on secondary users** because of an upstream Android 14 bug which breaks using one of the Location-related APIs used by Play services in secondary users. It would also break for other apps using it.

**Comment by idk-r-n** [comment] 2023-10-13 05:06
In some cases, viewing the crash log and retrying can "fix" this issue. Not sure if that helps with troubleshooting.

**Comment by idk-r-n** [comment] 2023-10-13 18:07
@thestinger I can try that next. Since my "brute force" method worked, I didn't bother looking for other solutions at that time.

**Comment by thestinger** [comment] 2023-10-13 21:29
Will be fixed by today's release.

**Closed by thestinger** 2023-10-13 21:29 UTC
Labels: bug, upstream, priority-max

**Comment by idk-r-n** [comment] 2023-10-14 00:11
> @idk-r-n Were you able to work around it by disabling the Location permission already?

Well this did work.
