### ISSUE TITLE
OS reboots to Recovery screen when SIM passcode is enabled 

### ISSUE THREAD

**Issue by TX9G9qBxid** [GrapheneOS/os-issue-tracker#1968] opened 2023-02-17 08:13 UTC
During boot, once reaching the SIM unlock screen, GrapheneOS restarts to the Recovery Screen, when attempting to enter SIM passcode.

Process:
1. Turn on phone
2. Await SIM unlock screen.
3. Attempt to enter passcode.
4. After 1-2 characters are entered the phone Reboots to Recovery Screen.
5. Selecting "Try Again" results in a repeat of above process. 

The issue persists over multiple SIMs (ruling out one faulty SIM).
The issue disappears when SIM passcode is disabled. And reappears when passcode is enabled again.

Device: Pixel 6a
Release channel: Stable (latest installed)
Issue first accurance: FEB 17th

**Comment by hrrd** [comment] 2023-02-17 13:35
something similar to this happened to me in this morning. my phone reboots every two hours while sleeping. today after i closed the alarm i tried to enter the pin and then it got stuck after i pressed the first 2 pin numbers and then the phone froze and reboots. It is impossible that this was between the 2 hours time frame because 30 min before the last alarm i pressed snoozes. so something different triggered the reboot. but maybe the phone does not count the alarm closing as un action to stop the 2 hours reboot time. dont know.

**Comment by thestinger** [comment] 2023-02-17 14:41
@hrrd That's fully intended. Auto-reboot only counts unlocking as restarting the timer. It's not related to this issue and is part of the design of the feature. It would be insecure if you could delay it without unlocking.

**Comment by hrrd** [comment] 2023-02-17 15:26
oh okay. good to know. thanks.

**Comment by thestinger** [comment] 2023-02-26 04:09
Unable to replicate.

**Comment by r3g-5z** [comment] 2023-04-15 00:46
Is this still an issue / reproducible?

**Comment by TX9G9qBxid** [comment] 2023-04-22 19:35
> Is this still an issue / reproducible?

Yes, consistently reproducible. 
A minor tweaks to the process: 
- Phone reboots regardless of any attempt to enter SIM passcode. After 2-3 reboots, phone defaults to Recovery Screen. 

Issue still avoidable by disabling SIM passcode.

**Comment by akc3n** [comment] 2023-06-25 09:20
Another reference to this issue may be found on our discussion forum, which just got posted today by a user reporting the same issue: https://discuss.grapheneos.org/d/5777-bootloop-after-two-latest-updates-p6

**Comment by thestinger** [comment] 2023-08-03 16:47
@TX9G9qBxid Are you still having this issue?

**Comment by hodhado** [comment] 2023-09-07 14:38
having similar issue

release: 2023090600

after lastest update grapheneos automatically powers itself off after asking for sim pin then boots again in recovery mode with options to try again or factory reset

after more tinkering it seems that if sim pin is typed almost immediately phone will proceed to showing the lockscreen and boot normally from there on. if there is a short delay of about 4 seconds and more before entering sim pin phone will reboot in recovery mode even after successfully proceeding to lock screen. also, phone will reboot to recovery mode if presented with pin screen and no pin entered.

thank you for your time and effort looking into this

**Comment by muhomorr** [comment] 2023-09-07 18:03
Unable to reproduce this on my Pixel 6a.

**Comment by hodhado** [comment] 2023-09-07 19:53
fixed when followed steps suggested here: https://discuss.grapheneos.org/d/5592-grapheneos-version-2023061400-released/30

"Upon changing various settings, I came across the element that for me seems to have been causing the issue -- ImsService.

The SIM lock boot-loop problem begins if you make changes to the locations permissions of ImsService, with either:

    you disable "precise location" for its location permission
    you disallow the location permission for ImsService completely

In either of those scenarios, I am able to replicate the problem. And then re-enabling ImsService's location permissions, the problem goes away completely."

**Comment by thestinger** [comment] 2023-09-07 20:13
This is caused by making broken configuration changes.

**Closed by thestinger** 2023-09-07 20:13 UTC
Labels: bug, upstream, status-unconfirmed
