### ISSUE TITLE
Before creating a work profile, ask the user if they want to auto install sandboxed GMS inside the work profile

### ISSUE THREAD

**Issue by randomhydrosol** [GrapheneOS/os-issue-tracker#1836] opened 2022-12-19 07:16 UTC
This helps with getting a device administrator app that depends on GMS or a GMS app like device policy working properly. Currently, GMS is not present when an app creates a work profile and the enrollment would fail

Asking the user if they would like to install GMS in the new profile before returning control to the work profile app should solve the issue

**Comment by r3g-5z** [comment] 2022-12-22 18:53
Dupe of https://github.com/GrapheneOS/os-issue-tracker/issues/1821

**Closed by r3g-5z** 2022-12-22 18:53 UTC
