### ISSUE TITLE
Sandboxed Play Store crashing repeatedly

### ISSUE THREAD

**Issue by moonshot64** [GrapheneOS/os-issue-tracker#2681] opened 2023-11-12 14:11 UTC
Here's what it gave me to report:

```
type: crash
osVersion: google/cheetah/cheetah:14/UP1A.231105.003/2023110700:user/release-keys
package: com.google.android.gms:234414038
process: com.google.android.gms.persistent
processUptime: 5735629 + 391 ms
installer: com.android.vending
GmsCompatConfig version: 83

java.lang.RuntimeException: Rethrown by StandaloneSchedulingEngine
	at cnen.a(:com.google.android.gms@234414038@23.44.14 (190400-580326705):455)
	at cnbn.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):9)
	at ajls.c(:com.google.android.gms@234414038@23.44.14 (190400-580326705):50)
	at ajls.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ajqx.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvmi: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.RuntimeException: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u15a138; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at bfxo.apply(:com.google.android.gms@234414038@23.44.14 (190400-580326705):5)
	at ebya.d(:com.google.android.gms@234414038@23.44.14 (190400-580326705):3)
	at ebyb.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):139)
	... 6 more
Caused by: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u15a138; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at cvxh.a(:com.google.android.gms@234414038@23.44.14 (190400-580326705):38)
	at cvxl.g(:com.google.android.gms@234414038@23.44.14 (190400-580326705):723)
	at cvxi.c(:com.google.android.gms@234414038@23.44.14 (190400-580326705):7)
	at com.google.android.gms.time.singleuserapi.service.TrustedTimeMaintenanceTaskService.hc(:com.google.android.gms@234414038@23.44.14 (190400-580326705):186)
	at bfxp.call(:com.google.android.gms@234414038@23.44.14 (190400-580326705):32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 6 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2457)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:14540)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14450)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:15416)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2661)


```

**Comment by muhomorr** [comment] 2023-11-12 17:58
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2649

**Closed by muhomorr** 2023-11-12 17:58 UTC

**Comment by thestinger** [comment] 2023-11-18 00:10
This is resolved by the latest release.
