### ISSUE TITLE
Enhancement: Make ANDROID_ID change for an app as soon as its reinstalled

### ISSUE THREAD

**Issue by Pauler221** [GrapheneOS/os-issue-tracker#1084] opened 2022-03-26 08:44 UTC
Some apps know they have already been installed and act differently becuase of that since the only "non resettable" non hardware identifier is the ANDROID_ID as far as i have undrstood it.

It would be great to prevent an app from accessing this ID or to reset this ID after an app is reinstalled or set a different ID for each app that is installed if that's possible. I know I can delete a profile and make a new one which gives me a new ID but its not that convenient also I cant reset the ID of the owner profile.

**Comment by thestinger** [comment] 2022-03-26 13:52
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/395.

**Comment by thestinger** [comment] 2022-03-26 13:53
> It would be great to prevent an app from accessing this ID or to reset this ID after an app is reinstalled or set a different ID for each app that is installed if that's possible.

It's already a per-app-per-profile value. It's the same value when the app is installed again but it's not the same value across apps.

**Closed by thestinger** 2022-03-26 13:52 UTC
