### ISSUE TITLE
Pixel 6a Screen/Night Dimming does not turn off

### ISSUE THREAD

**Issue by digitaldiamont** [GrapheneOS/os-issue-tracker#1963] opened 2023-02-14 11:33 UTC
Screen dimmer does not switch off although time period is set.
Pixel 6a

**Comment by r3g-5z** [comment] 2023-02-26 01:42
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/1268

**Closed by r3g-5z** 2023-02-26 01:42 UTC

**Comment by thestinger** [comment] 2023-03-13 19:01
Should be resolved by upstream QPR2 release.
