### ISSUE TITLE
Fsck_error

### ISSUE THREAD

**Issue by Q1A1B** [GrapheneOS/os-issue-tracker#3088] opened 2024-01-15 12:07 UTC
```
type: fsck_error
isPrevious: true
Build: google/redfin/redfin:14/UP1A.231105.001/2024011300:user/release-keys
Hardware: redfin
Revision: MP1.0
Bootloader: r3-0.6-10489834
Radio: null
Kernel: Linux version 4.19.282-gc92b5172dbc7 (build-user@build-host) (Android (7284624, based on r416183b) clang version 12.0.5 (https://android.googlesource.com/toolchain/llvm-project c935d99d7cf2016289302412d708641d52d2f7ee), LLD 12.0.5 (/buildbot/src/android/llvm-toolchain/out/llvm-project/lld c935d99d7cf2016289302412d708641d52d2f7ee)) #1 SMP PREEMPT Sun Dec 10 13:24:05 UTC 2023


fs_stat,/dev/block/platform/soc/1d84000.ufshc/by-name/persist,0x3

fs_stat,/dev/block/bootdevice/by-name/modem_a,0x0
Info: Fix the reported corruption.
Info: not exist /proc/version!
Info: MKFS version
  "4.19.261-gcd8080614a2a"
Info: FSCK version
  from "4.19.282-gc92b5172dbc7"
    to "4.19.282-gc92b5172dbc7"
Info: superblock features = 1499 :  encrypt verity extra_attr project_quota quota_ino casefold
Info: superblock encrypt level = 0, salt = 00000000000000000000000000000000
Info: Segments per section = 1
Info: Sections per zone = 1
Info: total FS sectors = 28602363 (111727 MB)
Info: CKPT version = 4516410d
Info: version timestamp cur: 23257329, prev: 20458167
[update_superblock: 775] Info: Done to update superblock
Info: checkpoint state = 145 :  trimmed crc compacted_summary unmount
[FSCK] Check node 1 / 128079 (0.00%)
[FSCK] Check node 12808 / 128079 (10.00%)
[FSCK] Check node 25615 / 128079 (20.00%)
[FSCK] Check node 38422 / 128079 (30.00%)
[FSCK] Check node 51229 / 128079 (40.00%)
[FSCK] Check node 64036 / 128079 (50.00%)
[FSCK] Check node 76843 / 128079 (60.00%)
[FSCK] Check node 89650 / 128079 (70.00%)
[FSCK] Check node 102457 / 128079 (80.00%)
[FSCK] Check node 115264 / 128079 (90.00%)
[FSCK] Check node 128071 / 128079 (100.00%)

[FSCK] Max image size: 34884 MB, Free space: 76842 MB
[FSCK] Unreachable nat entries                        [Ok..] [0x0]
[FSCK] SIT valid block bitmap checking                [Ok..]
[FSCK] Hard link checking for regular file            [Ok..] [0x1]
[FSCK] valid_block_count matching with CP             [Ok..] [0x8670db]
[FSCK] valid_node_count matching with CP (de lookup)  [Ok..] [0x1f44f]
[FSCK] valid_node_count matching with CP (nat lookup) [Ok..] [0x1f44f]
[FSCK] valid_inode_count matched with CP              [Ok..] [0x1d7d2]
[FSCK] free segment_count matched with CP             [Ok..] [0x95fa]
[FSCK] next block offset is free                      [Ok..]
[FSCK] fixing SIT types
[FSCK] other corrupted bugs                           [Ok..]

Done: 17.317444 secs

c, u, RA, CH, CM, Repl=
10000 10000 9057703 8817954 239749 229749

fs_stat,/dev/block/bootdevice/by-name/userdata,0x0
```

**Comment by muhomorr** [comment] 2024-01-15 13:27
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/3084

**Closed** 2024-01-15 13:27 UTC

**Comment by thestinger** [comment] 2024-01-16 10:19
This is a false positive error report due to an upstream Android bug. No corruption was detected and no error occurred. It will be worked around in a new GrapheneOS release tomorrow by filtering out filesystem check error reports with no errors.
