### ISSUE TITLE
adbd crash out of nowhere

### ISSUE THREAD

**Issue by ThatOneCalculator** [GrapheneOS/os-issue-tracker#2907] opened 2023-12-19 19:26 UTC
Pixel 7, happened during normal operation 

```
type: crash
osVersion: google/panther/panther:14/UQ1A.231205.015/2023121200:user/release-keys
uid: 2000 (u:r:adbd:s0)
cmdline: /apex/com.android.adbd/bin/adbd --root_seclabel=u:r:su:s0
processUptime: 13011s

abortMessage: failed to delete fd 21 from JDWP epoll fd: Bad file descriptor

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: jdwp control

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 62e64)
    /apex/com.android.adbd/lib64/libbase.so (android::base::DefaultAborter(char const*)+12, pc 368bc)
    /apex/com.android.adbd/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 38730)
    /apex/com.android.adbd/lib64/libbase.so (android::base::LogMessage::~LogMessage()+352, pc 37c30)
    /apex/com.android.adbd/bin/adbd (adbconnection_listen(void (*)(int, ProcessInfo))+1620, pc c5154)
    /apex/com.android.adbd/bin/adbd (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, init_jdwp()::$_0> >(void*)+168, pc c3928)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cf9ec)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64730)
```

**Comment by thestinger** [comment] 2023-12-19 19:50
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2724. It's an upstream issue.

**Closed by thestinger** 2023-12-19 19:50 UTC

**Comment by ThatOneCalculator** [comment] 2023-12-19 20:05
Is it? That seems to be related to Shizuku, but the Shizuku service wasn't even running at the time of the crash, nor was adb debugging even enabled

**Comment by thestinger** [comment] 2023-12-19 20:11
It's an upstream adbd bug, they're just triggering it with that misguided tool instead of the usual way.

**Comment by ThatOneCalculator** [comment] 2023-12-19 20:23
Interesting. Is "they" Google or the OP of the linked issue? And is the misguided tool Shizuku?
