### ISSUE TITLE
System server has crashed

### ISSUE THREAD

**Issue by BrunswickBTC** [GrapheneOS/os-issue-tracker#2838] opened 2023-12-12 19:20 UTC
```
type: crash
Process: system_server
Build: google/raven/raven:14/UQ1A.231205.015/2023120800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.AssertionError: Unable to create process group for app.vanadium.browser:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:4 (26139)
	at com.android.server.am.ProcessList.startProcess(ProcessList.java:2486)
	at com.android.server.am.ProcessList.lambda$handleProcessStart$1(ProcessList.java:2115)
	at com.android.server.am.ProcessList.$r8$lambda$x51oUQi6HPNnzxQPaHbqHBYY3LQ(ProcessList.java:0)
	at com.android.server.am.ProcessList$$ExternalSyntheticLambda3.run(R8$$SyntheticClass:0)
	at com.android.server.am.ProcessList.handleProcessStart(ProcessList.java:2141)
	at com.android.server.am.ProcessList.lambda$startProcessLocked$0(ProcessList.java:2081)
	at com.android.server.am.ProcessList.$r8$lambda$rd0BXPgECSWG21Kr8GWdMphFRuo(ProcessList.java:0)
	at com.android.server.am.ProcessList$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)

```

**Comment by thestinger** [comment] 2023-12-12 19:22
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2787.

**Closed by thestinger** 2023-12-12 19:22 UTC

**Comment by thestinger** [comment] 2023-12-13 01:37
https://grapheneos.org/releases#2023121200 raises the file descriptor limit and should resolve this Android 14 QPR1 issue unless it's caused by a file descriptor leak rather than higher file descriptor usage.
