### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by deralte99** [GrapheneOS/os-issue-tracker#2024] opened 2023-03-15 15:55 UTC
Started popping up overnight. Google Play Sandbox crashed. Google Play still seems to work but not getting updates. 

```
type: crash
osVersion: google/bluejay/bluejay:13/TQ1A.230205.002/2023030400:user/release-keys
package: com.google.android.googlequicksearchbox:301230437
process: com.google.android.googlequicksearchbox:search
processUptime: 64699 + 844 ms
GmsCompatConfig version: 37

java.lang.RuntimeException: Unable to instantiate receiver com.google.android.apps.search.assistant.verticals.automation.routines.receiver.GeofenceRecoveryReceiver_Receiver: java.lang.ClassNotFoundException: Didn't find class "com.google.android.apps.search.assistant.verticals.automation.routines.receiver.GeofenceRecoveryReceiver_Receiver" on path: DexPathList[[zip file "/data/app/~~lSi5PteDj9pEx9AcId6Glg==/com.google.android.googlequicksearchbox-7gFNHhzKmxUVlNK7ZNOo9w==/base.apk", zip file "/data/app/~~lSi5PteDj9pEx9AcId6Glg==/com.google.android.googlequicksearchbox-7gFNHhzKmxUVlNK7ZNOo9w==/split_config.xxhdpi.apk", zip file "/data/app/~~lSi5PteDj9pEx9AcId6Glg==/com.google.android.googlequicksearchbox-7gFNHhzKmxUVlNK7ZNOo9w==/split_fedora_brella_feature_module.apk"],nativeLibraryDirectories=[/data/app/~~lSi5PteDj9pEx9AcId6Glg==/com.google.android.googlequicksearchbox-7gFNHhzKmxUVlNK7ZNOo9w==/lib/arm64, /data/app/~~lSi5PteDj9pEx9AcId6Glg==/com.google.android.googlequicksearchbox-7gFNHhzKmxUVlNK7ZNOo9w==/base.apk!/lib/arm64-v8a, /data/app/~~lSi5PteDj9pEx9AcId6Glg==/com.google.android.googlequicksearchbox-7gFNHhzKmxUVlNK7ZNOo9w==/split_config.xxhdpi.apk!/lib/arm64-v8a, /data/app/~~lSi5PteDj9pEx9AcId6Glg==/com.google.android.googlequicksearchbox-7gFNHhzKmxUVlNK7ZNOo9w==/split_fedora_brella_feature_module.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4293)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2154)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.apps.search.assistant.verticals.automation.routines.receiver.GeofenceRecoveryReceiver_Receiver" on path: DexPathList[[zip file "/data/app/~~lSi5PteDj9pEx9AcId6Glg==/com.google.android.googlequicksearchbox-7gFNHhzKmxUVlNK7ZNOo9w==/base.apk", zip file "/data/app/~~lSi5PteDj9pEx9AcId6Glg==/com.google.android.googlequicksearchbox-7gFNHhzKmxUVlNK7ZNOo9w==/split_config.xxhdpi.apk", zip file "/data/app/~~lSi5PteDj9pEx9AcId6Glg==/com.google.android.googlequicksearchbox-7gFNHhzKmxUVlNK7ZNOo9w==/split_fedora_brella_feature_module.apk"],nativeLibraryDirectories=[/data/app/~~lSi5PteDj9pEx9AcId6Glg==/com.google.android.googlequicksearchbox-7gFNHhzKmxUVlNK7ZNOo9w==/lib/arm64, /data/app/~~lSi5PteDj9pEx9AcId6Glg==/com.google.android.googlequicksearchbox-7gFNHhzKmxUVlNK7ZNOo9w==/base.apk!/lib/arm64-v8a, /data/app/~~lSi5PteDj9pEx9AcId6Glg==/com.google.android.googlequicksearchbox-7gFNHhzKmxUVlNK7ZNOo9w==/split_config.xxhdpi.apk!/lib/arm64-v8a, /data/app/~~lSi5PteDj9pEx9AcId6Glg==/com.google.android.googlequicksearchbox-7gFNHhzKmxUVlNK7ZNOo9w==/split_fedora_brella_feature_module.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:110)
	at androidx.core.app.CoreComponentFactory.instantiateReceiver(PG:1)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4286)
	... 11 more
	Suppressed: java.io.IOException: Failed to open dex files from /data/app/~~lSi5PteDj9pEx9AcId6Glg==/com.google.android.googlequicksearchbox-7gFNHhzKmxUVlNK7ZNOo9w==/split_config.xxhdpi.apk because: Entry not found
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:371)
		at dalvik.system.DexFile.<init>(DexFile.java:113)
		at dalvik.system.DexFile.<init>(DexFile.java:86)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
		at dalvik.system.DexPathList.<init>(DexPathList.java:166)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:130)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:146)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:93)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:134)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:126)
		at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:61)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1034)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:1126)
		at android.app.LoadedApk.getResources(LoadedApk.java:1374)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3135)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3127)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6657)
		at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
		... 9 more
	Suppressed: java.io.IOException: Failed to open dex files from /data/app/~~lSi5PteDj9pEx9AcId6Glg==/com.google.android.googlequicksearchbox-7gFNHhzKmxUVlNK7ZNOo9w==/split_fedora_brella_feature_module.apk because: Entry not found
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:371)
		at dalvik.system.DexFile.<init>(DexFile.java:113)
		at dalvik.system.DexFile.<init>(DexFile.java:86)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
		at dalvik.system.DexPathList.<init>(DexPathList.java:166)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:130)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:146)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:93)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:134)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:126)
		at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:61)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1034)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:1126)
		at android.app.LoadedApk.getResources(LoadedApk.java:1374)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3135)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3127)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6657)
		at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
		... 9 more

```

**Comment by r3g-5z** [comment] 2023-03-15 15:57
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2024

Please give us more information, details, etc on what's being reported and how this occurred in there.

**Closed by r3g-5z** 2023-03-15 15:57 UTC
