### ISSUE TITLE
"Recent/open apps" is not accessible.

### ISSUE THREAD

**Issue by VulcanElf** [GrapheneOS/os-issue-tracker#1858] opened 2022-12-28 13:56 UTC
"Recent/open apps" will not show recent apps used, nor is each app tappable. Upon clearing all recent apps OR swiping each app away, they reappear when "recent/open apps" section is accessed again.

https://wormhole.app/bxrX9#fHOFtTl4LsBsn7Ize1IXWg

**Comment by octocorvus** [comment] 2022-12-28 14:02
Duplicate of #1822

**Closed** 2022-12-28 14:02 UTC

**Comment by octocorvus** [comment] 2022-12-28 14:03
A fix was found and is included in the next release of GrapheneOS

**Comment by VulcanElf** [comment] 2022-12-28 14:26
Thank you for a quick prognosis.
