### ISSUE TITLE
Screen freezes once time a day

### ISSUE THREAD

**Issue by mpiraz** [GrapheneOS/os-issue-tracker#1880] opened 2023-01-06 17:02 UTC
I'm using GOS with Pixel 6 for 1 year and after an upgrade in September /October  has begun the issue with complete screen freezing (with power button vibration when I push it) . It requires hard reboot.

**Comment by thestinger** [comment] 2023-01-06 19:49
This is a duplicate of a couple other issues.

**Closed by thestinger** 2023-01-06 19:49 UTC
