### ISSUE TITLE
android.hardware.biometrics.fingerprint-service crash

### ISSUE THREAD

**Issue by mmoduu** [GrapheneOS/os-issue-tracker#4302] opened 2024-11-08 14:03 UTC
```
type: crash
flags: dev options enabled
osVersion: google/husky/husky:15/AP3A.241105.007/2024110700:user/release-keys
uid: 1000 (u:r:hal_fingerprint_default:s0)
cmdline: /apex/com.google.android.hardware.biometrics.fingerprint/bin/hw/android.hardware.biometrics.fingerprint-service.goodix
processUptime: 100072s

signal: 11 (SIGSEGV), code 9 (SEGV_MTESERR), faultAddr 200c6be0759c510
threadName: android.hardwar
MTE: enabled

backtrace:
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libutils.so (android::VectorImpl::editArrayImpl()+28, pc 1224c)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::EventCenter::hasUpEvt()+20, pc 65894)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::DelmarSensor::checkFingerUp(unsigned int)+24, pc 4f074)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::DelmarSensor::readImage(unsigned int, unsigned long)+232, pc 4eb64)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::CustomizedSensor::readImage(unsigned int, unsigned long)+12, pc 6ca0c)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::DelmarFingerprintCore::onAfterAuthCapture(goodix::FingerprintCore::AuthenticateContext*)+76, pc 4d0cc)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::CustomizedFingerprintCore::onAfterAuthCapture(goodix::FingerprintCore::AuthenticateContext*)+492, pc 5a92c)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::FingerprintCore::onAuthDownEvt()+1212, pc 60b7c)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::FingerprintCore::onEvent(gf_event_type_t)+88, pc 619b8)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::EventCenter::dispatchEvent(gf_event_type_t)+196, pc 65384)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::EventCenter::threadLoop()+192, pc 65a20)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::Thread::sthreadLoop(void*)+28, pc 6465c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+200, pc 7bac8)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68, pc 6b6d4)
```

**Comment by muhomorr** [comment] 2024-11-08 15:48
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/4058

**Closed by muhomorr** 2024-11-08 15:48 UTC

**Comment by mmoduu** [comment] 2024-11-08 15:53
> @mmoduu Does fingerprint unlock continue to work after the crash?

Yes, although I needed to authenticate with PIN to get to see that crash log in the first place, and I didn't know it crashing before seeing that notification. So might be just a nuisance (which does not occur often, I didn't even remember I had reported it before)?
