### ISSUE TITLE
Sandboxed google crashed

### ISSUE THREAD

**Issue by Oktobear** [GrapheneOS/os-issue-tracker#2684] opened 2023-11-12 23:54 UTC
```
type: crash
osVersion: google/husky/husky:14/UD1A.231105.004/2023110700:user/release-keys
package: com.google.android.gms:234414039
process: com.google.android.gms.persistent
processUptime: 71925 + 432 ms
installer: com.android.vending
GmsCompatConfig version: 83

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a141; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at avyb.sendBroadcastAsUser(:com.google.android.gms@234414039@23.44.14 (190408-580326705):6)
	at cvxh.a(:com.google.android.gms@234414039@23.44.14 (190408-580326705):38)
	at cvxj.run(:com.google.android.gms@234414039@23.44.14 (190408-580326705):11)
	at ajls.c(:com.google.android.gms@234414039@23.44.14 (190408-580326705):50)
	at ajls.run(:com.google.android.gms@234414039@23.44.14 (190408-580326705):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ajqx.run(:com.google.android.gms@234414039@23.44.14 (190408-580326705):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvmi: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2457)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:14540)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14450)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:15416)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2661)


```

**Comment by thestinger** [comment] 2023-11-12 23:57
This is a duplicate of several recently filed issues. It has been resolved for the next OS release already.

**Closed by thestinger** 2023-11-12 23:57 UTC

**Comment by Oktobear** [comment] 2023-11-12 23:58
Alright mr
