### ISSUE TITLE
crash report - Google Play Services

### ISSUE THREAD

**Issue by mateowoetam** [GrapheneOS/os-issue-tracker#2653] opened 2023-11-04 16:24 UTC
```
type: crash
osVersion: google/coral/coral:13/TP1A.221005.002.B2/2023100300:user/release-keys
package: com.google.android.gms:234355038
process: com.google.android.gms.persistent
processUptime: 7238895 + 459 ms
installer: com.android.vending
GmsCompatConfig version: 82

java.lang.RuntimeException: Rethrown by StandaloneSchedulingEngine
	at cmzk.a(:com.google.android.gms@234355038@23.43.55 (190400-577318215):455)
	at cmwk.run(:com.google.android.gms@234355038@23.43.55 (190400-577318215):9)
	at ajlc.c(:com.google.android.gms@234355038@23.43.55 (190400-577318215):50)
	at ajlc.run(:com.google.android.gms@234355038@23.43.55 (190400-577318215):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at ajqf.run(:com.google.android.gms@234355038@23.43.55 (190400-577318215):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dviq: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.RuntimeException: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u11a167; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at bfub.apply(:com.google.android.gms@234355038@23.43.55 (190400-577318215):5)
	at ebua.d(:com.google.android.gms@234355038@23.43.55 (190400-577318215):3)
	at ebub.run(:com.google.android.gms@234355038@23.43.55 (190400-577318215):139)
	... 6 more
Caused by: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u11a167; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
	at android.os.Parcel.createException(Parcel.java:3004)
	at android.os.Parcel.readException(Parcel.java:2980)
	at android.os.Parcel.readException(Parcel.java:2922)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5111)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1473)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1440)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at avwq.sendBroadcastAsUser(:com.google.android.gms@234355038@23.43.55 (190400-577318215):6)
	at cvrq.a(:com.google.android.gms@234355038@23.43.55 (190400-577318215):39)
	at cvrv.g(:com.google.android.gms@234355038@23.43.55 (190400-577318215):723)
	at cvrr.c(:com.google.android.gms@234355038@23.43.55 (190400-577318215):7)
	at com.google.android.gms.time.singleuserapi.service.TrustedTimeMaintenanceTaskService.hb(:com.google.android.gms@234355038@23.43.55 (190400-577318215):186)
	at bfuc.call(:com.google.android.gms@234355038@23.43.55 (190400-577318215):32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 6 more

```

**Comment by muhomorr** [comment] 2023-11-06 07:42
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2649

**Closed** 2023-11-06 07:42 UTC
