### ISSUE TITLE
Error Sandboxed Google play crashed

### ISSUE THREAD

**Issue by stdestro** [GrapheneOS/os-issue-tracker#1719] opened 2022-11-21 09:42 UTC
Hi, I got this error a couple of times:

````
type: crash
osVersion: google/oriole/oriole:13/TP1A.221105.002/2022111800:user/release-keys
package: com.google.android.gms:224417044
process: com.google.android.gms.persistent
processUptime: 3655501 + 495 ms
GmsCompatConfig version: 17

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.CONFIGURED_NETWORKS_CHANGE flg=0x4000010 (has extras) } in com.google.android.gms.wearable.node.WifiService$SavedNetworkBroadcastReceiver@8caa735
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1800)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.SecurityException: WifiService: Neither user 10125 nor current process has android.permission.READ_WIFI_CREDENTIAL.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.net.wifi.IWifiManager$Stub$Proxy.getPrivilegedConfiguredNetworks(IWifiManager.java:2210)
	at android.net.wifi.WifiManager.getPrivilegedConfiguredNetworks(WifiManager.java:1697)
	at ccsl.e(:com.google.android.gms@224417044@22.44.17 (190400-488410709):4)
	at ccsl.i(:com.google.android.gms@224417044@22.44.17 (190400-488410709):3)
	at ccsl.g(:com.google.android.gms@224417044@22.44.17 (190400-488410709):1)
	at com.google.android.gms.wearable.node.WifiService$SavedNetworkBroadcastReceiver.a(:com.google.android.gms@224417044@22.44.17 (190400-488410709):6)
	at com.google.android.gms.libs.punchclock.tracing.TracingBroadcastReceiver.onReceive(:com.google.android.gms@224417044@22.44.17 (190400-488410709):2)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2285)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2313)
	at android.content.ContextWrapper.enforceCallingOrSelfPermission(ContextWrapper.java:948)
	at com.android.server.wifi.WifiServiceImpl.enforceReadCredentialPermission(WifiServiceImpl.java:1070)
	at com.android.server.wifi.WifiServiceImpl.getPrivilegedConfiguredNetworks(WifiServiceImpl.java:3029)


```

`

**Comment by hjangadi** [comment] 2022-11-21 17:03
I too got this error couple of times: see the logs below
``
type: crash
osVersion: google/cheetah/cheetah:13/TD1A.221105.001/2022111800:user/release-keys
package: com.google.android.gms:224417044
process: com.google.android.gms.persistent
processUptime: 20535077 + 305 ms
GmsCompatConfig version: 17

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.CONFIGURED_NETWORKS_CHANGE flg=0x4000010 (has extras) } in com.google.android.gms.wearable.node.WifiService$SavedNetworkBroadcastReceiver@c6d7fd0
at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1800)
at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7904)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ExecInit.main(ExecInit.java:49)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.SecurityException: WifiService: Neither user 10127 nor current process has android.permission.READ_WIFI_CREDENTIAL.
at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
at android.os.Parcel.createException(Parcel.java:3005)
at android.os.Parcel.readException(Parcel.java:2981)
at android.os.Parcel.readException(Parcel.java:2923)
at android.net.wifi.IWifiManager$Stub$Proxy.getPrivilegedConfiguredNetworks(IWifiManager.java:2210)
at android.net.wifi.WifiManager.getPrivilegedConfiguredNetworks(WifiManager.java:1697)
at ccsl.e(:com.google.android.gms@224417044@22.44.17 (190400-488410709):4)
at ccsl.i(:com.google.android.gms@224417044@22.44.17 (190400-488410709):3)
at ccsl.g(:com.google.android.gms@224417044@22.44.17 (190400-488410709):1)
at com.google.android.gms.wearable.node.WifiService$SavedNetworkBroadcastReceiver.a(:com.google.android.gms@224417044@22.44.17 (190400-488410709):6)
at com.google.android.gms.libs.punchclock.tracing.TracingBroadcastReceiver.onReceive(:com.google.android.gms@224417044@22.44.17 (190400-488410709):2)
at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
at android.app.ContextImpl.enforce(ContextImpl.java:2285)
at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2313)
at android.content.ContextWrapper.enforceCallingOrSelfPermission(ContextWrapper.java:948)
at com.android.server.wifi.WifiServiceImpl.enforceReadCredentialPermission(WifiServiceImpl.java:1070)
at com.android.server.wifi.WifiServiceImpl.getPrivilegedConfiguredNetworks(WifiServiceImpl.java:3029)

**Comment by muhomorr** [comment] 2022-11-22 07:42
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/1716

**Closed** 2022-11-22 08:00 UTC

**Comment by medecai0815** [comment] 2022-11-22 08:40
Happens atleast every time i toggle airplane mode and when I leave my wifi area. 

```
type: crash
osVersion: google/panther/panther:13/TD1A.221105.001/2022111800:user/release-keys
package: com.google.android.gms:224417044
process: com.google.android.gms.persistent
processUptime: 1032544 + 349 ms
GmsCompatConfig version: 17

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.CONFIGURED_NETWORKS_CHANGE flg=0x4000010 (has extras) } in com.google.android.gms.wearable.node.WifiService$SavedNetworkBroadcastReceiver@dc7d281
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1800)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.SecurityException: WifiService: Neither user 10125 nor current process has android.permission.READ_WIFI_CREDENTIAL.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.net.wifi.IWifiManager$Stub$Proxy.getPrivilegedConfiguredNetworks(IWifiManager.java:2210)
	at android.net.wifi.WifiManager.getPrivilegedConfiguredNetworks(WifiManager.java:1697)
	at ccsl.e(:com.google.android.gms@224417044@22.44.17 (190400-488410709):4)
	at ccsl.i(:com.google.android.gms@224417044@22.44.17 (190400-488410709):3)
	at ccsl.g(:com.google.android.gms@224417044@22.44.17 (190400-488410709):1)
	at com.google.android.gms.wearable.node.WifiService$SavedNetworkBroadcastReceiver.a(:com.google.android.gms@224417044@22.44.17 (190400-488410709):6)
	at com.google.android.gms.libs.punchclock.tracing.TracingBroadcastReceiver.onReceive(:com.google.android.gms@224417044@22.44.17 (190400-488410709):2)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2285)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2313)
	at android.content.ContextWrapper.enforceCallingOrSelfPermission(ContextWrapper.java:948)
	at com.android.server.wifi.WifiServiceImpl.enforceReadCredentialPermission(WifiServiceImpl.java:1070)
	at com.android.server.wifi.WifiServiceImpl.getPrivilegedConfiguredNetworks(WifiServiceImpl.java:3029)


```
