### ISSUE TITLE
Error in Google Services Framework

### ISSUE THREAD

**Issue by Gospodininzenjer** [GrapheneOS/os-issue-tracker#1653] opened 2022-11-09 10:29 UTC
```
type: crash
osVersion: google/sunfish/sunfish:13/TP1A.221105.002/2022110800:user/release-keys
package: com.google.android.gsf:33
process: com.google.process.gservices

java.lang.RuntimeException: Unable to start receiver com.google.android.gsf.gservices.GservicesProvider$OverrideReceiver: java.lang.SecurityException: com.google.android.gsf was not granted  this permission: android.permission.WRITE_SETTINGS.
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4346)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.SecurityException: com.google.android.gsf was not granted  this permission: android.permission.WRITE_SETTINGS.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:557)
	at android.content.ContentResolver.insert(ContentResolver.java:2216)
	at android.content.ContentResolver.insert(ContentResolver.java:2175)
	at com.google.android.gsf.gservices.GservicesProvider.syncSettingsFromGsfStorage(GservicesProvider.java:631)
	at com.google.android.gsf.gservices.GservicesProvider.syncAllSettingsFromGsfStorage(GservicesProvider.java:581)
	at com.google.android.gsf.gservices.GservicesProvider.updateGsfStorageOverridesTable(GservicesProvider.java:730)
	at com.google.android.gsf.gservices.GservicesProvider.updateOverride(GservicesProvider.java:425)
	at com.google.android.gsf.gservices.GservicesProvider.update(GservicesProvider.java:385)
	at android.content.ContentProvider.update(ContentProvider.java:1882)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:465)
	at android.content.ContentResolver.update(ContentResolver.java:2423)
	at android.content.ContentResolver.update(ContentResolver.java:2385)
	at com.google.android.gsf.gservices.GservicesProvider$OverrideReceiver.onReceive(GservicesProvider.java:119)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4337)
	... 11 more

```

**Comment by muhomorr** [comment] 2022-11-09 17:47
When does this crash happen? Does it happen once or many times?

**Comment by muhomorr** [comment] 2022-11-10 06:30
It looks like you've granted the "Modify system settings" permission to Play services and it causes GSF to crash.
If yes, revoke it.

**Comment by gonzalo-** [comment] 2022-11-10 09:06
I have the same in my Pixel 5, and I didn't give any "Modify system settings" permission to Play services, for me it crashed 4 times in the past 2 or 3 hours.

**Comment by muhomorr** [comment] 2022-11-10 10:02
@gonzalo- It's not the same issue. Crashes that you posted are fixed by GmsCompatConfig v15

**Comment by gonzalo-** [comment] 2022-11-10 10:45
@muhomorr thanks!

**Comment by Gospodininzenjer** [comment] 2022-12-02 13:00
```
type: crash
osVersion: google/sunfish/sunfish:13/TP1A.221105.002/2022113000:user/release-keys
package: com.google.android.gsf:33
process: com.google.process.gservices
processUptime: 3615338 + 2218 ms
GmsCompatConfig version: 17

java.lang.RuntimeException: Unable to start receiver com.google.android.gsf.gservices.GservicesProvider$OverrideReceiver: java.lang.SecurityException: com.google.android.gsf was not granted  this permission: android.permission.WRITE_SETTINGS.
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4346)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.SecurityException: com.google.android.gsf was not granted  this permission: android.permission.WRITE_SETTINGS.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:557)
	at android.content.ContentResolver.insert(ContentResolver.java:2216)
	at android.content.ContentResolver.insert(ContentResolver.java:2175)
	at com.google.android.gsf.gservices.GservicesProvider.syncSettingsFromGsfStorage(GservicesProvider.java:631)
	at com.google.android.gsf.gservices.GservicesProvider.syncAllSettingsFromGsfStorage(GservicesProvider.java:581)
	at com.google.android.gsf.gservices.GservicesProvider.updateGsfStorageOverridesTable(GservicesProvider.java:730)
	at com.google.android.gsf.gservices.GservicesProvider.updateOverride(GservicesProvider.java:425)
	at com.google.android.gsf.gservices.GservicesProvider.update(GservicesProvider.java:385)
	at android.content.ContentProvider.update(ContentProvider.java:1882)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:465)
	at android.content.ContentResolver.update(ContentResolver.java:2423)
	at android.content.ContentResolver.update(ContentResolver.java:2385)
	at com.google.android.gsf.gservices.GservicesProvider$OverrideReceiver.onReceive(GservicesProvider.java:119)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4337)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.provider.Settings.isCallingPackageAllowedToPerformAppOpsProtectedOperation(Settings.java:18589)
	at android.provider.Settings.checkAndNoteWriteSettingsOperation(Settings.java:18477)
	at com.android.providers.settings.SettingsProvider.mutateSystemSetting(SettingsProvider.java:1890)
	at com.android.providers.settings.SettingsProvider.insertSystemSetting(SettingsProvider.java:1856)
	at com.android.providers.settings.SettingsProvider.insert(SettingsProvider.java:700)


```![Screenshot_20221202-135955.png](https://user-images.githubusercontent.com/116552355/205298523-e22bcbe8-76b4-404d-a673-df2d2642cdb0.png)

**Comment by muhomorr** [comment] 2022-12-02 13:30
@Gospodininzenjer Can you send me a full bugreport next time this crash happens?
https://developer.android.com/studio/debug/bug-report#bugreportdevice

**Comment by Gospodininzenjer** [comment] 2022-12-02 13:31
Yes i do, thank you

**Comment by Gospodininzenjer** [comment] 2022-12-02 13:32
I can, thank you for your qiuck answer

**Comment by Gospodininzenjer** [comment] 2022-12-02 15:17
```
type: crash
osVersion: google/sunfish/sunfish:13/TP1A.221105.002/2022113000:user/release-keys
package: com.google.android.gsf:33
process: com.google.process.gservices
processUptime: 4300203 + 311 ms
GmsCompatConfig version: 17

java.lang.RuntimeException: Unable to start receiver com.google.android.gsf.gservices.GservicesProvider$OverrideReceiver: java.lang.SecurityException: com.google.android.gsf was not granted this permission: android.permission.WRITE_SETTINGS.
at android.app.ActivityThread.handleReceiver(ActivityThread.java:4346)
at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7904)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ExecInit.main(ExecInit.java:49)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.SecurityException: com.google.android.gsf was not granted this permission: android.permission.WRITE_SETTINGS.
at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
at android.os.Parcel.createException(Parcel.java:3005)
at android.os.Parcel.readException(Parcel.java:2981)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
at android.content.ContentProviderProxy.insert(ContentProviderNative.java:557)
at android.content.ContentResolver.insert(ContentResolver.java:2216)
at android.content.ContentResolver.insert(ContentResolver.java:2175)
at com.google.android.gsf.gservices.GservicesProvider.syncSettingsFromGsfStorage(GservicesProvider.java:631)
at com.google.android.gsf.gservices.GservicesProvider.syncAllSettingsFromGsfStorage(GservicesProvider.java:581)
at com.google.android.gsf.gservices.GservicesProvider.updateGsfStorageOverridesTable(GservicesProvider.java:730)
at com.google.android.gsf.gservices.GservicesProvider.updateOverride(GservicesProvider.java:425)
at com.google.android.gsf.gservices.GservicesProvider.update(GservicesProvider.java:385)
at android.content.ContentProvider.update(ContentProvider.java:1882)
at android.content.ContentProvider$Transport.update(ContentProvider.java:465)
at android.content.ContentResolver.update(ContentResolver.java:2423)
at android.content.ContentResolver.update(ContentResolver.java:2385)
at com.google.android.gsf.gservices.GservicesProvider$OverrideReceiver.onReceive(GservicesProvider.java:119)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:4337)
... 11 more

```

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by r3g-5z** [comment] 2023-02-04 20:27
Is this still reproducible?

**Closed** 2023-02-05 05:52 UTC
Labels: bug
