### ISSUE TITLE
Microphone not working when camera is disabled 

### ISSUE THREAD

**Issue by euakll** [GrapheneOS/os-issue-tracker#2074] opened 2023-04-02 21:27 UTC
Observed during a Signal call.

When you deactivate Camera Access globally to all apps,  your call partner doesn't hear you any more. Microphone Access stays on globally all the time. As soon camera is activated again, all is working again.

**Comment by r3g-5z** [comment] 2023-04-02 21:34
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2042

**Closed by r3g-5z** 2023-04-02 21:34 UTC
