### ISSUE TITLE
Hotspot "TTL toggle button"?

### ISSUE THREAD

**Issue by yodaforces** [GrapheneOS/os-issue-tracker#993] opened 2022-02-17 21:39 UTC
Thinking of have an optional toggle button for TTL in order to make it harder for the ISP/mobile data provider to see a hotspot being used? This can already be done on the connected hotspot device(s) but could maybe be useful for some people out there?

What's your thougths on this?

**Comment by thestinger** [comment] 2022-02-17 21:40
It would require disabling hardware offload.

**Comment by flawedworld** [comment] 2022-02-18 00:30
I think we could potentially do this as a "nice to have" on top of the OS always allowing tethering on any carrier, but I don't really see it as a feature improving security/privacy.

**Comment by thestinger** [comment] 2022-03-17 05:59
Closing as a duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/30 since it can be provided that way.

**Closed by thestinger** 2022-03-17 05:59 UTC
Labels: enhancement
