### ISSUE TITLE
Bug: Accessibility Features will not disable

### ISSUE THREAD

**Issue by X2K1ng** [GrapheneOS/os-issue-tracker#2263] opened 2023-06-20 18:16 UTC
Platform: Google Pixel 7 Pro
OS Version: 13 (TQ3A.230605.012.2023061402)
Issue: When Accessibility features are enables, they do not disable. When enabling any of the  following: "Extra Dim", "Colour Correction", " Colour Inversion". The phone stays in mode even after it is disabled.

Observation: if for example, "Color inversion" is enabled then disabled. The phone's colors stay inverted, BUT if you enable the "Extra Dim" it causes colours to revert back to normal. However, this only happens if "Colour Inversion" was disabled beforehand, otherwise screen is dimmed and inverted. It is important to also note that when the screen has two features enabled, as long as one stays enabled the other feature enables and disables properly, the last one to be disabled will not be disabled.

To Replicate:

    Open Settings App
    Select Accessibility settings
    Enable an accessibility feature
    Disable an accessibility feature

Temporary Fix: 
(1) Make sure the accessibility feature(s) is disabled, Hold the power button and restart the device. Phone will return to normal.
(2)Go to settings>display>colours. Change the colour to another colour setting other than the one currently selected and the accessibility feature that has did not disable will disable (you can put the colour back to the one that you originally had but you have to just click on another colour setting first)

Please let me know if you require additional info to resolve this issue.

**Comment by michaelscarpa** [comment] 2023-08-20 21:41
I can confirm this is happening for me, too.  System up to date at the time of writing.

**Comment by matrixneo135** [comment] 2023-10-12 18:23
Duplicate of #1437

**Closed** 2023-10-16 23:33 UTC
