### ISSUE TITLE
fix: color correction deactivation

### ISSUE THREAD

**Issue by FerranAD** [GrapheneOS/os-issue-tracker#2662] opened 2023-11-07 15:34 UTC
When activating any kind of color correction it then becomes impossible to deactivate color correction, the only thing possible is to change between different kinds of color correction. The only solution I find is to reboot the phone.

Note that the UI button seems to work, but it doesn't actually deactivate the color correction. Recreation on the attached photos, note that I upload photos instead of screesnhots since screenshots remove color correction filter.

![screenshot1](https://github.com/GrapheneOS/grapheneos.org/assets/72612615/20f46e61-8016-4c7b-9372-da94172a2a5e)
![screenshot2](https://github.com/GrapheneOS/grapheneos.org/assets/72612615/050daed4-f395-4ef9-8238-dfb93d867d7a)

Device: Pixel 7a
Build-Nr: UP1A.231005.007.2023103100

**Comment by BadEnoughDude** [comment] 2023-12-23 07:25
I encounter this issue with color inversion as well

Pixel 8 Pro on build UQ1A.231205.015.2023121200

**Comment by thestinger** [comment] 2023-12-23 14:47
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/1437.

**Closed by thestinger** 2023-12-23 14:47 UTC
