### ISSUE TITLE
Done button of expanded Bluetooth tile has wrong corner radius

### ISSUE THREAD

**Issue by danielmehring** [GrapheneOS/os-issue-tracker#3705] opened 2024-07-02 04:42 UTC
![Screenshot_1](https://github.com/GrapheneOS/os-issue-tracker/assets/37716951/511247ab-b450-47f0-addb-2d4f437f9690)

The done button here changed two updates ago. It doesn't have the same radius anymore as the others.

![Screenshot_2](https://github.com/GrapheneOS/os-issue-tracker/assets/37716951/aaee18e0-150a-4856-bed4-8d7dd56017bd)

**Comment by muhomorr** [comment] 2024-07-02 07:30
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/3636

**Closed by muhomorr** 2024-07-02 07:30 UTC
