### ISSUE TITLE
MS Outlook crashes during initial setup screens

### ISSUE THREAD

**Issue by mailtodelete** [GrapheneOS/os-issue-tracker#903] opened 2022-01-09 01:53 UTC
I am on Graphene build SQ1A.220105.002.2022010500, and am attempting to run Outlook version 4.2147.4, installed from the Play store. It crashes a few seconds after launch. I would be happy to help troubleshoot if someone has ideas.

**Comment by Zanthed** [comment] 2022-01-09 02:17
https://github.com/GrapheneOS/Vanadium/issues/105#issuecomment-982194309

https://github.com/GrapheneOS/Vanadium/issues/105#issuecomment-1003243533

**Comment by thestinger** [comment] 2022-01-09 10:38
This is almost certainly as bug in Outlook and there isn't going to be any progress unless a contributor decides to work on this by narrowing down the cause of the issue to a specific GrapheneOS feature such as hardened_malloc and then narrowing down why that happens. Once they do that, it may be possible to implement a workaround. It ultimately needs to be fixed by Microsoft for Outlook. We're unable to devote time to resolving issues caused by third party app bugs. I'll be closing this issue eventually if no one works on it since it should really be filed with Microsoft.

**Comment by mailtodelete** [comment] 2022-01-09 15:35
> This is almost certainly as bug in Outlook and there isn't going to be any progress unless a contributor decides to work on this by narrowing down the cause of the issue to a specific GrapheneOS feature such as hardened_malloc and then narrowing down why that happens. Once they do that, it may be possible to implement a workaround. It ultimately needs to be fixed by Microsoft for Outlook. We're unable to devote time to resolving issues caused by third party app bugs. I'll be closing this issue eventually if no one works on it since it should really be filed with Microsoft.

I am quite new and would need assistance locating the required logs, etc, but I'm a skilled troubleshooter and would not mind doing the legwork to correspond with MS if anyone would care to work with me.

**Comment by flawedworld** [comment] 2022-01-09 15:40
For reference to anyone looking to fix this, you will need to compile a userdebug GrapheneOS build as you need root access to read the logs of Outlook due to it not logging to logcat.

**Comment by pkhomyakov-rms** [comment] 2022-01-09 19:31
The issue is 100% with the apps. More specifically, the crash happens in init code of native Hermes JS library usually used with React Native. Other applications using the library crash as well on Graphene. ATT account management app is one example. Almost exactly the same backtrace.

Curiously only 64 bit version is affected. Outlook application for armv7 and hence using `lib/armeabi-v7a/libhermes.so` seems to work fine. 

A possible simple workaround is to use an alternative store front like Aurora with device ID spoofed to armv7 kind and downloading 32-bit version of Outlook APK. If you don't trust direct Aurora download you can have it show exact download URL instead to confirm that the APK is loading from official Google Play Store.

32-bit Outlook APK downloaded and installed that way has worked for me with no issues on Pixel 5a on both Graphene 11 and 12. I have not hit any problems or incompatibilities with other 64-bit office apps installed normally.

**Comment by thestinger** [comment] 2022-01-09 19:39
It's likely that it's incompatible with hardened_malloc. It needs to be debugged and reported upstream to get this resolved for the future. For existing apps we can implement a workaround.

**Comment by pkhomyakov-rms** [comment] 2022-01-09 20:18
I am not sure you should do a workaround. It is not possible to chase every buggy 3rd party app in the universe. It has been some time (and I might be wrong) but what I remember about that crash is that hermes was going for an address it should not have to, meaning hardened_malloc did exactly what it was designed to do.

**Comment by mailtodelete** [comment] 2022-01-09 20:53
> Curiously only 64 bit version is affected.

Holy Cow, you are correct... I was able to load the 32 bit client and it works fine. Thanks for the tip!

**Comment by thestinger** [comment] 2022-01-10 07:21
Please leave it open for now. We need a contributor to work on this.

**Comment by thestinger** [comment] 2022-01-10 07:22
The issue needs to be reported upstream.

**Comment by mailtodelete** [comment] 2022-01-11 17:56
No problem, thanks. 
    On Monday, January 10, 2022, 02:21:52 AM EST, Daniel Micay ***@***.***> wrote:  
 
 


Please leave it open for now. We need a contributor to work on this.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by flawedworld** [comment] 2022-01-23 19:43
Microsoft have fixed this now. I'm going to assume judging from my demo react hermes application working fine that hermes has resolved this.

**Comment by flawedworld** [comment] 2022-01-23 19:44
I also sent a feedback form to Microsoft about this, so maybe they acted on that.

**Closed by flawedworld** 2022-01-23 19:43 UTC
Labels: bug, upstream
