### ISSUE TITLE
Background app restriction not working

### ISSUE THREAD

**Issue by Undisputed00x** [GrapheneOS/os-issue-tracker#3124] opened 2024-01-20 15:29 UTC
Hi guys, just got an Pixel 6 Pro and flashed GrapheneOS on it. After some days my only issue for now is that there is some considerable battery drainage.
Checked the running services in Dev mode i see apps like [Aurora Store](https://gitlab.com/AuroraOSS/AuroraStore), [Nekogram](https://github.com/Nekogram/Nekogram) and [Google camera](https://play.google.com/store/apps/details?id=com.google.android.GoogleCamera&pli=1) still operating. In every app denied any background operation if possible and  restricted their battery usage policy on settings but still these apps are shown on running services.

Downloaded [PermissionManagerX](https://github.com/mirfatif/PermissionManagerX) in ADB mode and i saw that despite denying `START_FOREGROUND` `RUN_ANY_IN_BACKGROUND` `RUN_IN_BACKGROUND` AppOps there is enabled a normal app permission of the app  `android.normal.FOREGROUND_SERVICE` that cant be touched unless phone's rooted ?

1. My question is that are these apps that im referring to working in foreground instead of background? 
2. [Nekogram](https://github.com/Nekogram/Nekogram) although not shown on running services still fetches data and pops notifications. Whats up with that ?
3. If so shouldnt GrapheneOS shut down those app with restricted battery usage policy?
4. Is there a way for these apps to shut down completely after user closes them.

<details><summary>Details</summary>
<p>

![IMG_20240120_162128](https://github.com/GrapheneOS/os-issue-tracker/assets/80290008/e2254173-36f1-4bf2-8f60-7ce306689eda)
![Screenshot_20240120-161836](https://github.com/GrapheneOS/os-issue-tracker/assets/80290008/5e3c3271-11c6-45c1-9c83-2a731a734bec)
![Screenshot_20240120-161817](https://github.com/GrapheneOS/os-issue-tracker/assets/80290008/6a1bfcb4-306f-46e9-a4d1-a0062043c74b)
![Screenshot_20240120-161033](https://github.com/GrapheneOS/os-issue-tracker/assets/80290008/d6d65ff9-576c-42f6-9d70-83022475fc01)

</p>
</details>

**Comment by thestinger** [comment] 2024-01-20 17:13
> Hi guys, just got an Pixel 6 Pro and flashed GrapheneOS on it. After some days my only issue for now is that there is some considerable battery drainage.

It has better battery life by default so this is caused by your configuration and apps. Not enough information on what you have installed and set up to respond. It's unlikely that it's an OS bug.

> Checked the running services in Dev mode i see apps like [Aurora Store](https://gitlab.com/AuroraOSS/AuroraStore), [Nekogram](https://github.com/Nekogram/Nekogram) and [Google camera](https://play.google.com/store/apps/details?id=com.google.android.GoogleCamera&pli=1) still operating. In every app denied any background operation if possible and restricted their battery usage policy on settings but still these apps are shown on running services.

The services not being killed does not mean they can run. Processes are frozen via the cgroup freezer when they're not meant to running. Killing cached services and app processes will reduce rather than improving your battery life.

> Downloaded [PermissionManagerX](https://github.com/mirfatif/PermissionManagerX) in ADB mode

This is not a good idea.

> and i saw that despite denying START_FOREGROUND RUN_ANY_IN_BACKGROUND RUN_IN_BACKGROUND AppOps

Apps can already only start a foreground service from the foreground and the Restricted battery mode already disables what they can do by default along with delaying their alarms/jobs to when they run again. Why not simply use Restricted battery mode? It works fine, and you seem to be misunderstanding the difference between an app being cached in memory and being app to run.

> My question is that are these apps that im referring to working in foreground instead of background?

Neither.

> [Nekogram](https://github.com/Nekogram/Nekogram) although not shown on running services still fetches data and pops notifications. Whats up with that ?

If you're using sandboxed Google Play, FCM wakes apps.

> If so shouldnt GrapheneOS shut down those app with restricted battery usage policy?

The standard Restricted battery mode works fine, the issue is you're misunderstanding information in developer options.

> Is there a way for these apps to shut down completely after user closes them.

Closing apps rather than stopping them from running will **increase** power usage.

Use Restricted battery mode. It won't prevent them starting a foreground service from the foreground, but those are completely visible to you and you would know which apps are running one since they have to make a non-collapsed persistent notification with a status bar icon and lockscreen visibility by default (can be turned down or disabled by you) and show up in active apps.

**Comment by thestinger** [comment] 2024-01-20 17:13
Please use Matrix and the discussion forum for support in the future. There's no issue to report here.

**Closed by thestinger** 2024-01-20 17:13 UTC
