### ISSUE TITLE
Intermittent Screen Time Out

### ISSUE THREAD

**Issue by Metr0pl3x** [GrapheneOS/os-issue-tracker#1268] opened 2022-06-22 15:58 UTC
It has been reported on the Community forum that users are experiencing variable screen time out beyond the limit set under:
SETTINGS>DISPLAY>Screen Timeout

This is occurring across devices, those listed so far are Pixel 4a and Pixel 5. No screen protectors on or change in touch sensitivity options.

Users have taken bug reports upon experiencing this and have only found one reported instance of KEEP_SCREEN_ON flag appearing for an app they were not using at the time such as browsing in Vanadium.

https://discuss.grapheneos.org/d/78-screen-timeout-intermittent

**Comment by skykingisepic** [comment] 2023-02-26 20:13
Screen is constantly staying awake instead of sleeping after 30 seconds. All apps closed from background, nothing running. Pixel 6. Must press pwr button to sleep.

**Comment by thestinger** [comment] 2023-02-26 20:15
You need to provide more information such as showing your display timeout configuration and saying if you're using multiple users.

**Comment by thestinger** [comment] 2023-03-13 19:01
Should be resolved by upstream QPR2 release.

**Comment by skykingisepic** [comment] 2023-03-25 16:46
After latest system update, screen still stays awake half the time when various apps close.

**Comment by robertoprubio** [comment] 2023-03-27 11:45
Sometimes the screen doesn't turn off automatically when screen time passes (30 seconds in my case, but I have tried also 1 minute and the issue still occurs sometimes).
When this occurs the screen remains on until I turn off manually via the power button.
I do not use additional user profiles.

**Comment by heldrosil** [comment] 2023-04-24 10:41
This happens to me too, on the latest version of April stock OS and graphene OS (pixel 6).

**Comment by thestinger** [comment] 2023-04-24 12:32
We aren't going to be addressing these issues downstream.

**Closed** 2023-10-26 22:14 UTC
Labels: bug, upstream

**Comment by thestinger** [comment] 2023-10-26 22:15
No known issues with this. There are some standard features which enable keeping it awake longer but this is all working as intended as far as we can tell. Providing more configuration is an option but not what this was filed about.
