### ISSUE TITLE
adbd crash

### ISSUE THREAD

**Issue by David-Prock** [GrapheneOS/os-issue-tracker#2726] opened 2023-11-28 17:13 UTC
```
type: crash
osVersion: google/husky/husky:14/UD1A.231105.004/2023112600:user/release-keys
uid: 2000 (u:r:adbd:s0)
cmdline: /apex/com.android.adbd/bin/adbd --root_seclabel=u:r:su:s0
processUptime: 31213s

abortMessage: failed to delete fd 20 from JDWP epoll fd: Bad file descriptor

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: jdwp control
MTE: enabled

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 6e464)
    /apex/com.android.adbd/lib64/libbase.so (android::base::DefaultAborter(char const*)+12, pc 23a1c)
    /apex/com.android.adbd/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 25890)
    /apex/com.android.adbd/lib64/libbase.so (android::base::LogMessage::~LogMessage()+352, pc 24d90)
    /apex/com.android.adbd/bin/adbd (adbconnection_listen(void (*)(int, ProcessInfo))+1620, pc d3af4)
    /apex/com.android.adbd/bin/adbd (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, init_jdwp()::$_0> >(void*)+168, pc d0d88)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc db00c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 6fd30)
```

**Comment by muhomorr** [comment] 2023-11-28 18:21
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2724

**Closed by muhomorr** 2023-11-28 18:21 UTC
