### ISSUE TITLE
Greyscale can't be turned off (work around)

### ISSUE THREAD

**Issue by Swoooshhh** [GrapheneOS/os-issue-tracker#1997] opened 2023-03-07 00:53 UTC
When I use greyscale I can't turn it off unless I reboot the phone usually, but I found a work around so maybe this is helpful to finding out the issue.

I can turn greyscale on and off when nightlight is enabled, but if it isn't enabled then I can only turn greyscale and and it doesn't turn off unless I enable nightlight first.

Here's a demonstration

Edit: well it seems like screen recording doesn't capture color filters

**Comment by r3g-5z** [comment] 2023-03-07 01:37
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/1437

If you have a workaround, share it there.

**Closed by r3g-5z** 2023-03-07 01:37 UTC
