### ISSUE TITLE
2nd Pixel 5 phone with same issues

### ISSUE THREAD

**Issue by VulcanElf** [GrapheneOS/os-issue-tracker#1349] opened 2022-07-29 21:21 UTC
Ih previously reported an issue, the other day, regarding app crashes, etc after switching to beta release channel... It was presumed the issues stopped with removal of work profile, and/or hardware issues.

Unfortunately, I was able to replicate these issues.  Even more importantly, phone calls, on both pixels, both with beta release channels, are unable to answer incoming phone calls (eventhough there is a Ringtone). There is no notification for incoming calls/who is calling... After call in not able to be answered, there is a call log for the missed calls.

Both GSF dependent apps and non GSF apps crash shortly after booting (aside from AOSP keyboard and Vanadium browser).

There is no work profile and no administrative apps.

I have the latest beta release on both Pixel 5's (SQ3A.220705.003.A1.2022072700)

I have attempted to uninstall/reinstall all GSF/GPS/PlayStore apps with no success at changes.

**Comment by thestinger** [comment] 2022-07-29 22:57
You need to reinstall the apps depending on Play services after reinstalling Play services.

Phone call issues are unrelated.

**Comment by VulcanElf** [comment] 2022-07-29 22:58
Both Pixel5 Phones have the same issue.  I will follow your instructions and report back.  NOTE: Non GSF apps crash immediately

**Comment by thestinger** [comment] 2022-07-29 23:03
This is a configuration issue. You've done something on both devices to cause this. You'll need to start by using the reset app preferences feature in the Settings app to undo all your changes to app permissions / special access and other OS settings. This won't lose any app data.

Remove any accessibility service too.

**Comment by thestinger** [comment] 2022-07-29 23:38
The issue is likely that you disabled Network for Play services which isn't working well anymore on the latest release. It will be fixed with the next one. No issue was reported to us with enough details to know anything was wrong while the release was in Beta for 48 hours.

**Closed** 2022-07-29 23:38 UTC

**Comment by VulcanElf** [comment] 2022-07-30 00:10
NOTE: I have not changed any settings on the first phone, with issues, since Feb 2022.
The ONLY change I have made, recently, was switching to Beta Release.

**Comment by VulcanElf** [comment] 2022-07-30 00:15
I will create a secondary profile, with no Google services, again, and have retained bug information. 
NOTE: non GSF reliant apps have the same issues with NO Google apps enable from GOS's "App"

**Comment by thestinger** [comment] 2022-07-30 00:55
I gave you the reason.
