### ISSUE TITLE
Keyboard crashing when typing fast in various apps

### ISSUE THREAD

**Issue by LunchBoxC** [GrapheneOS/os-issue-tracker#2650] opened 2023-11-04 07:54 UTC
When typing too fast the keyboard crashes and then reloads.  Verified in various apps (Signal, Brave, Messages app etc.)

I made sure I'm using the latest app versions.

English US Keyboard

Region: Canada (If that makes a difference)

Phone: Pixel 7a

**Comment by pxlkng** [comment] 2023-11-09 02:14
This happens for me since the 2023103100 release too. I use multiple languages in the Keyboard and which one is selected doesn't appear to influence the behavior. Also it feels like its not necessarily fast typing overall, but rather a combination of typing for a longer time and pressing multiple keys in quick succession in the moment it happens.

Additionally I observed that after this happened, in the current open app in which was typed, the back swipe gesture doesn't work anymore. neither go back in the app, nor exit the app to the homescreen. Leaving the app to the homescreen and coming back fixes the behavior of the back swipe gesture.

Pixel 7a
UP1A.231105.003.2023110700

**Comment by randomgosuser** [comment] 2023-11-09 16:01
This is also happening to me on Pixel 6a, Alpha Channel, build UP1A.231105.003.2023110700, main user, secondaty users turned off, default Launcher app and AOSP keyboard.
"Additionally I observed that after this happened, in the current open app in which was typed, the back swipe gesture doesn't work anymore. neither go back in the app, nor exit the app to the homescreen. Leaving the app to the homescreen and coming back fixes the behavior of the back swipe gesture." ---> the exact same thing is happening to me as well. 
Recorded in WhatsApp, Telegram and FairEmail.

**Comment by 54D-R0807** [comment] 2023-11-09 16:06
Same here. Cannot give any note info, than the previous commenters.
If you need logs etc. let me know.

**Comment by randomgosuser** [comment] 2023-11-09 16:11
@54D-R0807 can you please provide your phone model, release channel and build version? thanks

**Comment by 54D-R0807** [comment] 2023-11-09 16:27
Model: Pixel 6
Release Channel: Stable
Build Version: UP1A.231105.003.2023110700

**Comment by 54D-R0807** [comment] 2023-11-09 21:14
By the way ai switch between German and English keyboard quiet frequently, too. And I type quiet fast.

Is there anything else I can provide?

**Comment by sn4201** [comment] 2023-12-02 00:13
Also happening here on pixel 7 latest stable release 

UP1A.231105.003.2023112900

**Comment by thestinger** [comment] 2023-12-11 08:50
Is this still an issue on the latest releases?

**Comment by 54D-R0807** [comment] 2023-12-11 08:58
I'm on 2023120800, too and my keyboard still crashes. Is there anything I/we can do, to further assist you?

**Comment by randomgosuser** [comment] 2023-12-11 10:10
Hi @thestinger, here's a quick recap of the issue, I hope it helps you and the rest of the team.
- I am on Pixel 6a, Alpha channel, build number UQ1A.231205.015.2023120800
- this has started happening to me a couple of builds into Android 14 (so during the first week of the OS being out)
- since then, despite all the various patches the issue has stayed. Even A14 QPR1 did not fix it
- this is the issue: while the on screen keyboard is up, it quickly closes for like a second and then it opens up again. After this happens, the back gesture navigation no longer works until you go back to the home screen
- the title says this happens when typing fast, but while this was my initial impressiona as well, after some testing I can say that (at least on my end) the only thing needed to trigger it is leaving the keyboard open on screen for a while. After like 5 minutes, even if not used, the issue happens (keyboard closing for a sec and back gesture not working)
- I have tried using three-button navigation for a while and this still happens, but the back button still works in this case, so there's no impact on functionality (excluding the fact that having the keyboard randomly closing can mess up your typing)
- this is constant across all apps, even system ones
- easy workaround: as soon as this happens, just swipe up to go home and then immediately reopen the app. This restores back gesture functionality and lets you keep your work/previous typing (unless you changed some settings in your phone)
- I have yet to test different keyboards other than the default AOSP one, so I will now do that and update this post accordingly
- if other people in this thread have experienced this issue in way different than mine it might be helpful if you shared it, so that we have more info on it
Thanks

**Comment by LunchBoxC** [comment] 2023-12-11 10:14
I prefer the 3 button navigation at the bottom of my screen rather than gestures.  These all work when the keyboard crashes and re-opens.  Just wanted to add that in case it helps pin down where the problem is.   

I had initially titled it "... While typing fast" because that is the only way I saw this happen. When I typed more slowly and shorter messages it didn't seem to happen.

Thanks for contributing to my thread.

**Comment by randomgosuser** [comment] 2023-12-11 15:30
Update: I have been using other keyboards (not the AOSP default one) all day and I ran into the issue zero times. The keyboards I used are Simple Keyboard (I know the project sold to ZipoApps and has to be avoided, but the old F-droid apk is still safe and works for now) and Gboard, and never experienced a single crash (even through multiple reboots).
So @thestinger I think that at this point it is safe to assume this is AOSP keyboard related, unless someone else in this thread has experienced this with other keyboards. This would also explain why I was able to find 0 mentions of this happening in stock OS since Android 14 dropped on Google Pixel.
So, for now, if this really bothers you just know that switching keyboard fixed this for me (at least for now).

**Comment by randomgosuser** [comment] 2023-12-11 15:52
> We need someone to get a crash log to have any hope of resolving it. Please reboot, then trigger the crash, then send a bug report to [contact@grapheneos.org](mailto:contact@grapheneos.org) captured via developer tools and mention keyboard crash in email subject.

The problem is that the app never really crashes, we don't get an error message on anything, the keyboard simply minimizes just like if you manually pushed "back" when the keyboard is up, and then after less than a second it goes back to its initial state. Is there a way to collect app specific logs even if an app never crashes? Thanks Daniel btw

**Comment by thestinger** [comment] 2023-12-11 16:53
It sounds like it's crashing and being automatically reopened. By default, app crashes don't get reported the first time they happen.

**Comment by thestinger** [comment] 2023-12-11 17:20
It is probably a crash with a crash log which can be obtained via capturing a bug report zip in developer options and emailing it to us. It would be helpful if multiple people could do that. Please try to do it as soon as possible after rebooting to minimize the other noise in the logs.

**Comment by randomgosuser** [comment] 2023-12-11 17:28
Ok, will try to do that. Do you recommend interactive report or full report? thanks

**Comment by LunchBoxC** [comment] 2023-12-11 17:43
My keyboard crashes way more frequently than what I'm seeing in this conversation.  I've just rebooted my phone and will capture a log and send to the email address.   Could someone tell me what to select in Developer options to get that log?

**Comment by thestinger** [comment] 2023-12-11 17:49
Capture bug report at the very top

**Comment by LunchBoxC** [comment] 2023-12-11 17:57
Thanks @randomgosuser for the steps... I got my keyboard to crash on my Pixel 7a and have submitted a Full bug report to the email address above from @thestinger ....

Best of luck hunting this bug down.

**Comment by LunchBoxC** [comment] 2023-12-11 18:03
I'm ok to put up with it... It's just annoying not a huge deal because on my Pixel 7a the keboard loads back up rather quickly.  I'd rather that than put anything Google on my phone I don't need like Gboard.  No tentacles in my device please from the Evil Corp.  Hahahahaha

**Comment by randomgosuser** [comment] 2023-12-11 18:06
> I'm ok to put up with it... It's just annoying not a huge deal because on my Pixel 7a the keboard loads back up rather quickly. I'd rather that than put anything Google on my phone I don't need like Gboard. No tentacles in my device please from the Evil Corp. Hahahahaha

Ok fair enough, I appreciate your mindset ;) (I think we more or less hate google, since we're here lol). Best of luck in the meantime!

**Comment by LunchBoxC** [comment] 2023-12-11 18:07
@randomgosuser Thanks again for taking the time to teach me about the bug report and how to do it, that way if I encounter future problems I can contribute the information needed to help this project.

**Comment by thestinger** [comment] 2023-12-11 18:07
If people send us bug report zips, we can probably fix it.

**Comment by LunchBoxC** [comment] 2023-12-17 18:13
I downloaded Openboard using F-Droid and have been using it for the last week.  It's a free and opensource keyboard that is far better than the included AOSP keyboard.  I have experience no crashes using this keyboard so it's definitely something in the AOSP keyboard that is the bug.  Just wanted to include this here to help pinning down the issue.

**Comment by Harrier-Du-Bois** [comment] 2023-12-24 10:18
Hi fellow keyboard sufferers and Devs,

just wanted to add my findings:

Using a 7a I pretty much get the same issue as described by others, aosp keyboard app crashing in multiple apps, afterwards back swipe not working.

The one thing I noticed when looking into this was that the kb app appears to be using a lot of RAM at times.

Now, I do use several languages and have the spelling checks and extended dictionaries for those installed, but when I checked RAM usage after this bug started happening, it said that the keyboard had peaked at 1.7 GB. Don't know if that's within the expected range, to me it feels like a lot for a basic app like a keyboard.

When I checked RAM usage again just now it wasn't that high but it still had peaked at about 400 MB over the past 24 hrs.

I did create a log some time ago and can create a fresh one if required.

Thanks for looking into what appears to be an Android/AOSP issue.

Happy holidays to all of you.

**Comment by LunchBoxC** [comment] 2023-12-24 15:07
@Harrier-Du-Bois Since switching to Openboard which I downloaded through F-Droid I have had 0 crashes.  Just if you want something in the meantime.  It supports multiple languages as well.  It also has a lot of nice features that you can toggle on/off as well.

**Comment by thestinger** [comment] 2023-12-25 13:43
We're working on it.

**Comment by thestinger** [comment] 2023-12-30 18:05
Resolved for upcoming OS release.

**Closed** 2023-12-30 18:05 UTC
Labels: bug, priority-max
