### ISSUE TITLE
Camera Crash

### ISSUE THREAD

**Issue by neffatomic** [GrapheneOS/os-issue-tracker#2878] opened 2023-12-16 16:06 UTC
Camera failed using the WhatsApp camera feature

```
type: crash
osVersion: google/panther/panther:14/UQ1A.231205.015/2023121200:user/release-keys
uid: 1000 (u:r:hal_camera_default:s0)
cmdline: /apex/com.google.pixel.camera.hal/bin/hw/android.hardware.camera.provider@2.7-service-google
processUptime: 0s

abortMessage: Timed out on NotifyCaptureSessionOpen

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: camera.provider

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 62e64)
    /system/lib64/liblog.so (__android_log_default_aborter+12, pc 63ec)
    /apex/com.android.vndk.v34/lib64/libbinder.so (android::base::LogMessage::~LogMessage()+352, pc b1cc0)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc 3c790c)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc 3c28b8)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc 3c24a4)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc 3bebd0)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc 33fbf8)
    /apex/com.google.pixel.camera.hal/lib64/libgooglecamerahal.so (android::google_camera_hal::CameraDevice::CreateCameraDeviceSession(std::__1::unique_ptr<android::google_camera_hal::CameraDeviceSession, std::__1::default_delete<android::google_camera_hal::CameraDeviceSession> >*)+80, pc 348c0)
    /apex/com.google.pixel.camera.hal/bin/hw/android.hardware.camera.provider@2.7-service-google (pc 1504c)
    /apex/com.google.pixel.camera.hal/lib64/android.hardware.camera.device-V2-ndk.so (aidl::android::hardware::camera::device::_aidl_android_hardware_camera_device_ICameraDevice_onTransact(AIBinder*, unsigned int, AParcel const*, AParcel*)+408, pc 186f8)
    /system/lib64/libbinder_ndk.so (ABBinder::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+140, pc d0bc)
    /system/lib64/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+304, pc 74b00)
    /system/lib64/libbinder.so (android::IPCThreadState::executeCommand(int)+1016, pc 5ed78)
    /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+160, pc 5e8c0)
    /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+112, pc 5f210)
    /apex/com.google.pixel.camera.hal/bin/hw/android.hardware.camera.provider@2.7-service-google (pc 3197c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+104, pc 5a718)
```

**Comment by muhomorr** [comment] 2024-01-18 09:13
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/3057

**Closed by muhomorr** 2024-01-18 09:13 UTC
Labels: bug
