### ISSUE TITLE
Play service crash

### ISSUE THREAD

**Issue by badmannen** [GrapheneOS/os-issue-tracker#3574] opened 2024-05-27 23:14 UTC
```
type: crash
osVersion: google/cheetah/cheetah:14/AP1A.240505.005/2024052100:user/release-keys
package: com.google.android.gms:241757038
process: com.google.android.gms.persistent
processUptime: 40278858 + 333 ms
installer: com.android.vending
GmsCompatConfig version: 113

java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@ea67ad54: GattService registerServer
	at com.android.bluetooth.Utils.checkPermissionForDataDelivery(Utils.java:563)
	at com.android.bluetooth.Utils.checkConnectPermissionForDataDelivery(Utils.java:595)
	at com.android.bluetooth.gatt.GattService.registerServer(GattService.java:4510)
	at com.android.bluetooth.gatt.GattService$BluetoothGattBinder.registerServer(GattService.java:1274)
	at com.android.bluetooth.gatt.GattService$BluetoothGattBinder.registerServer(GattService.java:1262)
	at android.bluetooth.IBluetoothGatt$Stub.onTransact(IBluetoothGatt.java:1203)
	at android.os.Binder.execTransactInternal(Binder.java:1530)
	at android.os.Binder.execTransact(Binder.java:1464)
	Suppressed: ejjy: 
		at tk_trace.nearby-ManualRadioStateReceiver_onReceive(Unknown Source:0)
Caused by: buqk
	at buqp.a(:com.google.android.gms@241757038@24.17.57 (190400-633823513):3)
	at buqq.a(:com.google.android.gms@241757038@24.17.57 (190400-633823513):3)
	at burr.execute(:com.google.android.gms@241757038@24.17.57 (190400-633823513):5)
	at com.google.android.gms.nearby.mediums.bluetooth.BluetoothRadio.b(:com.google.android.gms@241757038@24.17.57 (190400-633823513):5)
	at com.google.android.gms.nearby.mediums.bluetooth.BluetoothRadio$1.a(:com.google.android.gms@241757038@24.17.57 (190400-633823513):8)
	at com.google.android.gms.libs.punchclock.tracing.TracingBroadcastReceiver.onReceive(:com.google.android.gms@241757038@24.17.57 (190400-633823513):17)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1810)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$mcNAAl1SQ4MyJPyDg8TJ2x2h0Rk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

**Comment by muhomorr** [comment] 2024-05-28 05:07
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/3564

**Closed by muhomorr** 2024-05-28 05:07 UTC
