### ISSUE TITLE
Pin scrambling not enabled on profile swap

### ISSUE THREAD

**Issue by bootlesshacker** [GrapheneOS/os-issue-tracker#1421] opened 2022-08-25 21:05 UTC
When ending session on a profile without pin scrambling and attempting to login to primary profile again which has pin scrambling, pin scrambling does not seem to be enabled until after first unlock. Only observed since upgrading to 13 but not sure if issue on 12.

**Comment by bootlesshacker** [comment] 2022-08-25 21:07
TP1A.220624.021.2022082400

**Comment by andre4ik3** [comment] 2022-09-03 21:07
Yes, it was an issue on 12. Happened to me frequently. Sometimes it also happens in reverse: the profile without pin scrambling gets it. Sometimes the buttons collapse vertically (i.e. vertical spacing between them gets reduced to none), but in Android 13 instead of that, the buttons become pill-shaped. It's weird.

**Comment by inferenceus** [comment] 2023-02-26 15:56
Noticed same issue months ago. Has now become an issue since beginning to use PIN scrambling more aggressively across profiles. Upon profile switch, PIN scrambling not enabled on lockscreen despite being enabled in profile settings.

**Comment by andre4ik3** [comment] 2023-03-01 20:53
Hasn't had this issue once since upgrading to P7. Could be a P6 bug?

**Comment by r3g-5z** [comment] 2023-03-01 20:56
There's no evidence this is a device-specific issue. It's consistently reproducible on emulator. The problem is the way PIN scrambling was originally implemented.

**Comment by inferenceus** [comment] 2023-03-01 23:12
This occurred for me on both Pixel 4a (5G) and currently Pixel 6. Not device-specific.

**Comment by rustybird** [comment] 2023-03-03 14:02
Could this have the same root cause as #1420 ("Double-line clock setting does not persist across profile change")? Maybe it's not a bug in the PIN scrambling feature, but rather Android isn't properly refreshing all lock screen components after a profile switch.

**Comment by r3g-5z** [comment] 2023-03-14 11:33
Fixed in latest GrapheneOS release and now extends PIN scrambling to SIM PUK/PIN.

**Closed by r3g-5z** 2023-03-14 11:33 UTC
Labels: bug
