### ISSUE TITLE
eSIM activation support and configuration

### ISSUE THREAD

**Issue by ProactivePhilomath** [GrapheneOS/os-issue-tracker#159] opened 2019-11-21 22:07 UTC
I'm creating this issue to discuss and track the implementation of eSIM support in GrapheneOS.

This would be an enhancement for Pixel models 3, 3 XL, 3a and 3a XL.

**Comment by DC7IA** [comment] 2019-12-25 22:42
Out of curiosity: What would need to be done for that?

Isn't that something available as source code?

**Comment by thestinger** [comment] 2019-12-25 23:34
That's unknown at this point. Part of working on this is initial research into what would need to be implemented, what's already present, etc. and so far no one has shown interest in taking it on.

**Comment by wertyy102** [comment] 2020-02-27 20:09
I'm going to do some reading today into eSIM support, as this is pretty much a requirement for me to switch, and I finally have some time away from other projects of mine

**Comment by wertyy102** [comment] 2020-02-27 20:10
https://source.android.com/devices/tech/connect/esim-overview here is the documentation on the eSIM technology from AOSP.

**Comment by wertyy102** [comment] 2020-02-27 20:15
So it appears that you will need carrier applications to activate the eSIM technology, so yes one could work on adding support, but then it becomes your carrier's job to make it "Just Work"

I'm going to work on adding it to the requisite areas, and submit.  We will see if it gets approved.

**Comment by wertyy102** [comment] 2020-03-02 07:50
Alright, I can't make hell nor high water of how to insert the eSIM listener, so I'm going to have to set this down.

**Comment by DC7IA** [comment] 2020-03-29 11:07
Looking at the changelog of CalyxOS, I discovered they support eSIM.

https://gitlab.com/calyxos/calyxos/-/blob/master/changelogs/2020.02.11.10.md

Maybe this helps somehow in integrating it within GrapheneOS..?

**Comment by thestinger** [comment] 2020-04-09 17:42
@DC7IA Contributors still need to step up and start working on this. Looking into what CalyxOS has done to support this would be a good starting point. There will be no progress on this (or other features) until developers step up to start working on it. This isn't within the scope of what I work on, so depending on me to get around to it means that it will NEVER be implemented.

**Comment by daradib** [comment] 2020-06-30 21:05
It looks like CalyxOS bundles two priv-apps for eSIM support - com.google.android.euicc and com.google.euiccpixel:
https://gitlab.com/calyxos/vendor_android-prepare-vendor/-/commit/e3fb9d63c36c9f93dee6baad566e79bb960a8fe1
https://gitlab.com/calyxos/device_google_crosshatch/-/commit/515fcef76810e2b64eb7b44eda2d30a47e5482d7

I don't use eSIM, so I won't be able to test whether these changes are sufficient. I also don't know the privacy implications of bundling these apps, nor whether they in turn depend on some implementation of Play Services (CalyxOS includes microG).

**Comment by freddytuxworth** [comment] 2020-07-01 00:55
A starting point/useful reference for an OSS implementation might be these Truphone repositories that implement at least some parts of the LPA and a UI for setup:
 - [LPAD-React](https://github.com/Truphone/LPAD-React)
 - [LPAd_SM-DPPlus_Connector](https://github.com/Truphone/LPAd_SM-DPPlus_Connector/)
I'm not sure how complete they are though.

**Comment by jarrettlenox** [comment] 2020-12-30 04:20
Forgive me if it's not my place to chime in because I'm not an android developer, but I landed on this page because I was looking for a way to remove an installed eSIM (Google Fi) from a Pixel 4a. I forgot to remove it before I flashed GrapheneOS and then couldn't figure out how to remove it from GrapheneOS. Maybe there's a way that I missed, or another app that can, maybe it's because the API hasn't been implemented, I dunno. I did read through this page, https://source.android.com/devices/tech/connect/esim-overview, and while it's over my head, it got me thinking that it would be nice if it was possible to at least manage(remove) carrier-installed eSIMS from within GrapheneOS. I ended up re-flashing the factory image, using the reset options in system settings (this didn't work in GrapheneOS), and then re-flashing. Cheers and many thanks to all of the devs that make Graphene possible. It's great!

**Comment by codebam** [comment] 2020-12-30 22:11
On my Pixel 3a I was able to setup eSIM on the stock factory image, then flash to GrapheneOS and enable D2DS (*#*#INFO#*#* in dialer). After rebooting with D2DS enabled I was able to get a signal using the already installed eSIM.

**Comment by thestinger** [comment] 2020-12-30 22:38
The issue is not having an app for registration / configuration, not lack of OS support.

**Comment by thestinger** [comment] 2020-12-30 22:39
Including the Google apps for this isn't an option. They're proprietary Google apps using Google services and with a hard dependency on Play services.

**Comment by codedump** [comment] 2021-01-22 14:45
> On my Pixel 3a I was able to setup eSIM on the stock factory image, then flash to GrapheneOS and enable D2DS (`*#*#INFO#*#*` in dialer). After rebooting with D2DS enabled I was able to get a signal using the already installed eSIM.

Also works on Pixel 4a and GrapheneOS of 2021-01-05. Thanks for the hint :-)

(For clarity, for other lurkers, here the steps explicitly: Install (google) stock ROM, set up eSIM, flash GrapheneOS as per installation guide, then enable D2DS using "*#*#INFO#*#*").

**Comment by codethief** [comment] 2021-03-13 20:42
@codebam @codedump Does your eSIM also work in combination with a physical SIM, i.e. in dual-SIM (DSDS) mode?

**Comment by codedump** [comment] 2021-03-14 13:20
@codethief Yes, dual-sim works. I'm using it actively.

**Comment by mostafafahim** [comment] 2021-03-28 17:55
Sorry, but how to enable (D2DS) mode?

**Comment by TestUserfqgn** [comment] 2021-04-01 11:51
@codedump @codedieum I have the same issue. How to proceed?

**Comment by codedump** [comment] 2021-04-01 19:29
@codedieum You're on the right path, that's a menu. Click on "Phone information" and then scroll down to "Enable DSDS" (about mid-page).

Cheers

**Comment by TestUserfqgn** [comment] 2021-04-01 20:02
@codedump Thanks!

**Comment by codethief** [comment] 2021-04-04 02:29
> > On my Pixel 3a I was able to setup eSIM on the stock factory image, then flash to GrapheneOS and enable D2DS (`*#*#INFO#*#*` in dialer). After rebooting with D2DS enabled I was able to get a signal using the already installed eSIM.
> 
> Also works on Pixel 4a and GrapheneOS of 2021-01-05. Thanks for the hint :-)
> 
> (For clarity, for other lurkers, here the steps explicitly: Install (google) stock ROM, set up eSIM, flash GrapheneOS as per installation guide, then enable D2DS using `*#*#INFO#*#*`).

I can confirm that it also works on the Pixel 5 and GrapheneOS 2021.03.19, including dual SIM.

PSA: I made the mistake of hitting the "disable SIM" toggle for the eSIM in the network settings. (My plan was to disable the eSIM for a second to see whether the physical SIM is fully functional, too.) Unfortunately, the eSIM then disappeared completely and it seems there is no way of undoing this, short of re-flashing GrapheneOS. (I tried disabling and re-enabling DSDS, among other things.) So be careful. :)

**Comment by SatelliteSnyper** [comment] 2021-04-30 15:05
I would like to put up 0.2 BTC as bounty [== $11000] for development of eSIM support / LPA without needing to use stock Google Android.

Is it OK to send to the GrapheneOS donation address for escrow?

**Comment by SatelliteSnyper** [comment] 2021-04-30 17:09
If escrow is not possible I can hold onto it, OK for me 😎. Was just trying to prove that I'm not going to stiff the developers on the payment.

**Comment by SatelliteSnyper** [comment] 2021-04-30 21:05
Proof of solvency (for bitcoin-qt - File - Verify message)

* Address: [`1NVsJfnZYmcrw7x49VqYCmmwgwBazoqekB`](https://blockstream.info/address/1NVsJfnZYmcrw7x49VqYCmmwgwBazoqekB)
* Message: `Bounty for eSIM support https://github.com/GrapheneOS/os-issue-tracker/issues/159 @SatelliteSnyper`
* Signature: `H6hmf7ugBz+8cRPPPa8BEId8wkKk821veIK58wDJkmd5fC0i4YGfPpw8UiMpvG+Ty+lmbPPDfHcnaPgAgXJdlz0=`

**Comment by 857GIT** [comment] 2021-05-01 09:12
Can anybody confirm that does DSDS function work on Pixel 3? I managed to add physical SIM and eSIM but I cant use them at the same time. This was the main reason I chose this phone so at the moment I am quite pissed.

At the *#*#INFO#*#* menu I have phone information but cant find the DSDS enabling option. Thou I have it in my own language and it could have been translated to something weird. I have option "Enable operator (or carrier) control" but nothing happens if I press that button. I doubt its that....

Seems like Pixel 3a, 4a and 5 has this feature but any else Pixel phone?

**Comment by Lackshan** [comment] 2021-05-06 18:45
@SatelliteSnyper @thestinger I've done a little research into eSIM support. It appears that an LPA needs to be created. This is a system app that handles communication between the eUICC (eSIM) chip and the carrier's servers (SM-DP+).  

Additionally, an LPA UI or Carrier App must be created in order to install/manage subscription profiles.

I'm happy to take a crack at this but I've been unable to find a contributors guide (sorry!). Anyone mind linking me to it?

**Comment by Lackshan** [comment] 2021-05-12 21:59
An update: I've setup my AOSP/GOS build environment and ordered a Pixel 4a to use for testing. I've started work on the LPA but I'll only know if it works once I get my test device. It should arrive within the next week.

**Comment by SatelliteSnyper** [comment] 2021-06-22 19:39
@Lackshan

Can we do something to help you?

If you have done partial work but you can not continue, I'll surely make a partial payment when you upload it for other developers to follow in your footsteps.

**Comment by Juretsky** [comment] 2021-06-23 18:52
> On my Pixel 3a I was able to setup eSIM on the stock factory image, then flash to GrapheneOS and enable D2DS (`*#*#INFO#*#*` in dialer). After rebooting with D2DS enabled I was able to get a signal using the already installed eSIM.

Thanx! On the Pixel 3A XL it works!

**Comment by Lackshan** [comment] 2021-06-23 20:56
@SatelliteSnyper Sorry for not updating you sooner. Yes, I have hit an obstacle. The first one is that PackageManager reports that my Pixel 4a does not have the FEATURE_TELEPHONY_EUICC feature and I am unsure how to get it to work. If someone can help me figure this out, I'll be able to resume development.

I'll upload everything I have this weekend once I'm free.

**Comment by thestinger** [comment] 2021-06-23 22:28
You have to enable the feature via the usual feature configuration if you're providing it. You can look at how that's done in ProtonAOSP in the device repositories.

**Comment by moodguru-arch** [comment] 2021-06-29 20:52
I'm unable to contribute to this on a technical level but I'm happy to offer any testing on my GOS pixel 5 if this helps.

**Comment by beaking96** [comment] 2021-08-07 02:52
Is anyone brave enough to try airplane mode with the esim?

**Comment by codedump** [comment] 2021-08-07 06:31
> Is anyone brave enough to try airplane mode with the esim?

Err, with release GrapheneOS? Yes. I'm doing it all the time. Seems to work (i.e. the signal strength bars disappear, for both the esim.and the regular sim). I haven't gotten into any more detailed investigation, but if there's anything you want me to try, I'll be happy to oblige :-)

**Comment by orgua** [comment] 2021-08-22 13:50
now that GrapheneOS got the sandboxed playservices, would it be possible to integrate the apps that can transfer the SIM to eSIM?

**Comment by thestinger** [comment] 2021-08-22 15:36
We aren't integrating privileged Google apps/services into the OS.

**Comment by Lackshan** [comment] 2021-08-23 07:40
@thestinger Do you mean this file: https://github.com/ProtonAOSP/android_device_google_sunfish/blob/57b74a5c4d99fd73cb1b3fdf144ef405afd9600c/overlay/frameworks/base/core/res/res/values/config.xml ?

Because GOS appears to use a similar config and I can't see how ProtonAOSP has enabled EUICC.

**Comment by thestinger** [comment] 2021-08-23 11:02
No, I don't mean that.

This issue should only be used to discuss implementing an eSIM activation app for GrapheneOS.

**Comment by kalGITHUB** [comment] 2021-08-27 23:55
> https://github.com/ProtonAOSP/android_device_google_sunfish/blob/57b74a5c4d99fd73cb1b3fdf144ef405afd9600c/overlay/frameworks/base/core/res/res/values/config.xml

> `    
    <string-array translatable="false" name="config_telephonyEuiccDeviceCapabilities">
        <item>"gsm,11"</item>
        <item>"utran,11"</item>
        <item>"cdma1x,1"</item>
        <item>"hrpd,3"</item>
        <item>"ehrpd,12"</item>
        <item>"eutran,11"</item>
    </string-array>`

Lines 324 is what you're lookin for?

I'm about to try to manually install various system apps from the Pixel 5 Redfin Image related to SIM management, EUICC, connectivity, etc. on GOS until I get it to work. MTF

**Comment by thestinger** [comment] 2021-08-27 23:56
It likely has to be a privileged app built into the OS. That's the problem.

**Comment by kalGITHUB** [comment] 2021-08-28 06:32
Just to add context to the low hanging fruit options.

First thing I did was install the Google Services Compatibility Layer provided by Daniel.

Then, I installed the following apps pulled from my updated Pixel 5 using using AEE (APK Explorer and Editor) from F-Droid:

Adaptive Connectivity Services.apk
Carrier Provisioning Service.apk
Carrier Services.apk
Carrier Settings.apk
Carrier Setup.apk
com.android.connectivity.metrics.App.apk
Google Connectivity Services.apk
Google Fi.apk
Google Fi Support.apk
SIM Manager.apk
SIM Toolkit.apk

I gave all apps full permission and ability to change system setting if able. Still nothing happened with Google Fi activation. It kept telling me to check my settings. All this is to reinforce the importance of it being a privileged app.

![Screenshot_20210828-094648](https://user-images.githubusercontent.com/57609475/131201013-597d9fbe-a47c-496e-8539-1df2ca2f5fc7.png)

![Screenshot_20210828-094552](https://user-images.githubusercontent.com/57609475/131201021-36394fee-08d0-4549-8248-0502e9774544.png)

**Comment by kalGITHUB** [comment] 2021-08-28 08:37
Reporting unexpected behavior after I factory reset GOS.

So I'm essentially at the same state as if I have fully activated my eSIM on stock Redfin. Then flashed graphene. Turned on D2DS rebooted.

Without installing any Google anything, I can now view the Google Fi carrier settings in the Settings app. I hadn't done this before I installed Google services before. The only thing is that the status bar says I am roaming instead of saying LTE. SMS works, data works, no MMS. APN Settings are present.

There is some conflict between Google Services and the Carrier information when I have eSIM for Google Fi on GOS.

**Comment by readefries** [comment] 2021-08-31 18:52
@kalGITHUB thanks, mate! This list helped me get my eSim working by just downloading the requirements from apk mirror! I don't use Google Fi though.

1 small note, I had to enable `DSDS` not `D2DS`.

**Comment by Lackshan** [comment] 2021-09-06 13:48
@kalGITHUB Thanks! That config appears to already be in GOS though.

@thestinger I asked because I am trying to create an eSIM activation app. Also you're right, it has to be a privileged app built into the OS.

**Comment by theTaikun** [comment] 2021-09-23 20:43
Question for those who have eSIM working:
After activating eSIM and flashing GOS, is it possible to switch eSIMs? Or is that part of the activation problem that's being worked through?

**Comment by codebam** [comment] 2021-09-24 18:16
@theTaikun as far as I know you can't add more eSIMs after flasing GOS because there's no setup. You should be able to switch between existing eSIM, but I haven't tried it.

**Comment by mrmcan** [comment] 2021-10-08 05:57
Is there any update mates? I need that feature but I don't want to use stock image then flash. It's not a good way to make something work. We should be able to do it in GOS directly.

Any good news would be amazing!

**Comment by thestinger** [comment] 2021-10-08 06:05
If there's news it will be posted here. Don't need to ask about it.

**Comment by mrmcan** [comment] 2021-10-08 06:07
What is priority of that feature? I would like to be do good donation as Snyper did. I cant use my GOS because of no esim support. As a digital nomad, its an important feature for me.

**Comment by ivenprillwitz** [comment] 2021-10-21 06:37
> 
> 
> Deleting it will be supported in Android 12.

Updated to Android 12 Beta.  I dont see the option to add a esim.

**Comment by thestinger** [comment] 2021-10-21 06:44
There's still no activation app but the OS supports it and deletion is now available. That's progress.

**Comment by motojojo615** [comment] 2021-11-04 19:53
Just wanting to keep this issue visible.
The menu for the eSIM used to be visible, but I guess something in one of the recent updates got rid of it...?

**Comment by NewRedsquare** [comment] 2021-11-04 21:23
> Just wanting to keep this issue visible. The menu for the eSIM used to be there, but I guess something in one of the recent updates got rid of it...?

Yup, the only way to edit **some** settings of the eSim is by doing *#*#4636#*#* and selecting the eSim profile :(

**Comment by ATGUAG** [comment] 2021-11-15 11:33
Is this project related to the current issue? 
https://github.com/Truphone/LPAd_SM-DPPlus_Connector

**Comment by thestinger** [comment] 2021-11-15 17:14
That looks like it could be what we need when combined with the other repositories. Someone would need to figure out how to fully integrate it and set it up.

**Comment by satrinity402** [comment] 2021-12-02 19:11
eSIM support would be awesome!

**Comment by FreemanJones** [comment] 2022-01-14 22:01
Hey all, 
I have signed up an account just to respond to this as a total "novice know nothing" who was reading along here hoping to get a solution and appear to have completely by accident and inexplicably solved the issue with no knowledge of how or what made it possible (given I have missed a bunch of steps you have discussed and have zero idea how it is even technically possible that this is working now!?). 

I now have a fully functional esim loaded. Here is my config and here is what I have done - again don't ask me to explain my logic or anything technical, I have absolutely no idea and have somehow stumbled onto this with zero understanding:

In case it matters: 

I am in Australia on Telstra network
I transfered my phone number which was on a traditional plastic sim card in an iPhone to an esim service onto the Pixel 6 Pro whilst using the factory google pixel 6 pro ROM. This involved downloading the MyTelstra app via google play store to do this. 

The esim service had not provisioned properly though - was getting error saying it wasn't working (I can't even remember the actual error message now that's how little attention I was paying!). 

Before bothering fixing the issue, I assumed that the esim was loaded on the phone and that it was a carrier issue, just delayed provisioning maybe... so I flashed GOS and then immediately setup a second profile that is "googleafied" - basically the second profile is setup with all of googles play services etc but it is sandboxed from the primary profile? 

I then went back to the primary profile, which was still completely stock and untouched apart from allowing multiple profiles toggle set. 

I downloaded aurora store and downloaded the mytelstra app - and I should mention I was getting the same sim service error notification as before on the stock pixel os at this point. 

I then allowed dsds as per the steps above and rebooted phone. 

I then requested a reconfigure on the mytelstra app of the esim to the device I was using (now which was GOS, primary profile completely stock apart from the above mentioned) 

Nothing exciting happened in 30seconds so being the impatient person I am, I kicked the cat and repeated the esim service setup request as above. This time I got an error message saying that the original request had not yet been provisioned and that I would get a notice when it was and then I could start a new request. 

30 seconds later, my iphone (still with original sim card in it and still with active service working) rang for a business call - half way through the call it dropped out and i panicked briefly as i realised my service had now been transferred off the plastic sim to the non working esim and thought i was screwed as it is my business number... Then whilst holding my iPhone in my hand looking for something to throw it at in panic, my pixel with graphineos came to life as the caller phoned me back after our original call dropping out and the whole thing is working. 

I have tested data, imcomming and outgoing calls, MMS is sent through data for me anyway due signal messenger and from all I can see, the phone and esim is fully functional. 

I am about to try putting my second number into the physical sim tray now and see if both numbers get service. 

Will update shortly.

**Comment by t-8ch** [comment] 2022-02-12 09:33
It seems the published LPA from Truphone is fairly incomplete. For example the "LPAd Android" repository is missing.
(Also mentioned at https://github.com/Truphone/LPAd_SM-DPPlus_Connector/issues/2 without an answer)

Also it seems that an LPA can very well run into issues with all kinds of external systems:

    If you're making your own LPA, you should go through much more rigorous testing.
    You should work with your modem vendor, eUICC chip or eSIM OS vendor, SM-DP+ vendors, and carriers to resolve issues and ensure interoperability of your LPA within the RSP architecture.
    A good amount of manual testing is inevitable. For best test coverage, you should follow the [GSMA SGP.23 RSP Test Plan](https://www.gsma.com/newsroom/wp-content/uploads//SGP.23-v1.4.pdf).

Wouldn't it be possible to run the Google LPA in a sandbox similar to the other Play components and then hook it up into the upcoming package manager?
The sandbox could include a system app as a shim that forwards its invocations to the non-privileged Google LPA.
Users could even deinstall those components after the initial setup.

**Comment by SatelliteSnyper** [comment] 2022-02-16 19:33
Bounty increased to 1 BTC [== $44000 today] for an open source activation app. Check address balance [above](https://github.com/GrapheneOS/os-issue-tracker/issues/159#issuecomment-830391832). Can it be mentioned in the issue's title to make it better visible?

I think this would help people in oppressive countries who restrict SIM card purchase but allow "foreign / tourist" (e)SIM cards.

eSIM activation also is a reason some people still need to use another OS. I'm just saying let's get that reason fixed too :sunglasses:

> Wouldn't it be possible to run the Google LPA in a sandbox similar to the other Play components and then hook it up into the upcoming package manager?

Difficult to trust a closed source Google app for this purpose! It probably submits the new activated IMSI number and so on to Google?

**Comment by thestinger** [comment] 2022-03-23 16:34
This is implemented as part of sandboxed Google Play and will be documented soon. Providing an alternative implementation is an extremely long term goal and may not ever support Pixels but rather only GrapheneOS hardware.

**Comment by thestinger** [comment] 2022-03-23 16:35
Documentation will be added in the next few days.

**Closed by thestinger** 2022-03-23 16:34 UTC
Labels: enhancement, priority-max

**Comment by ThePowerOfDreams** [comment] 2022-03-23 17:41
This doesn't seem to qualify the project for the [bounty](https://github.com/GrapheneOS/os-issue-tracker/issues/159#issuecomment-1042088066), and I note that [it has not yet been paid out](https://blockstream.info/address/1NVsJfnZYmcrw7x49VqYCmmwgwBazoqekB). @thestinger Do you foresee progress on this issue meeting the requirements to claim the bounty in the near future?

**Comment by thestinger** [comment] 2022-03-23 18:20
If it's meant to be for developing a whole alternate implementation, that's going to be way too much work for the near future and it would be better to pay someone to work on it rather than someone needing to put in a massive amount of work to write a hundred thousand lines of code and deal with complex stuff without any guarantee they get funding.

**Comment by gordonel** [comment] 2022-03-23 20:28
Maybe this would be better suited for AOSP development, or some kind of collaborative project between AOSP-based ROMs (Calyx, LineageOS, GrapheneOS etc.) with the eventual goal of making it a FOSS app that can live on F-Droid.

It's gotta be at least 1.5x less work if at least 3 teams pitch in

**Comment by gordonel** [comment] 2022-03-23 20:29
>  it would be better to pay someone to work on it rather than someone needing to put in a massive amount of work to write a hundred thousand lines of code and deal with complex stuff without any guarantee they get funding.

Where would one look for this kind of muscle?

**Comment by ThePowerOfDreams** [comment] 2022-03-23 20:30
> It's gotta be at least 1.5x less work if at least 3 teams pitch in

_The Mythical Man-Month joins the chat_

**Comment by thestinger** [comment] 2022-03-23 20:33
We won't collaborate with CalyxOS and won't add more projects to GrapheneOS where any of their developers has commit access due their underhanded and malicious behavior. We already have to rewrite/replace the backup service implementation due to them defacto taking over that project and running it into the ground.

**Comment by SatelliteSnyper** [comment] 2022-03-24 15:13
The bounty was [intended](https://github.com/GrapheneOS/os-issue-tracker/issues/159#issuecomment-1042088066) for an open source activation app. But to make things easier now I have [donated it / 0.99 BTC](https://blockstream.info/tx/7fdabaa8ea3edef52aefc6f00c6bd62f79f2b515cd0729ff1a902ca9f02c9a4a) to GrapheneOS. I understand that GrapheneOS is NOT bound by my desire to see it used for the development of an open source activation app (#1079).

I would be happy to gift the [remaining 0.01 BTC](https://blockstream.info/address/bc1q8wh2rd9weqlj39ydkr0e7qep8sqke3uaskng9v) to you @Lackshan if you post a wallet address, for the work already put in even if it didn't work out in the end (or so far... never say never :sunglasses:).

**Comment by v2g2342g4** [comment] 2022-04-08 21:12
> The bounty was [intended](https://github.com/GrapheneOS/os-issue-tracker/issues/159#issuecomment-1042088066) for an open source activation app. But to make things easier now I have [donated it / 0.99 BTC](https://blockstream.info/tx/7fdabaa8ea3edef52aefc6f00c6bd62f79f2b515cd0729ff1a902ca9f02c9a4a) to GrapheneOS. I understand that GrapheneOS is NOT bound by my desire to see it used for the development of an open source activation app (#1079).
> 
> I would be happy to gift the [remaining 0.01 BTC](https://blockstream.info/address/bc1q8wh2rd9weqlj39ydkr0e7qep8sqke3uaskng9v) to you @Lackshan if you post a wallet address, as a thank you for the work already put in (e.g.research, expenses) even if it didn't work out in the end (or so far... never say never sunglasses).

I was really thankful that you put up the 1BTC bounty on this, and I respect you for paying it out. However, I don't think you should have paid. I wouldn't have because we still require google services on the phone.... In any case, I'm hopeful someone smarter than I am will be able to support ESim without requiring us to install the playstore.

**Comment by thestinger** [comment] 2022-04-09 01:46
We consider it a donation to the project to support further development.

**Comment by geppi** [comment] 2022-04-12 11:27
It looks like it is required to have the Google PlayServices installed in the Owner Profile to enable the privileged eSIM management. Therefore if you want to be able to manage your eSIM it is not a viable option to keep the Owner Profile clean and quarantine the PlayServices into an alternate user profile.

So far I couldn't check if it would work with the PlayServices solely installed into a Work Profile of the Owner Profile.
Does somebody have it working this way?

Which of the 3 components of the sandboxed PlayServices would be required to keep it to a minimum?

**Comment by thestinger** [comment] 2022-04-12 11:30
In general, apps installed in the Owner profile don't have special capabilities. However, only the owner profile can manage eSIM configuration and this has to be there instead of another one. You could put your apps not requiring Play services in a work or secondary profile instead. It's just how this works until there's an alternate implementation not requiring Play services.

**Comment by geppi** [comment] 2022-04-12 11:37
Can you tell if it does require all 3 components including the PlayStore? Or would GSF + GMS be sufficient?

**Comment by thestinger** [comment] 2022-04-12 11:39
GSF + GMS should be enough. I don't know how much it requires from them, like whether it actually uses any of their services (i.e. Network may be required) through GMS instead of doing that itself.

**Comment by Mattrazol** [comment] 2022-04-17 22:49
Since I understood that to activate the eSIM these two (GSF + GMS) have to be installed on the main profile (not the work profile): is it possible to install GSF and GMS, setup the eSIM and then remove them after the carrier setup is completed (since I don't want/use GSF and GMS on my main profile)?

**Comment by Mattrazol** [comment] 2022-04-17 22:57
Since I understood that the GSF + GMS have to be installed on the main profile (not on the work profile), is it possible to install GSF + GMS, setup the eSIM and then uninstall them afterwards? (Since I don't want/use them on my main profile)

**Comment by Zanthed** [comment] 2022-04-17 23:08
Yes after activation you can remove GSF + GMS.

**Comment by Mattrazol** [comment] 2022-04-17 23:11
@Zanthed what is the right/cleanest way to remove them? Uninstalling them like a regular app will be enough? Or is there a different procedure to remove them all their dependencies?

**Comment by thestinger** [comment] 2022-04-17 23:12
They're simply 3 regular sandboxed apps with the same sandbox, rules and restrictions as other user installed apps. There's nothing special about installing or removing them.

**Comment by Zanthed** [comment] 2022-04-17 23:12
They're normal apps. They aren't special. They aren't privileged. Uninstalling them like any other app is all you need to do.

**Comment by felixmartens** [comment] 2022-04-21 18:17
Having read the whole discussion multiple times: Did i got this right that the current release supports eSim   Activation without doing this on stock os before?

Thanks for your insane development!!

**Comment by thestinger** [comment] 2022-04-21 18:25
Read https://grapheneos.org/usage#sandboxed-google-play-esim. It's supported as a sandboxed Google Play extension.

**Comment by phhusson** [comment] 2022-04-29 10:44
I managed to provision an eSIM just fine using https://github.com/Truphone/LPAd_SM-DPPlus_Connector/ mentioned before.

My PoC code source is at https://github.com/phhusson/PhhDialer/tree/euicc There is no UI or anything, so it requires modifying source code manually to give it the eSIM infos, and to do the profile switches

**Comment by thestinger** [comment] 2022-06-17 22:23
Developing an open source replacement for the PIxel eSIM apps providing the same functionality and meeting our requirements doesn't currently have someone working on it.

We plan on using the donation to provide funding to someone to develop what we need rather than the unrealistic approach of someone making a large project meeting our requirements with no funding with the hope of getting it merged with the unpaid time they're able to invest in it to obtain a bounties. Bounties are problematic for non-trivial projects like this for multiple reasons and one of those can be seen here where the specifics were not laid out. Someone might have invested substantial work in it only to not end up providing something we're able to merge and therefore not getting it. It's better for us to find someone to work on it and fund it normally.

**Comment by thestinger** [comment] 2022-06-17 22:27
A full implementation is inherently going to require an optional dependency on sandboxed Google Play because FCM is used as part of activation for some carriers.

The first thing to do is figuring out the scope of the full project and what would actually need to be done to provide all that functionality.

We should probably develop an alternative to the Pixel app for keeping the eSIM secure element firmware uploaded / updated before working on the activation portion of it. That's a smaller task and then at least people wouldn't have much reason to do more than the initial activation using the Google apps.

**Comment by phhusson** [comment] 2022-06-17 22:28
Could you list your requirements that aren't matched by https://gitea.angry.im/PeterCxy/OpenEUICC ?

Other companies are willing to contribute to the development of OpenEUICC, so even though GrapheneOS doesn't have the manpower to do it, with your list of requirements, it's possible someone could do it.

Also you know... opensource people do stuff for free sometimes.

**Comment by thestinger** [comment] 2022-06-17 23:17
@phhusson If you want to have a technical discussion or participate in our community I expect you to remove the inaccurate claims you've made about GrapheneOS and myself elsewhere. This isn't in isolation from that especially since I posted here to clarify what happened based on the strange take you posted making it seem as if we posted a bounty and you did what was required to earn it when neither of those things has happened.

**Comment by phhusson** [comment] 2022-06-17 23:24
I've wanted a technical discussion for two months now. You're answering here only because I triggered you (which I definitely didn't intend to), not because you decided this matters.

**Comment by thestinger** [comment] 2022-06-17 23:31
> I've wanted a technical discussion for two months now. You're answering here only because I triggered you (which I definitely didn't intend to), not because you decided this matters.

I've seen no attempt on your part to contact us. Today you spread multiple fabricated stories about GrapheneOS and are treating a severe libel and harassment campaign directed towards me as a laughing matter. You can either remove the misinformation you spread today and several previous attempts at spinning things as you did with the bounty here or you aren't welcome to contact me and aren't welcome to participate in any space where I participate. My issue with Bromite is that they decided to allow the participation of people openly involved in abusive behavior towards me because in their own words they don't care.

Before today, I only had an issue with a few previous attempts at spin you posted like that. If that is all you had done today, there wouldn't be a serious issue between us but now there is and that's not ever going away unless you're going to try to undo the harm you did to GrapheneOS and to me in a completely unjust way.

**Comment by thestinger** [comment] 2022-06-18 00:58
@phhusson Not only did you refuse to remove clear lies and misinformation but you doubled down and did even more. To be clear, you are permanently banned from the GrapheneOS community, you are not permitted to ever contact me again and people who permit abusive people like you in their communities are no friends of ours.

**Comment by thestinger** [comment] 2022-06-18 01:02
@phhusson has been permanently banned from the GrapheneOS community due to their repeated fabrication of stories about GrapheneOS, libel about the project members including myself, support for harassment and their repeated borderline plagiarism where they take credit for other people's work and claim to have been responsible for it when they were not.

**Comment by geppi** [comment] 2022-08-18 08:57
Just stumbled across this [blogpost](https://blog.esper.io/android-dessert-bites-24-esim-me-1248143/)  mentioning PeterCxy’s [OpenEUICC project](https://gitea.angry.im/PeterCxy/OpenEUICC), an open source eSIM LPA implementation licensed under GPLv2. It says that:

> OpenEUICC implements Android’s system APIs for eSIM management, namely [EuiccManager](https://developer.android.com/reference/android/telephony/euicc/EuiccManager) and [EuiccService](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/telephony/java/android/service/euicc/EuiccService.java), and it requests the privileged permissions needed to interface with eUICCs via the TelephonyManager API ([android.permission.WRITE_EMBEDDED_SUBSCRIPTIONS](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/res/AndroidManifest.xml;l=2565?q=WRITE_EMBEDDED_SUBSCRIPTIONS) and [android.permission.MODIFY_PHONE_STATE](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/res/AndroidManifest.xml;l=2387?q=MODIFY_PHONE_STATE)) or OMAPI ([android.permission.SECURE_ELEMENT_PRIVILEGED_OPERATION](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/res/AndroidManifest.xml;l=2078?q=SECURE_ELEMENT_PRIVILEGED_OPERATION)) without needing to be allow listed in the ARF.

Could that be used as the foundation of a full implementation for eSIM activation and configuration support in GrapheneOS without sandboxed Google Play Services?

**Comment by oleduc** [comment] 2022-10-26 16:50
I was a able to setup my eSIM by installing sandboxed Google play services in priviledge mode and then removing it. Airplane mode and reboot worked fine.

**Comment by codethief** [comment] 2023-01-23 23:41
> PSA: Once I had it working, I made the mistake of hitting the "disable SIM" toggle for the eSIM in the network settings. (My plan was to disable the eSIM for a second to see whether the physical SIM is fully functional, too.) Unfortunately, the eSIM then disappeared completely and it seems there is no way of undoing this, short of re-flashing GrapheneOS. (I tried disabling and re-enabling DSDS, among other things.) So be careful. :)

I stand corrected: As I just found out, after accidentally disabling the eSIM and the eSIM disappearing, it is not necessary to flash the stock ROM and then re-install GrapheneOS. The eSIM is not entirely gone and it is possible to make it reappear by briefly disabling DSDS (via ` *#*#INFO#*#*` or ` *#*#4636#*#* `) and then reenabling it again.

**Comment by thestinger** [comment] 2023-01-23 23:49
GrapheneOS has eSIM activation support:

https://grapheneos.org/usage#sandboxed-google-play-esim

There's no need to use the stock OS even for activating initially.

**Comment by thestinger** [comment] 2023-01-23 23:50
A new issue should be used for discussing new issues or discussing development of an open source eSIM activation and firmware update system.
