### ISSUE TITLE
Biometric crash

### ISSUE THREAD

**Issue by ddkrd** [GrapheneOS/os-issue-tracker#3603] opened 2024-06-03 07:01 UTC
```
type: crash
osVersion: google/husky/husky:14/AP1A.240505.005/2024053100:user/release-keys
uid: 1000 (u:r:hal_fingerprint_default:s0)
cmdline: /apex/com.google.android.hardware.biometrics.fingerprint/bin/hw/android.hardware.biometrics.fingerprint-service.goodix
processUptime: 45897s

signal: 11 (SIGSEGV), code 9 (SEGV_MTESERR), faultAddr f00d5a221183d20
threadName: android.hardwar
MTE: enabled

backtrace:
    /apex/com.android.vndk.v35/lib64/libutils.so (android::SharedBuffer::attemptEdit() const+4, pc fd54)
    /apex/com.android.vndk.v35/lib64/libutils.so (android::VectorImpl::editArrayImpl()+36, pc 11244)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::EventCenter::hasUpEvt()+28, pc 6222c)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::DelmarSensor::checkFingerUp(unsigned int)+24, pc 4d074)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::DelmarSensor::readImage(unsigned int, unsigned long)+232, pc 4cb64)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::CustomizedSensor::readImage(unsigned int, unsigned long)+12, pc 68d0c)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::DelmarFingerprintCore::onAfterAuthCapture(goodix::FingerprintCore::AuthenticateContext*)+76, pc 4b0cc)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::CustomizedFingerprintCore::onAfterAuthCapture(goodix::FingerprintCore::AuthenticateContext*)+304, pc 582b0)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::FingerprintCore::onAuthDownEvt()+1200, pc 5dc90)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::FingerprintCore::onEvent(gf_event_type_t)+88, pc 5ec08)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::EventCenter::dispatchEvent(gf_event_type_t)+164, pc 61cb4)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::EventCenter::threadLoop()+208, pc 623d0)
    /apex/com.google.android.hardware.biometrics.fingerprint/lib64/libgf_hal.so (goodix::Thread::sthreadLoop(void*)+28, pc 60e7c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc d5e6c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68, pc 69a64)
```

**Comment by Daniel-A-Gutierrez** [comment] 2024-08-20 22:47
Just got this same error.

**Comment by arikb** [comment] 2024-09-01 05:40
Got it right now

```
type: crash
osVersion: google/akita/akita:14/AP2A.240805.005.A1/2024082200:user/release-keys
uid: 1000 (u:r:hal_fingerprint_default:s0)
cmdline: /vendor/bin/hw/android.hardware.biometrics.fingerprint-service.goodix
processUptime: 808047s

signal: 11 (SIGSEGV), code 9 (SEGV_MTESERR), faultAddr 300d706bf283e70
threadName: android.hardwar
MTE: enabled

backtrace:
    /vendor/lib64/libutils.so (android::SharedBuffer::attemptEdit() const+4, pc 10374)
    /vendor/lib64/libutils.so (android::VectorImpl::editArrayImpl()+36, pc 12f34)
    /vendor/lib64/libgf_hal.so (goodix::EventCenter::hasUpEvt()+28, pc 6223c)
    /vendor/lib64/libgf_hal.so (goodix::DelmarSensor::checkFingerUp(unsigned int)+24, pc 4d074)
    /vendor/lib64/libgf_hal.so (goodix::DelmarSensor::readImage(unsigned int, unsigned long)+232, pc 4cb64)
    /vendor/lib64/libgf_hal.so (goodix::CustomizedSensor::readImage(unsigned int, unsigned long)+12, pc 68eec)
    /vendor/lib64/libgf_hal.so (goodix::DelmarFingerprintCore::onAfterAuthCapture(goodix::FingerprintCore::AuthenticateContext*)+76, pc 4b0cc)
    /vendor/lib64/libgf_hal.so (goodix::CustomizedFingerprintCore::onAfterAuthCapture(goodix::FingerprintCore::AuthenticateContext*)+304, pc 582e0)
    /vendor/lib64/libgf_hal.so (goodix::FingerprintCore::onAuthDownEvt()+1200, pc 5dcb0)
    /vendor/lib64/libgf_hal.so (goodix::FingerprintCore::onEvent(gf_event_type_t)+88, pc 5ec28)
    /vendor/lib64/libgf_hal.so (goodix::EventCenter::dispatchEvent(gf_event_type_t)+164, pc 61cc4)
    /vendor/lib64/libgf_hal.so (goodix::EventCenter::threadLoop()+208, pc 623e0)
    /vendor/lib64/libgf_hal.so (goodix::Thread::sthreadLoop(void*)+28, pc 60e8c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc 795dc)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68, pc 69fa4)
```

**Comment by muhomorr** [comment] 2024-11-08 15:50
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/4058

**Closed by muhomorr** 2024-11-08 15:50 UTC
