### ISSUE TITLE
JMP.chat/Cheogram calls lose mic INPUT when using integrated dialer

### ISSUE THREAD

**Issue by virtuousvector** [GrapheneOS/os-issue-tracker#2871] opened 2023-12-15 19:27 UTC
This might be related to #2557 but does not appear to be the exact same issue to me as there is NOTHING in my experience related to bluetooth/audio output ...

When using the native dialer integration in GOS with Cheogram for JMP.chat phone service, calls reliably have a problem after a few minutes of conversation where the other party can suddenly no longer hear me. The call is still connected and I can still hear the other party. It also does not revert back, ie. it doesn't feel like an intermittent reception issue like someone going through a tunnel, etc. I call right back and the same pattern plays out consistently. 

The workaround is to remove Cheogram from calling accounts in GOS and make/receive calls through Cheogram natively. This doesn't sound so bad, but the UI for Cheogram is so challenging that it actually rises to the level of driving reconsideration of my entire privacy calling strategy.

I raised this issue with Cheogram and their response is below. It's unclear to me whether they are going to actively work on this or chalk it up to a GOS problem. 

GOS and Cheogram/JMP.chat are independently such fabulous services for the privacy community, I would hate to see this be just a game of blaming each other. :( 

Cheogram response ...
"we're pretty confident it's not a Cheogram bug, but there's a chance we can work around somehow If we figure out what's happening ... we've not yet managed to reproduce on A14 non GOS."

**Comment by thestinger** [comment] 2023-12-15 19:32
> "we're pretty confident it's not a Cheogram bug, but there's a chance we can work around somehow If we figure out what's happening ... we've not yet managed to reproduce on A14 non GOS."

This doesn't mean that it's not a bug in it. GrapheneOS makes no changes to any of this infrastructure.

**Comment by virtuousvector** [comment] 2023-12-15 19:44
> This doesn't mean that it's not a bug in it. GrapheneOS makes no changes to any of this infrastructure.

I hear you. I've worked in software for 20+ years. But when both dev teams have similar responses users aren't left with any options. :(

**Comment by singpolyma** [comment] 2023-12-16 02:45
Since there is nothing actionable here for GOS team, probably it can be closed while debugging and information gathering is happening on our side.

**Comment by singpolyma** [comment] 2023-12-16 02:47
> the UI for Cheogram is so challenging that it actually rises to the level of driving reconsideration of my entire privacy calling strategy.

obviously off topic here, but if you're having struggles to use the in-app dialler feel free to come by out channel and we can talk about that also.

**Comment by thestinger** [comment] 2023-12-16 02:48
It's probably something which changed in AOSP which broke the app but it's very unlikely that it's specific to GrapheneOS. The AOSP Dialer app is barely developed anymore and might have a bug that's unfixed. The Dialer in the stock Pixel OS is a different one. It doesn't really seem like the Dialer app would actually be responsible for this though.

**Comment by singpolyma** [comment] 2023-12-16 02:51
@thestinger one of our team spent most of today debugging on this and the current theory is it's related to the new mic permission system in A14.  Not sure why we haven't been able to reproduce outside of GOS yet but it hardly matters if we manage to find a solution.  Hopefully we will find something that works soon.

Thanks for all you do and your hard work on GOS.  We will be in contact of course if we think we find something actionable that is GOS specific, but as you say that seems unlikely at this point.

**Comment by thestinger** [comment] 2023-12-16 03:00
When was it first reported? Android 14 QPR1 just came out this month (December) and in practice only Pixels ship the monthly and quarterly releases when they come out (or pretty much at all) rather than the standalone security backports. They have slow staged rollouts so GrapheneOS users tend to get the new releases before stock OS users unless they actively try to obtain the update as soon as possible. Means that GrapheneOS users are often going to be the first ones to run into these bugs. QPR1 fixed a LOT of issues but also introduced some new ones. We had to fix some of them ourselves since waiting for them is too slow for things that are higher priority for us.

**Closed by thestinger** 2023-12-16 03:00 UTC

**Comment by virtuousvector** [comment] 2023-12-16 16:37
@thestinger @singpolyma REALLY grateful for both of you collaborating and being willing to talk through this. I realize this might seem like a small thing but given how unique and compelling BOTH GrapheneOS and JMP.chat/Cheogram are independently, it's a massive unlock to get them working together through the native GrapheneOS dialer. I think it's a big step closer to getting the privacy respecting voice experience to parity with "mainstream" options.

**Comment by rkraken** [comment] 2024-01-29 04:17
> This might be related to #2557 but does not appear to be the exact same issue to me as there is NOTHING in my experience related to bluetooth/audio output ...
> 

I believe that was a typo and you meant issue #2577, which I filed a few months ago.  Just today I noticed a similar problem while using the built in speaker only, no bluetooth.  Both parties were unable to hear each other, occurring about 10 seconds after the call was connected.  Hopefully they are caused by the same underlying problem.

> @thestinger @singpolyma REALLY grateful for both of you collaborating and being willing to talk through this. I realize this might seem like a small thing but given how unique and compelling BOTH GrapheneOS and JMP.chat/Cheogram are independently, it's a massive unlock to get them working together through the native GrapheneOS dialer. I think it's a big step closer to getting the privacy respecting voice experience to parity with "mainstream" options.

Completely agree!  Thanks for your dedication and hard work.
