### ISSUE TITLE
Tapping new SMS message from lock screen goes to blank screen.

### ISSUE THREAD

**Issue by Mcflorple** [GrapheneOS/os-issue-tracker#1204] opened 2022-05-19 07:56 UTC
A couple of weeks ago an update broke double tapping a new message notification in the swipe screen lock. If you double tap the screen goes blank and you have to turn the screen off and on to go back to the lock screen and just swipe up and go the messaging app directly.

**Comment by r3g-5z** [comment] 2023-03-01 02:30
Is this still an issue? I can't reproduce this in emulator.

**Comment by r3g-5z** [comment] 2023-03-02 00:50
Going to assume this has been fixed in QPR1 or an update as it has been over 9 months since this issue was posted, and no one else has reported this issue or upvoted the issue confirming this issue happens to them as well.

If it's still an issue let us know, but we'll need more clear reproduction steps because I cannot reproduce this in emulator.

**Closed by r3g-5z** 2023-03-02 00:50 UTC
Labels: upstream

**Comment by Mcflorple** [comment] 2023-03-02 04:05
Apologies just saw this. Yes it cleared up when GrapheneOS moved to the new android version. Thanks for taking the time to respond!
