### ISSUE TITLE
Screen stopped working in Pixel 6A

### ISSUE THREAD

**Issue by cherez0ff** [GrapheneOS/os-issue-tracker#1831] opened 2022-12-18 13:57 UTC
Same as https://github.com/GrapheneOS/os-issue-tracker/issues/1824

Now that battery was drained and phone is shut down - I confirm it's not a hardware/screen issue, as I plug in charger and restarted phone successfully. Something is seriously broken in latest update(s). I can give you logs and more data, just tell me how.

**Comment by thestinger** [comment] 2022-12-18 19:08
No one else is having this issue though. Turn off any device managers, accessibility services or apps with draw over other apps as a starting point.

**Comment by whereskarlo** [comment] 2022-12-19 09:48
> No one else is having this issue though. Turn off any device managers, accessibility services or apps with draw over other apps as a starting point.

There are three reports of this now including my report of unresponsive screen.
#1831
#1830 
#1824

**Comment by thestinger** [comment] 2022-12-19 09:53
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/1830 and not reproducible.

**Closed by thestinger** 2022-12-19 09:53 UTC
