### ISSUE TITLE
Add the ability to hide the green location popup on the top right

### ISSUE THREAD

**Issue by bcsti** [GrapheneOS/os-issue-tracker#2987] opened 2024-01-02 15:29 UTC
A option to toggle the visibility of the green location accessed popup for specific apps would be great.

I have some apps like VPN or Tasker which check the location every minute, so the green dot is visible almost all time.

It's annoying when it always pops up.

I don't want the option to hide it overall since I still want to know when I'm getting located, just the ability to hide it for specific apps like the two above.

**Comment by thestinger** [comment] 2024-01-02 16:05
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/1886.

**Closed by thestinger** 2024-01-02 16:05 UTC
