### ISSUE TITLE
Changing profiles re-loads widgets

### ISSUE THREAD

**Issue by sm131313** [GrapheneOS/os-issue-tracker#1992] opened 2023-03-04 20:05 UTC
Setup a widget on homescreen, any widget but for reference I am using k9 email widget. 
Switch profile to second user and stay there for some minutes, doing some surfing. 
Switch back to Main and the widget is now unloaded and needs to be loaded from beginning as if you have just booted the phone. 

Expected:
The widget should not be booted again from beginning as it causes a delay in usability transitioning between profiles.

**Comment by r3g-5z** [comment] 2023-03-04 20:08
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/453

**Closed by r3g-5z** 2023-03-04 20:08 UTC

**Comment by thestinger** [comment] 2023-03-04 20:10
It doesn't really sound like a bug but rather an intentional part of the way profiles are designed to save resources.

**Comment by thestinger** [comment] 2023-03-04 20:10
Think we should stick with how this works upstream.

**Comment by JW10234** [comment] 2023-09-09 17:06
In my case, the issue only occured when I pressed "end session". When I switched to main using the users page, All my widgets were preserved. The user I tested it on does not have permission to run in the background.
