### ISSUE TITLE
Google Maps crashes when Play service apps are installed in another profile but not in current one

### ISSUE THREAD

**Issue by justinhsa** [GrapheneOS/os-issue-tracker#685] opened 2021-10-10 02:43 UTC
Device: Pixel 5 (redfin)
OS version: RQ3A.211001.001.2021100606

Hello, just noticed this. I have one secondary profile with play service apps installed. If I install google maps in another secondary profile without play service apps, it will crash on start. Haven't tested on owner profile yet. Below is part of the logs that I think related: 

`FATAL EXCEPTION: DefaultPool5`
`Process: com.google.android.apps.maps, PID: 15591`
`java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 12; expected to find a valid ContentProvider for this authority`
`	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)`
`	at android.os.Parcel.createException(Parcel.java:2357)`
`	at android.os.Parcel.readException(Parcel.java:2340)`
`	at android.os.Parcel.readException(Parcel.java:2282)`
`	at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:1229)`
`	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2627)`
`	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2615)`
`	at cytj.<init>(PG:2)`
`	at cytj.a(PG:2)`
`	at cyue.j(PG:2)`
`	at cyue.d(PG:10)`
`	at czdw.d(PG:1)`
`	at com.google.android.libraries.social.peoplekit.avatars.viewcontrollers.glide.FifeGlideModule.c(PG:2)`
`	at ddn.g(PG:42)`
`	at ddn.b(PG:3)`
`	at ddn.d(PG:2)`
`	at ddn.c(PG:1)`
`	at crqt.a(PG:2)`
`	at ddbw.a(PG:1)`
`	at crqp.run(PG:6)`
`	at bwkl.run(PG:2)`
`	at bwlv.run(PG:2)`
`	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)`
`	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)`
`	at bwlm.run(PG:4)`
`	at java.lang.Thread.run(Thread.java:923)`
`Caused by: android.os.RemoteException: Remote stack trace:`
`	at com.android.server.content.ContentService.registerContentObserver(ContentService.java:355)`
`	at android.content.IContentService$Stub.onTransact(IContentService.java:482)`
`	at android.os.Binder.execTransactInternal(Binder.java:1154)`
`	at android.os.Binder.execTransact(Binder.java:1123)`

**Comment by thestinger** [comment] 2021-10-10 03:08
Are you talking about a secondary user or a work profile?

**Comment by codethief** [comment] 2022-01-24 17:49
Similar (but slightly different) observation: When I install Signal in my personal profile (while having Play Services installed *only* in my work profile), Signal still thinks Play Services are available and will attempt to use them for notifications instead of using the web socket. Details -> https://github.com/signalapp/Signal-Android/issues/9279#issuecomment-991404603

**Comment by Zanthed** [comment] 2022-02-02 06:04
I can't reproduce this on the latest release. Can you please try the latest version (2022013120) and see if it still happens?

**Comment by thestinger** [comment] 2022-02-02 06:05
This shouldn't be an issue anymore across user profiles. The issue should be fixed upstream now.

**Closed by thestinger** 2022-02-02 06:05 UTC
Labels: bug
