### ISSUE TITLE
Attempting to sign in to websites using FIDO2 WebAuthn via NFC crashes Google Play Services

### ISSUE THREAD

**Issue by moonbeast32** [GrapheneOS/os-issue-tracker#1978] opened 2023-02-25 02:15 UTC
I am attempting to set up MFA for many of my accounts using a SoloKey USB-A NFC key. I've gotten it to work via USB A on my laptop, but not on my Pixel 6a.

Things I've done:

- enabled NFC in settings
- granted Google Play Services permissions for 'Photos and Videos', and 'Music and Audio'
- updated to the latest build (TQ1A.230205.002.2023021000 at time of writing)
- Attempted on Vanadium and on Firefox.
- attempted on multiple websites

<h3>Reproduction steps:</h3>

1. Enable MFA authentication on a website, and add your key via USB on a different device (Bitwarden in my case)
2. on Vanadium or on Firefox, attempt to log into the website until prompted for MFA, and then click on the button to start
3. In the new window that pops up, follow instructions and click 'Get Started'

![Screenshot_20230224-183909](https://user-images.githubusercontent.com/48586368/221329759-6db95960-0bb4-4442-a2a6-81778b77810d.png)

4. When prompted, press the key to the back of the phone

![Screenshot_20230224-183915](https://user-images.githubusercontent.com/48586368/221329910-69a768c7-c113-492f-86d2-0fbf6f436552.png)

<h3>Result:</h3>

When pressing my key to the back of my phone about 5-6 instances of a new 'Continue to hold your security key in place' window appear, each accompanied by a jingle. 

![Screenshot_20230224-183922](https://user-images.githubusercontent.com/48586368/221330030-41a6328c-8617-4129-84a3-45e759980b21.png)

I keep the key held in place until all windows say "You can now remove your security key"

![Screenshot_20230224-183931](https://user-images.githubusercontent.com/48586368/221330067-fe847f64-4499-4e62-a788-d04d99388444.png)

Shortly after, the initial window closes, taking me back to the website login on my browser. Instead of logging me in, an error box appears in the top right corner saying "NotReadableError: An unknown error occurred while talking to the credential manager."

![Screenshot_20230224-172335](https://user-images.githubusercontent.com/48586368/221330243-eea73338-23ce-4663-acab-3b443a5fd0ff.png)

In addition to this, I get several notifications from GmsCompact telling me that Google Play Services has crashed. Here is the crash log:  https://pastebin.com/bpwR3cpa

Update as I'm writing this: I though of updating GPS to the latest build and tried it again. I no longer get the crash notifications, but everything else is still the same.

<h3>Specs:</h3>
Pixel 6a
Android 13
GrapheneOS build: TQ1A.230205.002.2023021000
Google Play Services version: 23.05.14 (190400-509319212)

Solo Tap USB-A + NFC

**Comment by muhomorr** [comment] 2023-02-26 09:48
Unable to reproduce this issue with YubiKey 5C NFC, both in NFC and USB modes.
Need to see a logcat. Reboot your device, reproduce this issue, and then capture the logcat with `adb logcat -d > log.txt`

**Comment by muhomorr** [comment] 2023-02-28 06:20
> I tried that logcat command, but it doesn't seem to do anything. its only output is: waiting for device

Need to enable ADB access first: https://developer.android.com/studio/command-line/adb#Enabling

> Also, just in case you didn't see it, I said I was using s Solokey, not yubikey. 

I've seen it. Support for security keys is implemented in Play services in a generic way AFAIK.

**Comment by wwwcccc1** [comment] 2023-03-08 09:38
gms doesnt have support for fido2/ctap2, only for u2f/ctap1, rather, it wants you to use passkeys for passwordless, and doesnt let you use your security keys

**Comment by thestinger** [comment] 2023-03-08 13:32
That's not true, it supports FIDO2.

**Comment by Flactual** [comment] 2023-03-18 23:10
I've reproduced it. 
No dialog opens for webauth in vanadium.
Google play services and play store are installed and running. Google play services has storage scopes enabled. They don't crash when attempting to open the webauthn dialog however. When testing using demo.yubico.com, it gives the error 
`The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client.`
This is on a pixel 6a. I can't reproduce it on my 4a (5g). Could there be something wrong with the grapheneos version for the 6a?
I picked this particular section out of the log that seemed relavent, but this isn't my area so I don't know how to interpret it other than, "hey, this don't work".
`03-18 19:04:49.323  3768  3768 E cr_Fido2Request: FIDO2 API call failed
03-18 19:04:49.323  3768  3768 E cr_Fido2Request: W7: 17: API: Fido.FIDO2_PRIVILEGED_API is not available on this device. Connection failed with: ConnectionResult{statusCode=INTERNAL_ERROR, resolution=null, message=null}
03-18 19:04:49.323  3768  3768 E cr_Fido2Request: 	at Y7.a(chromium-TrichromeChrome6432.apk-stable-556305834:18)
03-18 19:04:49.323  3768  3768 E cr_Fido2Request: 	at M12.a(chromium-TrichromeChrome6432.apk-stable-556305834:6)
03-18 19:04:49.323  3768  3768 E cr_Fido2Request: 	at a12.d(chromium-TrichromeChrome6432.apk-stable-556305834:45)
03-18 19:04:49.323  3768  3768 E cr_Fido2Request: 	at a12.c(chromium-TrichromeChrome6432.apk-stable-556305834:7)
03-18 19:04:49.323  3768  3768 E cr_Fido2Request: 	at a12.o(chromium-TrichromeChrome6432.apk-stable-556305834:179)
03-18 19:04:49.323  3768  3768 E cr_Fido2Request: 	at a12.z(chromium-TrichromeChrome6432.apk-stable-556305834:2)
03-18 19:04:49.323  3768  3768 E cr_Fido2Request: 	at b72.b(chromium-TrichromeChrome6432.apk-stable-556305834:9)
03-18 19:04:49.323  3768  3768 E cr_Fido2Request: 	at z22.a(chromium-TrichromeChrome6432.apk-stable-556305834:50)
03-18 19:04:49.323  3768  3768 E cr_Fido2Request: 	at l42.handleMessage(chromium-TrichromeChrome6432.apk-stable-556305834:378)
03-18 19:04:49.323  3768  3768 E cr_Fido2Request: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-18 19:04:49.323  3768  3768 E cr_Fido2Request: 	at android.os.Looper.loopOnce(Looper.java:201)
03-18 19:04:49.323  3768  3768 E cr_Fido2Request: 	at android.os.Looper.loop(Looper.java:288)
03-18 19:04:49.323  3768  3768 E cr_Fido2Request: 	at android.os.HandlerThread.run(HandlerThread.java:67)`
I've attached the entire log
[log.txt](https://github.com/GrapheneOS/os-issue-tracker/files/11009811/log.txt)

**Comment by muhomorr** [comment] 2023-03-19 07:24
@Flactual Try updating Play services to the latest version through the Play Store.

**Comment by muhomorr** [comment] 2023-03-19 09:47
This is a different issue than what was initially reported.
@Flactual Play services doesn't have the Network permission on your device, and this triggers a compatibility layer bug.
Play services FIDO2 implementation does work without the Network permission, this'll be fixed by a GmsCompatConfig update.

**Comment by thestinger** [comment] 2023-03-19 17:44
This is resolved with GmsCompatConfig v40 now in the stable channel of the app repository.

**Comment by r3g-5z** [comment] 2023-04-01 22:43
Is this still an issue? No one else is reporting FIDO2 issues.

**Comment by bigswag420** [comment] 2023-04-26 11:51
ion know if this is related 🗿 but passkeys don't save on my shit

steps to reproduce:
1. go to a website that save passkeys 🗿 like passkeys.io
2. a pop up appears asking to save the passkey
3. attempt to save it
4. it simply does not save 🧍‍♀️

tried on google chrome and vanadium 🗿🍵

in addition 🕺🕺🕺🕺 you just don't get to use passkeys if you don't have google play![Screenshot_20230426-074945.png](https://user-images.githubusercontent.com/94314620/234566135-2bcd0f4b-156d-4655-ab70-1283c372e047.png)

**Comment by r3g-5z** [comment] 2023-04-26 12:04
Since the original issue reported is not reproducible by anyone, there hasn't been any activity by OP, and no one else has reported FIDO2 issues in the past month, we're going to assume it's a Solokey problem or a configuration problem on the user's end.

If this is still an issue let us know but we need substantially more information here of the user's configuration, including a logcat as requested previously which was not supplied.

**Closed by r3g-5z** 2023-04-26 12:04 UTC
Labels: bug, status-unconfirmed, status-needinfo

**Comment by bigswag420** [comment] 2023-04-26 12:11
> Passkeys aren't the same thing here. See https://github.com/GrapheneOS/os-issue-tracker/issues/2073#issuecomment-1493388702

ong how did I not see that in search 😭

**Comment by Silur** [comment] 2023-11-23 12:39
The issue is reproducible on my end with latest GmsCompat

**Comment by thestinger** [comment] 2023-11-23 12:51
Please file a new issue.
