### ISSUE TITLE
Incorrect Duress Password Setup Triggerd System Restart

### ISSUE THREAD

**Issue by tashijayla** [GrapheneOS/os-issue-tracker#3703] opened 2024-07-01 23:16 UTC
When attempting to set up a Duress password, I entered a incorrect password that caused a system crash and restart.

Steps to Reproduce:
1. Navigate to the Duress password setup screen.
2. Enter an incorrect password.

Expected Behavior:
The system should prompt for the correct password without restarting.

Actual Behavior:
Entering an incorrect password caused the system to restart.

type: crash
SystemUptimeMs: 9172467
Process: system_server
Build: google/panther/panther:14/AP2A.240605.024/2024062700:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.autofill.ui.FillUi$AnchoredWindow.show(android.view.WindowManager$LayoutParams)' on a null object reference
at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter.lambda$show$0(FillUi.java:692)
at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter.$r8$lambda$rayRxR7zWVCJ_EZ9KlZ9jO79cqM(FillUi.java:0)
at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.os.HandlerThread.run(HandlerThread.java:85)
at com.android.server.ServiceThread.run(ServiceThread.java:46)
at com.android.server.UiThread.run(UiThread.java:45)

**Comment by muhomorr** [comment] 2024-07-02 07:28
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/3679

**Comment by muhomorr** [comment] 2024-07-02 07:29
This crash is not due to duress password setup attempt, it's an upstream autofill-related bug.

**Closed by muhomorr** 2024-07-02 07:28 UTC
