### ISSUE TITLE
Bug: Pixel 8 Pro cannot turn off Extra Dim

### ISSUE THREAD

**Issue by minhng99** [GrapheneOS/os-issue-tracker#2900] opened 2023-12-19 07:20 UTC
Platform: Google Pixel 8 Pro
OS Version: 14 build UQ1A.231205.015.2023121200

To Replicate:

1. Open Settings App
2. Select Accessibility
3. Enable Extra Dim -> The screen gets dimmer
4. Disable Extra Dim -> The screen is still just as dim and not back to its normal brightness

- If I crank up the Brightness, the brightness does go up but just as dim as when the feature is Enabled.
- The only way to get rid of this is to reboot.

**Comment by thestinger** [comment] 2023-12-19 11:40
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/1437, an upstream Android bug.

**Closed by thestinger** 2023-12-19 11:40 UTC
