### ISSUE TITLE
Sandboxed google Play crashes, without apparent reason or change in settings

### ISSUE THREAD

**Issue by Gyathob** [GrapheneOS/os-issue-tracker#2410] opened 2023-08-26 16:40 UTC
```
type: crash
osVersion: google/raven/raven:13/TQ3A.230805.001/2023080800:user/release-keys
package: com.google.android.gms:233314044
process: com.google.android.gms.persistent
processUptime: 47094 + 340 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 70

java.lang.SecurityException: Permission Denial: registerUidObserver from pid=21204, uid=10147 requires android.permission.PACKAGE_USAGE_STATS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
	at android.os.Parcel.createException(Parcel.java:3004)
	at android.os.Parcel.readException(Parcel.java:2980)
	at android.os.Parcel.readException(Parcel.java:2922)
	at android.app.IActivityManager$Stub$Proxy.registerUidObserver(IActivityManager.java:4802)
	at android.app.ActivityManager.addOnUidImportanceListener(ActivityManager.java:3846)
	at com.google.android.gms.common.util.AppImportanceHelperV26.c(:com.google.android.gms@233314044@23.33.14 (190400-558914857):7)
	at com.google.android.gms.common.util.AppImportanceHelper.b(:com.google.android.gms@233314044@23.33.14 (190400-558914857):19)
	at djir.t(:com.google.android.gms@233314044@23.33.14 (190400-558914857):9)
	at djir.u(:com.google.android.gms@233314044@23.33.14 (190400-558914857):28)
	at djir.handleMessage(:com.google.android.gms@233314044@23.33.14 (190400-558914857):31)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at bbrt.lG(:com.google.android.gms@233314044@23.33.14 (190400-558914857):1)
	at bbrt.dispatchMessage(:com.google.android.gms@233314044@23.33.14 (190400-558914857):143)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	Suppressed: dpix: 
		at tk_trace.location_base-GoogleLocationChimeraService_onCreate(Unknown Source:0)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforceCallingPermission(ActivityManagerService.java:6029)
	at com.android.server.am.ActivityManagerService.registerUidObserver(ActivityManagerService.java:7420)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2036)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2632)
	at android.os.Binder.execTransactInternal(Binder.java:1309)


```

**Comment by thestinger** [comment] 2023-08-26 16:48
This will be fixed when you update to GmsCompatConfig v71. It has just been pushed to the stable channel in the app repository. The issue was caused by a newly enabled Play services feature flag.

**Closed by thestinger** 2023-08-26 16:48 UTC
