### ISSUE TITLE
Display screen time out is not working some times

### ISSUE THREAD

**Issue by Madhpharma** [GrapheneOS/os-issue-tracker#1976] opened 2023-02-24 14:44 UTC
I set it for 30sec for screen timeout on my pixel 6a , but the display is not turning off, I have to press the power button to turn screen off.

**Comment by r3g-5z** [comment] 2023-02-24 15:42
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/1268

**Closed by r3g-5z** 2023-02-24 15:42 UTC
