### ISSUE TITLE
phone dialer does not play sound over bluetooth headset device in secondary profiles

### ISSUE THREAD

**Issue by pkhomyakov-rms** [GrapheneOS/os-issue-tracker#762] opened 2021-10-27 20:05 UTC
Pixel 5a, 2021102613 build.

In main profile, connect bluetooth headset or car sound system. Make a phone call. Audio plays over connected bluetooth device. Hitting speaker button and selecting different output like internal speaker switches over as expected.

In secondary profile, connect bluetooth headset or car sound system. Make a phone call. Bluetooth device is shown as active audio target but sound is played via phone speaker. Hitting speaker button and attempting to change to a different output has no effect.

**Comment by dsreyes1014** [comment] 2021-11-07 11:20
I'm also affected by this bug.  On other call/sms apps such as Signal switching to any other available sound output behaves as expected.  It seems to misbehave only with the default Phone app.

**Comment by AuthenticPumpkin** [comment] 2021-11-20 14:30
Exactly the same issue since the Android 12 update on Pixel 4A (current build - latest: SP1A.211105.004.2021111414), used to work perfectly in Android 11 with the same Bluetooth earbuds.

Works in the primary profile, doesn't work for either phone calls or signal calls in the secondary profiles. Doesn't even show up as an option on calls.

Note that Bluetooth audio works just fine in the secondary profiles for music etc., only calls don't work.

I also did a quick search of the GrapheneOS matrix channel and just want it to be noted that at least 5-6 different people have reported the exact same issue since the Android 12 update using secondary profiles.

**Comment by JanOstrowka** [comment] 2021-12-22 20:38
I have also been affected by this issue. It does not work in primary profile (while I do not have a 2ndary one).

---
Specification:
os: 2021110617
phone: Pixel 5
app version: 23.0

**Comment by dailyherold** [comment] 2021-12-28 20:56
Same issue for me with Pixel 6 and `2021122018`. For car use and headset use with work, I'm going to move back to Owner profile as primary for now. Let me know if any additional info or details I can provide!

**Comment by dailyherold** [comment] 2021-12-29 04:35
Tried searching AOSP's [issue tracker](https://issuetracker.google.com/issues?q=status:open%20bluetooth) but couldn't find anything related to this specifically. Anyone know if there is an open upstream bug to follow/link? For kicks, I tried using Simple Dialer in secondary profile based on an idea from Matrix chat, but that had same issue. Which to me only confirms it's a lower level AOSP issue.

**Comment by appletalk** [comment] 2022-03-12 17:58
This issue appears to be resolved for me since the Android 12.1 update.
Bluetooth calls through the dialer work correctly in secondary user profiles on my Pixel 5.

**Comment by Zanthed** [comment] 2022-03-12 18:01
Let us know if it's still not working. Going to assume it's fixed on our latest release then.

**Comment by pkhomyakov-rms** [comment] 2022-03-12 18:22
Not working on Pixel 5a, latest release. Same as before, BT device is shown as active but sound is played via phone speaker.

**Comment by Zanthed** [comment] 2022-03-12 18:25
@appletalk What did you do to verify this is solved?

**Comment by JanOstrowka** [comment] 2022-03-12 18:38
I can confirm, that the issue has been resolved in default dialer app.

Unfortunately, I am still experiencing this issue in [Signal](https://github.com/signalapp/Signal-Android)

---
Specification:
os: 2022030801
phone: Pixel 5
app version: 23.0

**Comment by appletalk** [comment] 2022-03-12 18:50
I simply connected my Bluetooth headset to the phone in a secondary profile and made a call. Since the Android 12 release it had not worked via the phone dialer app for calls outside of the owner profile.  The same problem described in the original issue.

On the current release, I made a phone call and audio send/receive transferred to the headset and it worked as expected.
It works for me in both a profile with/without Google services installed.

**Comment by jerewolf69** [comment] 2022-05-04 17:38
I installed release 2022042000 on my Pixel 6 Pro and was not having this issue.

After updating to 2022042600, Bluetooth calls are working in the Phone app for the Owner user profile only. Phone app allows switching to Bluetooth for secondary users, but audio remains on the handset or speakerphone. Bluetooth device is connected and media playback continues to work for all users. Bluetooth continues working in Signal for all users. Phone app permissions are stock and unchanged in Owner and secondary user profiles. Tried multiple Bluetooth devices. Rebooted, updated to 2022043000, 2022050300, and 2022050301. Issue persists. Please let me know if you need any further details. Thank you!

**Comment by thestinger** [comment] 2022-05-06 08:07
Should be solved by the next OS release. You can let us know if it's still an issue after we make the release.

**Comment by Zanthed** [comment] 2022-05-09 21:50
Reported to still be an issue. Main profile works fine though.

**Comment by b8p** [comment] 2022-05-10 22:31
Filled out an issue in AOSP issue tracker.
https://issuetracker.google.com/issues/232112722

**Comment by Zanthed** [comment] 2022-05-10 22:33
Closed as this is reproducible in stock OS and an issue has been filed to AOSP.

**Closed by Zanthed** 2022-05-10 22:33 UTC
Labels: bug, upstream

**Comment by Zanthed** [comment] 2022-05-10 22:34
Further concerns or requests should be made in their issue tracker not here.

**Comment by DyNaxity** [comment] 2024-05-01 15:35
Is there still no workaround? I am having the issue with Pixel 8 and Jabra Elite 75t. Can't use the headset in Non Owner Profil... frustrating...
