### ISSUE TITLE
Do not disturb doesn't activate with multiple profiles

### ISSUE THREAD

**Issue by novocaiin** [GrapheneOS/os-issue-tracker#896] opened 2022-01-05 19:21 UTC
If multiple profiles are used, Do no disturb doesn't activate/deactivate if I'm in another profile during start/end time.
So if it's set to start at 22:00, and I switch to it at 23:00, it will not be in DND.
Conversely if it's set to end at 6am, and I switch to it at 7am it will still be in DND.

**Comment by r3g-5z** [comment] 2023-04-03 22:19
Seems like a duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/1726 which was reported to be an issue on stock OS as well. Since no one else has reported an issue like this since then or made any activity on this issue, going to assume it's been resolved.

**Closed by r3g-5z** 2023-04-03 22:19 UTC
Labels: bug, upstream

**Comment by novocaiin** [comment] 2023-04-06 23:36
@r3g-5z  Just because there hasn't been new activity doesn't mean it's been resolved so I don't think the assumption is warranted.

I have since dialed down my profile usage significantly (partly due to bugs like this one), so I'm not sure if this is still happening or not.

Will post an update once I test this.
