### ISSUE TITLE
First Bug Report... Any advice would be awesome 

### ISSUE THREAD

**Issue by ThVi11ian** [GrapheneOS/os-issue-tracker#3270] opened 2024-02-26 15:05 UTC
```
type: crash
osVersion: google/husky/husky:14/UQ1A.240205.004/2024022300:user/release-keys
package: com.google.android.gms:240513038
process: com.google.android.gms.ui
processUptime: 981240 + 204 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 96

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.nfc.action.ADAPTER_STATE_CHANGED flg=0x4000010 (has extras) } in com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver@841ce0e
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1819)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at fd.aE(:com.google.android.gms@240513038@24.05.13 (190400-602827846):12)
	at fd.N(:com.google.android.gms@240513038@24.05.13 (190400-602827846):27)
	at bs.c(:com.google.android.gms@240513038@24.05.13 (190400-602827846):66)
	at bs.a(:com.google.android.gms@240513038@24.05.13 (190400-602827846):2)
	at cx.hH(:com.google.android.gms@240513038@24.05.13 (190400-602827846):109)
	at cx.dismiss(:com.google.android.gms@240513038@24.05.13 (190400-602827846):2)
	at dxst.dismiss(:com.google.android.gms@240513038@24.05.13 (190400-602827846):8)
	at asnb.s(:com.google.android.gms@240513038@24.05.13 (190400-602827846):52)
	at asnb.k(:com.google.android.gms@240513038@24.05.13 (190400-602827846):88)
	at atxr.b(:com.google.android.gms@240513038@24.05.13 (190400-602827846):504)
	at asnb.q(:com.google.android.gms@240513038@24.05.13 (190400-602827846):10)
	at atfn.f(:com.google.android.gms@240513038@24.05.13 (190400-602827846):5)
	at asun.b(:com.google.android.gms@240513038@24.05.13 (190400-602827846):9)
	at atvy.c(:com.google.android.gms@240513038@24.05.13 (190400-602827846):64)
	at atvy.b(:com.google.android.gms@240513038@24.05.13 (190400-602827846):116)
	at com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver.a(:com.google.android.gms@240513038@24.05.13 (190400-602827846):113)
	at com.google.android.gms.libs.punchclock.tracing.TracingBroadcastReceiver.onReceive(:com.google.android.gms@240513038@24.05.13 (190400-602827846):18)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1811)
	... 12 more
```

**Comment by ThVi11ian** [comment] 2024-02-26 15:58
Basically setting up my new 8 pro. Set up the NFC security key.. I ain't no n00b... Then linked it with the windows PC for access to my cloud drive..

Giving me an error for the DNS server its running the GrapeneOS stock DNS openDNS throwing some definitely caught some Illegal Exceptions.???

I'm having issues with the ssl certs for some sites also its looping please install play store so I can clash it up... 

Running build 2024022300

ripcurrent-14.1-11208047 bootloader

Kernel 5.15.148-android14-11-g5e2dfb1b9172
#1 Mon Feb 19 17:25:23 UTC 2024

**Comment by ThVi11ian** [comment] 2024-02-26 16:04
Also throwing errors for the two factor auth using the stock Vanadium Browser I'll post a pic next time it does it..  Also I'll change the DNS to googles public... Issues with VPN also no WiFi only mobile data at the moment... Haven't exposed her to that yet..Haha

**Comment by muhomorr** [comment] 2024-03-15 07:15
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/3114

**Closed** 2024-03-15 07:16 UTC
