### ISSUE TITLE
Add letters to keypad for PIN entry.

### ISSUE THREAD

**Issue by greenerk** [GrapheneOS/os-issue-tracker#2017] opened 2023-03-14 10:09 UTC
I like to make things a little easier on myself by creating long PINs using the letters associated with each number (like on a telephone keypad).

I'd like to see an option for this brought back to GrapheneOS as it would make the PIN scrambling (which I love, by the way) a little easier - Users would be able to still tap in their "word" when scrambled, instead of having to remember the actual PIN.

Examples;  27753 could be remembered as "APPLE".  46633663 could be "GOOD-FOOD"
![keypad](https://user-images.githubusercontent.com/56622533/224967573-1162993d-61f0-4131-8d84-8df3325b7e4d.png)

**Comment by r3g-5z** [comment] 2023-03-14 11:25
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/1977

No plans to change the PIN layout

**Closed by r3g-5z** 2023-03-14 11:25 UTC
