### ISSUE TITLE
Google Play Services crash

### ISSUE THREAD

**Issue by mmoduu** [GrapheneOS/os-issue-tracker#3049] opened 2024-01-10 13:14 UTC
```
type: crash
osVersion: google/husky/husky:14/UQ1A.240105.004/2024010400:user/release-keys
package: com.google.android.gms:234914039
process: com.google.android.gms
processUptime: 26070427 + 401 ms
installer: com.android.vending
GmsCompatConfig version: 90

efpd: rethrowing error from lowpool[12]
	at akab.run(:com.google.android.gms@234914039@23.49.14 (190408-590296185):27)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at bhhk.lL(:com.google.android.gms@234914039@23.49.14 (190408-590296185):1)
	at bhhk.dispatchMessage(:com.google.android.gms@234914039@23.49.14 (190408-590296185):143)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
	Suppressed: dyxu: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.semanticlocationhistory-StoreVisitsProcessingService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/~~52IgyZTkBbUv1xIiirrKsA==/com.google.android.gms-x_Ht8BdrZOvX_k1ATNqv4g==/base.apk!/lib/arm64-v8a/libgeller_jni_lite_lib.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.google.android.gms.semanticlocationhistory.deidentifieddata.storevisits.StoreVisitsProcessingService.g(:com.google.android.gms@234914039@23.49.14 (190408-590296185):36)
	at com.google.android.gms.semanticlocationhistory.deidentifieddata.storevisits.StoreVisitsProcessingService.hc(:com.google.android.gms@234914039@23.49.14 (190408-590296185):131)
	at bhja.call(:com.google.android.gms@234914039@23.49.14 (190408-590296185):32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at akas.c(:com.google.android.gms@234914039@23.49.14 (190408-590296185):50)
	at akas.run(:com.google.android.gms@234914039@23.49.14 (190408-590296185):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at akgh.run(:com.google.android.gms@234914039@23.49.14 (190408-590296185):8)
	at java.lang.Thread.run(Thread.java:1012)

```

Crash reporter asked to "report to developers" and the corresponding button lead me here.

**Comment by muhomorr** [comment] 2024-01-21 16:14
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2552

**Closed by muhomorr** 2024-01-21 16:14 UTC
Labels: bug
