### ISSUE TITLE
system_server crash: Failed to initialize display event receiver

### ISSUE THREAD

**Issue by L11R** [GrapheneOS/os-issue-tracker#2839] opened 2023-12-12 20:47 UTC
That time I was just scrolling Mastodon app, but after clicking the link it crashed on opening Vanadium.

```
type: crash
Process: system_server
Build: google/bluejay/bluejay:14/UQ1A.231205.015/2023120800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Failed to initialize display event receiver.  status=-2147483646
	at android.view.DisplayEventReceiver.nativeInit(Native Method)
	at android.view.DisplayEventReceiver.<init>(DisplayEventReceiver.java:130)
	at android.view.Choreographer$FrameDisplayEventReceiver.<init>(Choreographer.java:1277)
	at android.view.Choreographer.<init>(Choreographer.java:281)
	at android.view.Choreographer.<init>(Choreographer.java:274)
	at android.view.Choreographer.<init>(Unknown Source:0)
	at android.view.Choreographer$1.initialValue(Choreographer.java:116)
	at android.view.Choreographer$1.initialValue(Choreographer.java:109)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at android.view.Choreographer.getInstance(Choreographer.java:309)
	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1171)
	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1132)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:397)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:150)
	at android.app.Dialog.show(Dialog.java:352)
	at com.android.server.am.ErrorDialogController$$ExternalSyntheticLambda3.accept(R8$$SyntheticClass:0)
	at com.android.server.am.ErrorDialogController.forAllDialogs(ErrorDialogController.java:164)
	at com.android.server.am.ErrorDialogController.lambda$showCrashDialogs$1(ErrorDialogController.java:182)
	at com.android.server.am.ErrorDialogController.$r8$lambda$RbiusjkAePXWGrMazzX5fIVcwYY(ErrorDialogController.java:0)
	at com.android.server.am.ErrorDialogController$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
	at com.android.server.UiThread.run(UiThread.java:45)

```

**Comment by thestinger** [comment] 2023-12-12 20:53
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2787.

**Closed by thestinger** 2023-12-12 20:53 UTC

**Comment by thestinger** [comment] 2023-12-13 01:37
https://grapheneos.org/releases#2023121200 raises the file descriptor limit and should resolve this Android 14 QPR1 issue unless it's caused by a file descriptor leak rather than higher file descriptor usage.
