### ISSUE TITLE
Camera Crashes

### ISSUE THREAD

**Issue by andrew-drogalis** [GrapheneOS/os-issue-tracker#3057] opened 2024-01-11 22:31 UTC
Here's the crash report.

```
type: crash
osVersion: google/oriole/oriole:14/UQ1A.240105.002/2024010400:user/release-keys
uid: 1000 (u:r:hal_camera_default:s0)
cmdline: /apex/com.google.pixel.camera.hal/bin/hw/android.hardware.camera.provider@2.7-service-google
processUptime: 0s

abortMessage: Timed out on NotifyCaptureSessionOpen

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: camera.provider

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 62ea4)
    /system/lib64/liblog.so (__android_log_default_aborter+12, pc 63ec)
    /apex/com.android.vndk.v34/lib64/libbinder.so (android::base::LogMessage::~LogMessage()+352, pc b1cc0)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc 3c390c)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc 3be8b8)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc 3be4a4)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc 3babd0)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc 33bbf8)
    /apex/com.google.pixel.camera.hal/lib64/libgooglecamerahal.so (android::google_camera_hal::CameraDevice::CreateCameraDeviceSession(std::__1::unique_ptr<android::google_camera_hal::CameraDeviceSession, std::__1::default_delete<android::google_camera_hal::CameraDeviceSession> >*)+80, pc 348c0)
    /apex/com.google.pixel.camera.hal/bin/hw/android.hardware.camera.provider@2.7-service-google (pc 1504c)
    /apex/com.google.pixel.camera.hal/lib64/android.hardware.camera.device-V2-ndk.so (aidl::android::hardware::camera::device::_aidl_android_hardware_camera_device_ICameraDevice_onTransact(AIBinder*, unsigned int, AParcel const*, AParcel*)+408, pc 186f8)
    /system/lib64/libbinder_ndk.so (ABBinder::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+140, pc d0bc)
    /system/lib64/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+304, pc 74b00)
    /system/lib64/libbinder.so (android::IPCThreadState::executeCommand(int)+1016, pc 5ed78)
    /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+160, pc 5e8c0)
    /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+112, pc 5f210)
    /apex/com.google.pixel.camera.hal/bin/hw/android.hardware.camera.provider@2.7-service-google (pc 3197c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+104, pc 5a768)
```

**Comment by thestinger** [comment] 2024-01-11 23:02
This is a hardware issue.

**Comment by Skealz** [comment] 2024-01-13 17:42
Hi,
I got regular errors from MTE, apps crash, interface crash, system_server crash. I checked several opened similar issues, and I see @thestinger that you said several times that this is a hardware/firmware issue.
I dont know what that really means and if those issues will be fixed or not. I am wondering if my phone hardware is faulty.

**Comment by thestinger** [comment] 2024-01-13 17:46
@Skealz This issue report is unrelated to your issues. The crash report above shows that the camera service lost the connection to the camera and timed out. Please don't bring up unrelated things in a thread.

GrapheneOS recently added user-facing crash reporting which does not exist on the stock OS. On the stock OS, the camera service would simply silently restart and reconnect in this case. GrapheneOS is reporting the abort with our own crash reporting infrastructure. Adding user-facing crash reporting in GrapheneOS does not mean GrapheneOS is causing most of the issues that it's reporting. You would normally not know about something like this on the stock OS.

This isn't meant to be a general purpose discussion forum but rather is an issue tracker and it needs to be kept on the original topic for each filed issue.

**Comment by thestinger** [comment] 2024-01-13 17:47
This shows that the camera service lost the connection to the camera and timed out. It's unlikely that it was caused by anything in GrapheneOS, but rather GrapheneOS reports these issues to end users. It might be a good idea to stop reporting specific kinds of aborts from the camera service since they seem relatively common and are therefore not unexpected.

**Closed by thestinger** 2024-01-13 17:47 UTC
Labels: bug, upstream
